// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/



// RUN: triton-shared-opt --triton-to-unstructured --canonicalize --unstructured-to-memref --canonicalize %s | FileCheck %s

module {
// CHECK-LABEL:   tt.func public @gather_simple_no_mask(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 64 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant dense<10> : tensor<64xi32>
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 5 : i32
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 64 : i32
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant dense<64> : tensor<64xi32>
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant 2 : i32
// CHECK:           %[[CONSTANT_8:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_9:.*]] = arith.constant 0 : i32
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 64 : i32, start = 0 : i32} : tensor<64xi32>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_9]] to %[[CONSTANT_7]] step %[[CONSTANT_8]] iter_args(%[[VAL_1:.*]] = %[[MAKE_RANGE_0]], %[[VAL_2:.*]] = %[[MAKE_RANGE_0]]) -> (tensor<64xi32>, tensor<64xi32>)  : i32 {
// CHECK:             %[[DIVSI_0:.*]] = arith.divsi %[[VAL_1]], %[[CONSTANT_3]] : tensor<64xi32>
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[VAL_0]], %[[CONSTANT_4]] : i32
// CHECK:             %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_5]] : i32
// CHECK:             %[[SPLAT_0:.*]] = tt.splat %[[REMSI_0]] : i32 -> tensor<64xi32>
// CHECK:             %[[ADDI_1:.*]] = arith.addi %[[DIVSI_0]], %[[SPLAT_0]] : tensor<64xi32>
// CHECK:             %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_1]] : memref<*xf32> to memref<?xf32>
// CHECK:             %[[EMPTY_0:.*]] = tensor.empty() : tensor<64xf32>
// CHECK:             %[[FOR_1:.*]] = scf.for %[[VAL_3:.*]] = %[[CONSTANT_1]] to %[[CONSTANT_2]] step %[[CONSTANT_0]] iter_args(%[[VAL_4:.*]] = %[[EMPTY_0]]) -> (tensor<64xf32>) {
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[ADDI_1]]{{\[}}%[[VAL_3]]] : tensor<64xi32>
// CHECK:               %[[INDEX_CAST_0:.*]] = arith.index_cast %[[EXTRACT_0]] : i32 to index
// CHECK:               %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[INDEX_CAST_0]]] : memref<?xf32>
// CHECK:               %[[INSERT_0:.*]] = tensor.insert %[[LOAD_0]] into %[[VAL_4]]{{\[}}%[[VAL_3]]] : tensor<64xf32>
// CHECK:               scf.yield %[[INSERT_0]] : tensor<64xf32>
// CHECK:             }
// CHECK:             %[[CAST_1:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:             scf.for %[[VAL_5:.*]] = %[[CONSTANT_1]] to %[[CONSTANT_2]] step %[[CONSTANT_0]] {
// CHECK:               %[[EXTRACT_1:.*]] = tensor.extract %[[VAL_2]]{{\[}}%[[VAL_5]]] : tensor<64xi32>
// CHECK:               %[[EXTRACT_2:.*]] = tensor.extract %[[FOR_1]]{{\[}}%[[VAL_5]]] : tensor<64xf32>
// CHECK:               %[[INDEX_CAST_1:.*]] = arith.index_cast %[[EXTRACT_1]] : i32 to index
// CHECK:               memref.store %[[EXTRACT_2]], %[[CAST_1]]{{\[}}%[[INDEX_CAST_1]]] : memref<?xf32>
// CHECK:             }
// CHECK:             %[[ADDI_2:.*]] = arith.addi %[[ADDI_1]], %[[CONSTANT_6]] : tensor<64xi32>
// CHECK:             %[[ADDI_3:.*]] = arith.addi %[[VAL_2]], %[[CONSTANT_6]] : tensor<64xi32>
// CHECK:             scf.yield %[[ADDI_2]], %[[ADDI_3]] : tensor<64xi32>, tensor<64xi32>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func public @gather_simple_no_mask(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>) attributes {noinline = false} {
    %c1_i32 = arith.constant 1 : i32
    %c2_i32 = arith.constant 2 : i32
    %c0_i32 = arith.constant 0 : i32
    %cst = arith.constant dense<64> : tensor<64xi32>
    %c64_i32 = arith.constant 64 : i32
    %c5_i32 = arith.constant 5 : i32
    %cst_0 = arith.constant dense<10> : tensor<64xi32>
    %0 = tt.make_range {end = 64 : i32, start = 0 : i32} : tensor<64xi32>
    %1 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<64x!tt.ptr<f32>>
    %2 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<64x!tt.ptr<f32>>
    %3:2 = scf.for %arg2 = %c0_i32 to %c2_i32 step %c1_i32 iter_args(%arg3 = %0, %arg4 = %0) -> (tensor<64xi32>, tensor<64xi32>)  : i32 {
      %4 = arith.divsi %arg3, %cst_0 : tensor<64xi32>
      %5 = arith.addi %arg2, %c5_i32 : i32
      %6 = arith.remsi %5, %c64_i32 : i32
      %7 = tt.splat %6 : i32 -> tensor<64xi32>
      %8 = arith.addi %4, %7 : tensor<64xi32>
      %9 = tt.addptr %1, %8 : tensor<64x!tt.ptr<f32>>, tensor<64xi32>
      %10 = tt.load %9 : tensor<64x!tt.ptr<f32>>
      %11 = tt.addptr %2, %arg4 : tensor<64x!tt.ptr<f32>>, tensor<64xi32>
      tt.store %11, %10 : tensor<64x!tt.ptr<f32>>
      %12 = arith.addi %8, %cst : tensor<64xi32>
      %13 = arith.addi %arg4, %cst : tensor<64xi32>
      scf.yield %12, %13 : tensor<64xi32>, tensor<64xi32>
    }
    tt.return
  }
}
