// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt --triton-to-linalg-experimental --split-input-file %s | FileCheck %s
// RUN: triton-shared-opt --triton-to-linalg-experimental --split-input-file %s | FileCheck %s --check-prefix=NO_STATE

// Make sure no tts.get_structured_state in the end.
// NO_STATE-LABEL: func.func @_moe_linear_kernel(
// NO_STATE-NOT: tts.get_structured_state
// NO_STATE: return

module attributes {maia.triton_kernel} {
// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>
// CHECK: #[[$ATTR_1:.+]] = affine_map<(d0, d1) -> (d0, d1)>
// CHECK: #[[$ATTR_2:.+]] = affine_map<(d0, d1) -> (d0, 0)>
// CHECK: #[[$ATTR_3:.+]] = affine_map<(d0, d1) -> (0, d1)>
// CHECK-LABEL:   func.func @_moe_linear_kernel(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32> {maia.rank = 3 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xi32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xi32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xi32> {maia.rank = 1 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xi32> {maia.rank = 1 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xi32> {maia.rank = 1 : i32, tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG10:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG11:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG12:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG13:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG14:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG15:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG16:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG17:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG18:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG19:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG20:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[TYPE_OFFSET_0:.*]] = tptr.type_offset f32  : i32
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 8 : i32
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 128 : i32
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 128 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant 64 : index
// CHECK:           %[[CONSTANT_8:.*]] = arith.constant 16 : i32
// CHECK:           %[[CONSTANT_9:.*]] = arith.constant 2 : i32
// CHECK:           %[[CONSTANT_10:.*]] = arith.constant 63 : i32
// CHECK:           %[[CONSTANT_11:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_12:.*]] = arith.constant 64 : i32
// CHECK:           %[[EMPTY_0:.*]] = tensor.empty() : tensor<64x64xi32>
// CHECK:           %[[FILL_0:.*]] = linalg.fill ins(%[[CONSTANT_12]] : i32) outs(%[[EMPTY_0]] : tensor<64x64xi32>) -> tensor<64x64xi32>
// CHECK:           %[[EMPTY_1:.*]] = tensor.empty() : tensor<64x64xf32>
// CHECK:           %[[FILL_1:.*]] = linalg.fill ins(%[[CONSTANT_3]] : f32) outs(%[[EMPTY_1]] : tensor<64x64xf32>) -> tensor<64x64xf32>
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[ARG14]], %[[CONSTANT_10]] : i32
// CHECK:           %[[DIVSI_0:.*]] = arith.divsi %[[ADDI_0]], %[[CONSTANT_12]] : i32
// CHECK:           %[[DIVSI_1:.*]] = arith.divsi %[[ARG18]], %[[CONSTANT_8]] : i32
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[DIVSI_1]], %[[CONSTANT_0]] : i32
// CHECK:           %[[SUBI_0:.*]] = arith.subi %[[DIVSI_0]], %[[MULI_0]] : i32
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[SUBI_0]], %[[CONSTANT_0]] : i32
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[ARG18]], %[[MINSI_0]] : i32
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[MULI_0]], %[[REMSI_0]] : i32
// CHECK:           %[[REMSI_1:.*]] = arith.remsi %[[ARG18]], %[[CONSTANT_8]] : i32
// CHECK:           %[[DIVSI_2:.*]] = arith.divsi %[[REMSI_1]], %[[MINSI_0]] : i32
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ADDI_1]] : i32 to index
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[ARG7]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [1], strides: [1] : memref<*xi32> to memref<1xi32, strided<[1], offset: ?>>
// CHECK:           %[[LOAD_0:.*]] = affine.load %[[REINTERPRET_CAST_0]][0] : memref<1xi32, strided<[1], offset: ?>>
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[LOAD_0]] : i32 to index
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[LOAD_0]], %[[CONSTANT_2]] : i32
// CHECK:           cf.cond_br %[[CMPI_0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           return
// CHECK:         ^bb2:
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[ARG8]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [1], strides: [1] : memref<*xi32> to memref<1xi32, strided<[1], offset: ?>>
// CHECK:           %[[LOAD_1:.*]] = affine.load %[[REINTERPRET_CAST_1]][0] : memref<1xi32, strided<[1], offset: ?>>
// CHECK:           %[[INDEX_CAST_2:.*]] = arith.index_cast %[[LOAD_1]] : i32 to index
// CHECK:           %[[REINTERPRET_CAST_2:.*]] = memref.reinterpret_cast %[[ARG6]] to offset: {{\[}}%[[INDEX_CAST_1]]], sizes: [1], strides: [1] : memref<*xi32> to memref<1xi32, strided<[1], offset: ?>>
// CHECK:           %[[LOAD_2:.*]] = affine.load %[[REINTERPRET_CAST_2]][0] : memref<1xi32, strided<[1], offset: ?>>
// CHECK:           %[[MULI_1:.*]] = arith.muli %[[LOAD_0]], %[[ARG10]] : i32
// CHECK:           %[[INDEX_CAST_3:.*]] = arith.index_cast %[[MULI_1]] : i32 to index
// CHECK:           %[[CMPI_1:.*]] = arith.cmpi sge, %[[LOAD_1]], %[[LOAD_2]] : i32
// CHECK:           cf.cond_br %[[CMPI_1]], ^bb1, ^bb3
// CHECK:         ^bb3:
// CHECK:           %[[EMPTY_2:.*]] = tensor.empty() : tensor<64xi32>
// CHECK:           %[[GENERIC_0:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[EMPTY_2]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_0:.*]]: i32):
// CHECK:             %[[INDEX_0:.*]] = linalg.index 0 : index
// CHECK:             %[[INDEX_CAST_4:.*]] = arith.index_cast %[[INDEX_0]] : index to i32
// CHECK:             linalg.yield %[[INDEX_CAST_4]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[FILL_2:.*]] = linalg.fill ins(%[[LOAD_1]] : i32) outs(%[[EMPTY_2]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:           %[[GENERIC_1:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[FILL_2]], %[[GENERIC_0]] : tensor<64xi32>, tensor<64xi32>) outs(%[[FILL_2]] : tensor<64xi32>) {
// CHECK:           ^bb0(%[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32):
// CHECK:             %[[ADDI_2:.*]] = arith.addi %[[VAL_1]], %[[VAL_2]] : i32
// CHECK:             linalg.yield %[[ADDI_2]] : i32
// CHECK:           } -> tensor<64xi32>
// CHECK:           %[[MULI_2:.*]] = arith.muli %[[DIVSI_2]], %[[CONSTANT_12]] : i32
// CHECK:           %[[INDEX_CAST_5:.*]] = arith.index_cast %[[MULI_2]] : i32 to index
// CHECK:           %[[FILL_3:.*]] = linalg.fill ins(%[[LOAD_2]] : i32) outs(%[[EMPTY_2]] : tensor<64xi32>) -> tensor<64xi32>
// CHECK:           %[[EMPTY_3:.*]] = tensor.empty() : tensor<64xi1>
// CHECK:           %[[GENERIC_2:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[GENERIC_1]], %[[FILL_3]] : tensor<64xi32>, tensor<64xi32>) outs(%[[EMPTY_3]] : tensor<64xi1>) {
// CHECK:           ^bb0(%[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i1):
// CHECK:             %[[CMPI_2:.*]] = arith.cmpi slt, %[[VAL_4]], %[[VAL_5]] : i32
// CHECK:             linalg.yield %[[CMPI_2]] : i1
// CHECK:           } -> tensor<64xi1>
// CHECK:           %[[ADDI_3:.*]] = arith.addi %[[INDEX_CAST_1]], %[[INDEX_CAST_2]] : index
// CHECK:           %[[ADDI_4:.*]] = arith.addi %[[INDEX_CAST_2]], %[[CONSTANT_7]] : index
// CHECK:           %[[INDEX_CAST_6:.*]] = arith.index_cast %[[LOAD_2]] : i32 to index
// CHECK:           %[[MINSI_1:.*]] = arith.minsi %[[ADDI_4]], %[[INDEX_CAST_6]] : index
// CHECK:           %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_1]], %[[INDEX_CAST_2]] : index
// CHECK:           %[[SUBI_1:.*]] = arith.subi %[[MAXSI_0]], %[[INDEX_CAST_2]] : index
// CHECK:           %[[REINTERPRET_CAST_3:.*]] = memref.reinterpret_cast %[[ARG4]] to offset: {{\[}}%[[ADDI_3]]], sizes: [64], strides: [1] : memref<*xi32> to memref<64xi32, strided<[1], offset: ?>>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<64xi32>
// CHECK:           %[[SUBVIEW_0:.*]] = memref.subview %[[REINTERPRET_CAST_3]][0] {{\[}}%[[SUBI_1]]] [1] : memref<64xi32, strided<[1], offset: ?>> to memref<?xi32, strided<[1], offset: ?>>
// CHECK:           %[[SUBVIEW_1:.*]] = memref.subview %[[ALLOC_0]][0] {{\[}}%[[SUBI_1]]] [1] : memref<64xi32> to memref<?xi32, strided<[1]>>
// CHECK:           memref.copy %[[SUBVIEW_0]], %[[SUBVIEW_1]] : memref<?xi32, strided<[1], offset: ?>> to memref<?xi32, strided<[1]>>
// CHECK:           %[[EXPAND_SHAPE_0:.*]] = tensor.expand_shape %[[GENERIC_0]] {{\[\[}}0, 1]] output_shape [1, 64] : tensor<64xi32> into tensor<1x64xi32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : memref<*xf32> to tensor<64x64x!ptr.ptr<#tptr.default_memory_space>>
// CHECK:           %[[INDEX_CAST_7:.*]] = arith.index_cast %[[ARG11]] : i32 to index
// CHECK:           %[[MULI_3:.*]] = arith.muli %[[INDEX_CAST_5]], %[[INDEX_CAST_7]] : index
// CHECK:           %[[MULI_4:.*]] = arith.muli %[[INDEX_CAST_7]], %[[CONSTANT_4]] : index
// CHECK:           %[[FOR_0:.*]]:3 = scf.for %[[VAL_7:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_9]] step %[[CONSTANT_11]] iter_args(%[[VAL_8:.*]] = %[[FILL_1]], %[[VAL_9:.*]] = %[[UNREALIZED_CONVERSION_CAST_0]], %[[VAL_10:.*]] = %[[INDEX_CAST_3]]) -> (tensor<64x64xf32>, tensor<64x64x!ptr.ptr<#tptr.default_memory_space>>, index)  : i32 {
// CHECK:             %[[MULI_5:.*]] = arith.muli %[[VAL_7]], %[[CONSTANT_12]] : i32
// CHECK:             %[[SUBI_2:.*]] = arith.subi %[[CONSTANT_1]], %[[MULI_5]] : i32
// CHECK:             %[[EXPAND_SHAPE_1:.*]] = tensor.expand_shape %[[GENERIC_2]] {{\[\[}}0, 1]] output_shape [64, 1] : tensor<64xi1> into tensor<64x1xi1>
// CHECK:             %[[EMPTY_4:.*]] = tensor.empty() : tensor<1x64xi32>
// CHECK:             %[[FILL_4:.*]] = linalg.fill ins(%[[SUBI_2]] : i32) outs(%[[EMPTY_4]] : tensor<1x64xi32>) -> tensor<1x64xi32>
// CHECK:             %[[EMPTY_5:.*]] = tensor.empty() : tensor<1x64xi1>
// CHECK:             %[[GENERIC_3:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[EXPAND_SHAPE_0]], %[[FILL_4]] : tensor<1x64xi32>, tensor<1x64xi32>) outs(%[[EMPTY_5]] : tensor<1x64xi1>) {
// CHECK:             ^bb0(%[[VAL_11:.*]]: i32, %[[VAL_12:.*]]: i32, %[[VAL_13:.*]]: i1):
// CHECK:               %[[CMPI_3:.*]] = arith.cmpi slt, %[[VAL_11]], %[[VAL_12]] : i32
// CHECK:               linalg.yield %[[CMPI_3]] : i1
// CHECK:             } -> tensor<1x64xi1>
// CHECK:             %[[EMPTY_6:.*]] = tensor.empty() : tensor<64x64xi1>
// CHECK:             %[[GENERIC_4:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_2]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[EXPAND_SHAPE_1]] : tensor<64x1xi1>) outs(%[[EMPTY_6]] : tensor<64x64xi1>) attrs =  {broadcastDims = array<i64: 1>} {
// CHECK:             ^bb0(%[[VAL_14:.*]]: i1, %[[VAL_15:.*]]: i1):
// CHECK:               linalg.yield %[[VAL_14]] : i1
// CHECK:             } -> tensor<64x64xi1>
// CHECK:             %[[GENERIC_5:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_3]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_3]] : tensor<1x64xi1>) outs(%[[EMPTY_6]] : tensor<64x64xi1>) attrs =  {broadcastDims = array<i64: 0>} {
// CHECK:             ^bb0(%[[VAL_16:.*]]: i1, %[[VAL_17:.*]]: i1):
// CHECK:               linalg.yield %[[VAL_16]] : i1
// CHECK:             } -> tensor<64x64xi1>
// CHECK:             %[[GENERIC_6:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_4]], %[[GENERIC_5]] : tensor<64x64xi1>, tensor<64x64xi1>) outs(%[[GENERIC_4]] : tensor<64x64xi1>) {
// CHECK:             ^bb0(%[[VAL_18:.*]]: i1, %[[VAL_19:.*]]: i1, %[[VAL_20:.*]]: i1):
// CHECK:               %[[ANDI_0:.*]] = arith.andi %[[VAL_18]], %[[VAL_19]] : i1
// CHECK:               linalg.yield %[[ANDI_0]] : i1
// CHECK:             } -> tensor<64x64xi1>
// CHECK:             %[[GENERIC_7:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_9]], %[[GENERIC_6]], %[[FILL_1]] : tensor<64x64x!ptr.ptr<#tptr.default_memory_space>>, tensor<64x64xi1>, tensor<64x64xf32>) outs(%[[EMPTY_1]] : tensor<64x64xf32>) {
// CHECK:             ^bb0(%[[VAL_21:.*]]: !ptr.ptr<#tptr.default_memory_space>, %[[VAL_22:.*]]: i1, %[[VAL_23:.*]]: f32, %[[VAL_24:.*]]: f32):
// CHECK:               %[[TO_MEMREF_0:.*]] = tptr.to_memref %[[VAL_21]] : <#tptr.default_memory_space> to memref<1xf32>
// CHECK:               %[[IF_0:.*]] = scf.if %[[VAL_22]] -> (f32) {
// CHECK:                 %[[LOAD_3:.*]] = memref.load %[[TO_MEMREF_0]]{{\[}}%[[CONSTANT_6]]] : memref<1xf32>
// CHECK:                 scf.yield %[[LOAD_3]] : f32
// CHECK:               } else {
// CHECK:                 scf.yield %[[VAL_23]] : f32
// CHECK:               }
// CHECK:               linalg.yield %[[IF_0]] : f32
// CHECK:             } -> tensor<64x64xf32>
// CHECK:             %[[INDEX_CAST_8:.*]] = arith.index_cast %[[SUBI_2]] : i32 to index
// CHECK:             %[[MINSI_2:.*]] = arith.minsi %[[INDEX_CAST_8]], %[[CONSTANT_7]] : index
// CHECK:             %[[MAXSI_1:.*]] = arith.maxsi %[[MINSI_2]], %[[CONSTANT_6]] : index
// CHECK:             %[[ADDI_5:.*]] = arith.addi %[[VAL_10]], %[[MULI_3]] : index
// CHECK:             %[[REMSI_2:.*]] = arith.remsi %[[ADDI_5]], %[[MULI_4]] : index
// CHECK:             %[[SUBI_3:.*]] = arith.subi %[[ADDI_5]], %[[REMSI_2]] : index
// CHECK:             %[[ADDI_6:.*]] = arith.addi %[[REMSI_2]], %[[CONSTANT_7]] : index
// CHECK:             %[[MINSI_3:.*]] = arith.minsi %[[ADDI_6]], %[[MULI_4]] : index
// CHECK:             %[[SUBI_4:.*]] = arith.subi %[[MINSI_3]], %[[REMSI_2]] : index
// CHECK:             %[[SUBI_5:.*]] = arith.subi %[[CONSTANT_7]], %[[SUBI_4]] : index
// CHECK:             %[[REINTERPRET_CAST_4:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: {{\[}}%[[ADDI_5]]], sizes: [64, %[[SUBI_4]]], strides: [1, %[[INDEX_CAST_7]]] : memref<*xf32> to memref<64x?xf32, strided<[1, ?], offset: ?>>
// CHECK:             %[[REINTERPRET_CAST_5:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: {{\[}}%[[SUBI_3]]], sizes: [64, %[[SUBI_5]]], strides: [1, %[[INDEX_CAST_7]]] : memref<*xf32> to memref<64x?xf32, strided<[1, ?], offset: ?>>
// CHECK:             %[[DIM_0:.*]] = memref.dim %[[REINTERPRET_CAST_4]], %[[CONSTANT_5]] : memref<64x?xf32, strided<[1, ?], offset: ?>>
// CHECK:             %[[DIM_1:.*]] = memref.dim %[[REINTERPRET_CAST_5]], %[[CONSTANT_5]] : memref<64x?xf32, strided<[1, ?], offset: ?>>
// CHECK:             %[[SUBVIEW_2:.*]] = memref.subview %[[REINTERPRET_CAST_4]][0, 0] {{\[}}%[[MAXSI_1]], %[[DIM_0]]] [1, 1] : memref<64x?xf32, strided<[1, ?], offset: ?>> to memref<?x?xf32, strided<[1, ?], offset: ?>>
// CHECK:             %[[CAST_0:.*]] = memref.cast %[[SUBVIEW_2]] : memref<?x?xf32, strided<[1, ?], offset: ?>> to memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:             %[[SUBVIEW_3:.*]] = memref.subview %[[REINTERPRET_CAST_5]][0, 0] {{\[}}%[[MAXSI_1]], %[[DIM_1]]] [1, 1] : memref<64x?xf32, strided<[1, ?], offset: ?>> to memref<?x?xf32, strided<[1, ?], offset: ?>>
// CHECK:             %[[CAST_1:.*]] = memref.cast %[[SUBVIEW_3]] : memref<?x?xf32, strided<[1, ?], offset: ?>> to memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[CAST_0]] restrict : memref<?x?xf32, strided<[?, ?], offset: ?>> to tensor<?x?xf32>
// CHECK:             %[[TO_TENSOR_1:.*]] = bufferization.to_tensor %[[CAST_1]] restrict : memref<?x?xf32, strided<[?, ?], offset: ?>> to tensor<?x?xf32>
// CHECK:             %[[INSERT_SLICE_0:.*]] = tensor.insert_slice %[[TO_TENSOR_0]] into %[[FILL_1]][0, 0] {{\[}}%[[MAXSI_1]], %[[DIM_0]]] [1, 1] : tensor<?x?xf32> into tensor<64x64xf32>
// CHECK:             %[[INSERT_SLICE_1:.*]] = tensor.insert_slice %[[TO_TENSOR_1]] into %[[INSERT_SLICE_0]][0, %[[DIM_0]]] {{\[}}%[[MAXSI_1]], %[[DIM_1]]] [1, 1] : tensor<?x?xf32> into tensor<64x64xf32>
// CHECK:             %[[MATMUL_0:.*]] = linalg.matmul ins(%[[GENERIC_7]], %[[INSERT_SLICE_1]] : tensor<64x64xf32>, tensor<64x64xf32>) outs(%[[FILL_1]] : tensor<64x64xf32>) -> tensor<64x64xf32>
// CHECK:             %[[GENERIC_8:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_8]], %[[MATMUL_0]] : tensor<64x64xf32>, tensor<64x64xf32>) outs(%[[VAL_8]] : tensor<64x64xf32>) {
// CHECK:             ^bb0(%[[VAL_25:.*]]: f32, %[[VAL_26:.*]]: f32, %[[VAL_27:.*]]: f32):
// CHECK:               %[[ADDF_0:.*]] = arith.addf %[[VAL_25]], %[[VAL_26]] : f32
// CHECK:               linalg.yield %[[ADDF_0]] : f32
// CHECK:             } -> tensor<64x64xf32>
// CHECK:             %[[GENERIC_9:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_9]], %[[FILL_0]] : tensor<64x64x!ptr.ptr<#tptr.default_memory_space>>, tensor<64x64xi32>) outs(%[[VAL_9]] : tensor<64x64x!ptr.ptr<#tptr.default_memory_space>>) {
// CHECK:             ^bb0(%[[VAL_28:.*]]: !ptr.ptr<#tptr.default_memory_space>, %[[VAL_29:.*]]: i32, %[[VAL_30:.*]]: !ptr.ptr<#tptr.default_memory_space>):
// CHECK:               %[[MULI_6:.*]] = arith.muli %[[VAL_29]], %[[TYPE_OFFSET_0]] : i32
// CHECK:               %[[PTRADD_0:.*]] = tptr.ptradd %[[VAL_28]] %[[MULI_6]] : <#tptr.default_memory_space>, i32 to <#tptr.default_memory_space>
// CHECK:               linalg.yield %[[PTRADD_0]] : !ptr.ptr<#tptr.default_memory_space>
// CHECK:             } -> tensor<64x64x!ptr.ptr<#tptr.default_memory_space>>
// CHECK:             %[[ADDI_7:.*]] = arith.addi %[[VAL_10]], %[[CONSTANT_7]] : index
// CHECK:             scf.yield %[[GENERIC_8]], %[[GENERIC_9]], %[[ADDI_7]] : tensor<64x64xf32>, tensor<64x64x!ptr.ptr<#tptr.default_memory_space>>, index
// CHECK:           }
// CHECK:           %[[MULI_7:.*]] = arith.muli %[[LOAD_0]], %[[ARG12]] : i32
// CHECK:           %[[INDEX_CAST_9:.*]] = arith.index_cast %[[MULI_7]] : i32 to index
// CHECK:           %[[ADDI_8:.*]] = arith.addi %[[INDEX_CAST_9]], %[[INDEX_CAST_5]] : index
// CHECK:           %[[REMSI_3:.*]] = arith.remsi %[[ADDI_8]], %[[CONSTANT_4]] : index
// CHECK:           %[[SUBI_6:.*]] = arith.subi %[[ADDI_8]], %[[REMSI_3]] : index
// CHECK:           %[[ADDI_9:.*]] = arith.addi %[[REMSI_3]], %[[CONSTANT_7]] : index
// CHECK:           %[[MINSI_4:.*]] = arith.minsi %[[ADDI_9]], %[[CONSTANT_4]] : index
// CHECK:           %[[SUBI_7:.*]] = arith.subi %[[MINSI_4]], %[[REMSI_3]] : index
// CHECK:           %[[SUBI_8:.*]] = arith.subi %[[CONSTANT_7]], %[[SUBI_7]] : index
// CHECK:           %[[REINTERPRET_CAST_6:.*]] = memref.reinterpret_cast %[[ARG2]] to offset: {{\[}}%[[ADDI_8]]], sizes: [1, %[[SUBI_7]]], strides: [64, 1] : memref<*xf32> to memref<1x?xf32, strided<[64, 1], offset: ?>>
// CHECK:           %[[REINTERPRET_CAST_7:.*]] = memref.reinterpret_cast %[[ARG2]] to offset: {{\[}}%[[SUBI_6]]], sizes: [1, %[[SUBI_8]]], strides: [64, 1] : memref<*xf32> to memref<1x?xf32, strided<[64, 1], offset: ?>>
// CHECK:           %[[ALLOC_1:.*]] = memref.alloc() : memref<1x64xf32>
// CHECK:           %[[DIM_2:.*]] = memref.dim %[[REINTERPRET_CAST_6]], %[[CONSTANT_5]] : memref<1x?xf32, strided<[64, 1], offset: ?>>
// CHECK:           %[[DIM_3:.*]] = memref.dim %[[REINTERPRET_CAST_7]], %[[CONSTANT_5]] : memref<1x?xf32, strided<[64, 1], offset: ?>>
// CHECK:           %[[SUBVIEW_4:.*]] = memref.subview %[[ALLOC_1]][0, 0] [1, %[[DIM_2]]] [1, 1] : memref<1x64xf32> to memref<1x?xf32, strided<[64, 1]>>
// CHECK:           %[[SUBVIEW_5:.*]] = memref.subview %[[ALLOC_1]][0, %[[DIM_2]]] [1, %[[DIM_3]]] [1, 1] : memref<1x64xf32> to memref<1x?xf32, strided<[64, 1], offset: ?>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_6]], %[[SUBVIEW_4]] : memref<1x?xf32, strided<[64, 1], offset: ?>> to memref<1x?xf32, strided<[64, 1]>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_7]], %[[SUBVIEW_5]] : memref<1x?xf32, strided<[64, 1], offset: ?>> to memref<1x?xf32, strided<[64, 1], offset: ?>>
// CHECK:           %[[TO_TENSOR_2:.*]] = bufferization.to_tensor %[[ALLOC_1]] restrict writable : memref<1x64xf32> to tensor<1x64xf32>
// CHECK:           %[[GENERIC_10:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_3]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[TO_TENSOR_2]] : tensor<1x64xf32>) outs(%[[EMPTY_1]] : tensor<64x64xf32>) attrs =  {broadcastDims = array<i64: 0>} {
// CHECK:           ^bb0(%[[VAL_31:.*]]: f32, %[[VAL_32:.*]]: f32):
// CHECK:             linalg.yield %[[VAL_31]] : f32
// CHECK:           } -> tensor<64x64xf32>
// CHECK:           %[[GENERIC_11:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_33:.*]]#0, %[[GENERIC_10]] : tensor<64x64xf32>, tensor<64x64xf32>) outs(%[[VAL_33]]#0 : tensor<64x64xf32>) {
// CHECK:           ^bb0(%[[VAL_34:.*]]: f32, %[[VAL_35:.*]]: f32, %[[VAL_36:.*]]: f32):
// CHECK:             %[[ADDF_1:.*]] = arith.addf %[[VAL_34]], %[[VAL_35]] : f32
// CHECK:             linalg.yield %[[ADDF_1]] : f32
// CHECK:           } -> tensor<64x64xf32>
// CHECK:           %[[REINTERPRET_CAST_8:.*]] = memref.reinterpret_cast %[[ARG5]] to offset: {{\[}}%[[ADDI_3]]], sizes: [64], strides: [1] : memref<*xi32> to memref<64xi32, strided<[1], offset: ?>>
// CHECK:           %[[ALLOC_2:.*]] = memref.alloc() : memref<64xi32>
// CHECK:           %[[SUBVIEW_6:.*]] = memref.subview %[[REINTERPRET_CAST_8]][0] {{\[}}%[[SUBI_1]]] [1] : memref<64xi32, strided<[1], offset: ?>> to memref<?xi32, strided<[1], offset: ?>>
// CHECK:           %[[SUBVIEW_7:.*]] = memref.subview %[[ALLOC_2]][0] {{\[}}%[[SUBI_1]]] [1] : memref<64xi32> to memref<?xi32, strided<[1]>>
// CHECK:           memref.copy %[[SUBVIEW_6]], %[[SUBVIEW_7]] : memref<?xi32, strided<[1], offset: ?>> to memref<?xi32, strided<[1]>>
// CHECK:           %[[TO_TENSOR_3:.*]] = bufferization.to_tensor %[[ALLOC_2]] restrict writable : memref<64xi32> to tensor<64xi32>
// CHECK:           %[[INDEX_CAST_10:.*]] = arith.index_cast %[[ARG13]] : i32 to index
// CHECK:           %[[ADDI_10:.*]] = arith.addi %[[INDEX_CAST_5]], %[[CONSTANT_7]] : index
// CHECK:           %[[MINSI_5:.*]] = arith.minsi %[[ADDI_10]], %[[CONSTANT_4]] : index
// CHECK:           %[[MAXSI_2:.*]] = arith.maxsi %[[MINSI_5]], %[[INDEX_CAST_5]] : index
// CHECK:           %[[SUBI_9:.*]] = arith.subi %[[MAXSI_2]], %[[INDEX_CAST_5]] : index
// CHECK:           %[[MINSI_6:.*]] = arith.minsi %[[SUBI_1]], %[[CONSTANT_7]] : index
// CHECK:           %[[MINSI_7:.*]] = arith.minsi %[[SUBI_9]], %[[CONSTANT_7]] : index
// CHECK:           %[[MINSI_8:.*]] = arith.minsi %[[MINSI_6]], %[[CONSTANT_7]] : index
// CHECK:           scf.for %[[VAL_37:.*]] = %[[CONSTANT_6]] to %[[MINSI_8]] step %[[CONSTANT_5]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[TO_TENSOR_3]]{{\[}}%[[VAL_37]]] : tensor<64xi32>
// CHECK:             %[[INDEX_CAST_11:.*]] = arith.index_cast %[[EXTRACT_0]] : i32 to index
// CHECK:             %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[GENERIC_11]]{{\[}}%[[VAL_37]], 0] [1, %[[MINSI_7]]] [1, 1] : tensor<64x64xf32> to tensor<1x?xf32>
// CHECK:             %[[MULI_8:.*]] = arith.muli %[[INDEX_CAST_11]], %[[INDEX_CAST_10]] : index
// CHECK:             %[[ADDI_11:.*]] = arith.addi %[[MULI_8]], %[[INDEX_CAST_5]] : index
// CHECK:             %[[REINTERPRET_CAST_9:.*]] = memref.reinterpret_cast %[[ARG3]] to offset: {{\[}}%[[ADDI_11]]], sizes: [1, 64], strides: {{\[}}%[[INDEX_CAST_10]], 1] : memref<*xf32> to memref<1x64xf32, strided<[?, 1], offset: ?>>
// CHECK:             %[[SUBVIEW_8:.*]] = memref.subview %[[REINTERPRET_CAST_9]][0, 0] [1, %[[MINSI_7]]] [1, 1] : memref<1x64xf32, strided<[?, 1], offset: ?>> to memref<1x?xf32, strided<[?, 1], offset: ?>>
// CHECK:             %[[CAST_2:.*]] = memref.cast %[[SUBVIEW_8]] : memref<1x?xf32, strided<[?, 1], offset: ?>> to memref<1x?xf32, strided<[?, ?], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[CAST_2]] : (tensor<1x?xf32>, memref<1x?xf32, strided<[?, ?], offset: ?>>) -> ()
// CHECK:           }
// CHECK:           return
// CHECK:         }
  tt.func public @_moe_linear_kernel(%arg0: !tt.ptr<f32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32> {maia.rank = 3 : i32, tt.divisibility = 16 : i32}, %arg2: !tt.ptr<f32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32}, %arg3: !tt.ptr<f32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32}, %arg4: !tt.ptr<i32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32}, %arg5: !tt.ptr<i32> {maia.rank = 2 : i32, tt.divisibility = 16 : i32}, %arg6: !tt.ptr<i32> {maia.rank = 1 : i32, tt.divisibility = 16 : i32}, %arg7: !tt.ptr<i32> {maia.rank = 1 : i32, tt.divisibility = 16 : i32}, %arg8: !tt.ptr<i32> {maia.rank = 1 : i32, tt.divisibility = 16 : i32}, %arg9: i32 {tt.divisibility = 16 : i32}, %arg10: i32 {tt.divisibility = 16 : i32}, %arg11: i32 {tt.divisibility = 16 : i32}, %arg12: i32 {tt.divisibility = 16 : i32}, %arg13: i32 {tt.divisibility = 16 : i32}, %arg14: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %c16_i32 = arith.constant 16 : i32
    %c2_i32 = arith.constant 2 : i32
    %c63_i32 = arith.constant 63 : i32
    %c1_i32 = arith.constant 1 : i32
    %cst = arith.constant dense<64> : tensor<64x64xi32>
    %cst_0 = arith.constant dense<0.000000e+00> : tensor<64x64xf32>
    %cst_1 = arith.constant dense<128> : tensor<64xi32>
    %c128_i32 = arith.constant 128 : i32
    %c64_i32 = arith.constant 64 : i32
    %c0_i32 = arith.constant 0 : i32
    %c8_i32 = arith.constant 8 : i32
    %0 = tt.get_program_id x : i32
    %1 = arith.addi %arg14, %c63_i32 : i32
    %2 = arith.divsi %1, %c64_i32 : i32
    %3 = arith.divsi %0, %c16_i32 : i32
    %4 = arith.muli %3, %c8_i32 : i32
    %5 = arith.subi %2, %4 : i32
    %6 = arith.minsi %5, %c8_i32 : i32
    %7 = arith.remsi %0, %6 : i32
    %8 = arith.addi %4, %7 : i32
    %9 = arith.remsi %0, %c16_i32 : i32
    %10 = arith.divsi %9, %6 : i32
    %11 = tt.addptr %arg7, %8 : !tt.ptr<i32>, i32
    %12 = tt.load %11 : !tt.ptr<i32>
    %13 = arith.cmpi slt, %12, %c0_i32 : i32
    cf.cond_br %13, ^bb1, ^bb2
  ^bb1:  // 2 preds: ^bb0, ^bb2
    tt.return
  ^bb2:  // pred: ^bb0
    %14 = tt.addptr %arg8, %8 : !tt.ptr<i32>, i32
    %15 = tt.load %14 : !tt.ptr<i32>
    %16 = tt.addptr %arg6, %12 : !tt.ptr<i32>, i32
    %17 = tt.load %16 : !tt.ptr<i32>
    %18 = tt.addptr %arg4, %12 : !tt.ptr<i32>, i32
    %19 = tt.addptr %arg5, %12 : !tt.ptr<i32>, i32
    %20 = arith.muli %12, %arg10 : i32
    %21 = tt.addptr %arg1, %20 : !tt.ptr<f32>, i32
    %22 = arith.cmpi sge, %15, %17 : i32
    cf.cond_br %22, ^bb1, ^bb3
  ^bb3:  // pred: ^bb2
    %23 = tt.make_range {end = 64 : i32, start = 0 : i32} : tensor<64xi32>
    %24 = tt.splat %15 : i32 -> tensor<64xi32>
    %25 = arith.addi %24, %23 : tensor<64xi32>
    %26 = arith.muli %10, %c64_i32 : i32
    %27 = tt.splat %26 : i32 -> tensor<64xi32>
    %28 = arith.addi %27, %23 : tensor<64xi32>
    %29 = arith.remsi %28, %cst_1 : tensor<64xi32>
    %30 = tt.splat %17 : i32 -> tensor<64xi32>
    %31 = arith.cmpi slt, %25, %30 : tensor<64xi32>
    %32 = tt.splat %18 : !tt.ptr<i32> -> tensor<64x!tt.ptr<i32>>
    %33 = tt.addptr %32, %25 : tensor<64x!tt.ptr<i32>>, tensor<64xi32>
    %34 = tt.load %33, %31 : tensor<64x!tt.ptr<i32>>
    %35 = tt.expand_dims %34 {axis = 1 : i32} : tensor<64xi32> -> tensor<64x1xi32>
    %36 = tt.splat %arg9 : i32 -> tensor<64x1xi32>
    %37 = arith.muli %35, %36 : tensor<64x1xi32>
    %38 = tt.expand_dims %23 {axis = 0 : i32} : tensor<64xi32> -> tensor<1x64xi32>
    %39 = tt.broadcast %37 : tensor<64x1xi32> -> tensor<64x64xi32>
    %40 = tt.broadcast %38 : tensor<1x64xi32> -> tensor<64x64xi32>
    %41 = arith.addi %39, %40 : tensor<64x64xi32>
    %42 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<64x64x!tt.ptr<f32>>
    %43 = tt.addptr %42, %41 : tensor<64x64x!tt.ptr<f32>>, tensor<64x64xi32>
    %44 = tt.expand_dims %23 {axis = 1 : i32} : tensor<64xi32> -> tensor<64x1xi32>
    %45 = tt.expand_dims %29 {axis = 0 : i32} : tensor<64xi32> -> tensor<1x64xi32>
    %46 = tt.splat %arg11 : i32 -> tensor<1x64xi32>
    %47 = arith.muli %45, %46 : tensor<1x64xi32>
    %48 = tt.broadcast %44 : tensor<64x1xi32> -> tensor<64x64xi32>
    %49 = tt.broadcast %47 : tensor<1x64xi32> -> tensor<64x64xi32>
    %50 = arith.addi %48, %49 : tensor<64x64xi32>
    %51 = tt.splat %21 : !tt.ptr<f32> -> tensor<64x64x!tt.ptr<f32>>
    %52 = tt.addptr %51, %50 : tensor<64x64x!tt.ptr<f32>>, tensor<64x64xi32>
    %53:3 = scf.for %arg15 = %c0_i32 to %c2_i32 step %c1_i32 iter_args(%arg16 = %cst_0, %arg17 = %43, %arg18 = %52) -> (tensor<64x64xf32>, tensor<64x64x!tt.ptr<f32>>, tensor<64x64x!tt.ptr<f32>>)  : i32 {
      %79 = arith.muli %arg15, %c64_i32 : i32
      %80 = arith.subi %c128_i32, %79 : i32
      %81 = tt.expand_dims %31 {axis = 1 : i32} : tensor<64xi1> -> tensor<64x1xi1>
      %82 = tt.splat %80 : i32 -> tensor<1x64xi32>
      %83 = arith.cmpi slt, %38, %82 : tensor<1x64xi32>
      %84 = tt.broadcast %81 : tensor<64x1xi1> -> tensor<64x64xi1>
      %85 = tt.broadcast %83 : tensor<1x64xi1> -> tensor<64x64xi1>
      %86 = arith.andi %84, %85 : tensor<64x64xi1>
      %87 = tt.load %arg17, %86, %cst_0 : tensor<64x64x!tt.ptr<f32>>
      %88 = tt.splat %80 : i32 -> tensor<64x1xi32>
      %89 = arith.cmpi slt, %44, %88 : tensor<64x1xi32>
      %90 = tt.broadcast %89 : tensor<64x1xi1> -> tensor<64x64xi1>
      %91 = tt.load %arg18, %90, %cst_0 : tensor<64x64x!tt.ptr<f32>>
      %92 = tt.dot %87, %91, %arg16 : tensor<64x64xf32> * tensor<64x64xf32> -> tensor<64x64xf32>
      %93 = tt.addptr %arg17, %cst : tensor<64x64x!tt.ptr<f32>>, tensor<64x64xi32>
      %94 = tt.addptr %arg18, %cst : tensor<64x64x!tt.ptr<f32>>, tensor<64x64xi32>
      scf.yield %92, %93, %94 : tensor<64x64xf32>, tensor<64x64x!tt.ptr<f32>>, tensor<64x64x!tt.ptr<f32>>
    }
    %54 = arith.muli %12, %arg12 : i32
    %55 = tt.addptr %arg2, %54 : !tt.ptr<f32>, i32
    %56 = tt.splat %55 : !tt.ptr<f32> -> tensor<1x64x!tt.ptr<f32>>
    %57 = tt.addptr %56, %45 : tensor<1x64x!tt.ptr<f32>>, tensor<1x64xi32>
    %58 = tt.load %57 : tensor<1x64x!tt.ptr<f32>>
    %59 = tt.broadcast %58 : tensor<1x64xf32> -> tensor<64x64xf32>
    %60 = arith.addf %53#0, %59 : tensor<64x64xf32>
    %61 = arith.cmpi slt, %28, %cst_1 : tensor<64xi32>
    %62 = tt.splat %19 : !tt.ptr<i32> -> tensor<64x!tt.ptr<i32>>
    %63 = tt.addptr %62, %25 : tensor<64x!tt.ptr<i32>>, tensor<64xi32>
    %64 = tt.load %63, %31 : tensor<64x!tt.ptr<i32>>
    %65 = tt.expand_dims %64 {axis = 1 : i32} : tensor<64xi32> -> tensor<64x1xi32>
    %66 = tt.splat %arg13 : i32 -> tensor<64x1xi32>
    %67 = arith.muli %65, %66 : tensor<64x1xi32>
    %68 = tt.expand_dims %28 {axis = 0 : i32} : tensor<64xi32> -> tensor<1x64xi32>
    %69 = tt.broadcast %67 : tensor<64x1xi32> -> tensor<64x64xi32>
    %70 = tt.broadcast %68 : tensor<1x64xi32> -> tensor<64x64xi32>
    %71 = arith.addi %69, %70 : tensor<64x64xi32>
    %72 = tt.splat %arg3 : !tt.ptr<f32> -> tensor<64x64x!tt.ptr<f32>>
    %73 = tt.addptr %72, %71 : tensor<64x64x!tt.ptr<f32>>, tensor<64x64xi32>
    %74 = tt.expand_dims %31 {axis = 1 : i32} : tensor<64xi1> -> tensor<64x1xi1>
    %75 = tt.expand_dims %61 {axis = 0 : i32} : tensor<64xi1> -> tensor<1x64xi1>
    %76 = tt.broadcast %74 : tensor<64x1xi1> -> tensor<64x64xi1>
    %77 = tt.broadcast %75 : tensor<1x64xi1> -> tensor<64x64xi1>
    %78 = arith.andi %76, %77 : tensor<64x64xi1>
    tt.store %73, %60, %78 : tensor<64x64x!tt.ptr<f32>>
    tt.return
  }
}
