// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --add-llvm-debug-info --mlir-print-debuginfo %s | FileCheck %s

#loc = loc("/path/to/program.py":9:0)
// CHECK: #[[$ATTR_0:.+]] = loc("/path/to/program.py":9:0)
// CHECK-LABEL:   tt.func public @kernel(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/path/to/program.py":9:0),
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 loc("/path/to/program.py":9:0)) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<1.000000e+00> : tensor<2xf32> loc(#loc1)
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 2 : i32 loc(#loc1)
// CHECK:           %[[GET_PROGRAM_ID_0:.*]] = tt.get_program_id x : i32 loc(#loc2)
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[GET_PROGRAM_ID_0]], %[[CONSTANT_1]] : i32 loc(#loc3)
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 2 : i32, start = 0 : i32} : tensor<2xi32> loc(#loc4)
// CHECK:           %[[SPLAT_0:.*]] = tt.splat %[[MULI_0]] : i32 -> tensor<2xi32> loc(#loc5)
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[SPLAT_0]], %[[MAKE_RANGE_0]] : tensor<2xi32> loc(#loc5)
// CHECK:           %[[SPLAT_1:.*]] = tt.splat %[[ARG0]] : !tt.ptr<f32> -> tensor<2x!tt.ptr<f32>> loc(#loc6)
// CHECK:           %[[ADDPTR_0:.*]] = tt.addptr %[[SPLAT_1]], %[[ADDI_0]] : tensor<2x!tt.ptr<f32>>, tensor<2xi32> loc(#loc6)
// CHECK:           tt.store %[[ADDPTR_0]], %[[CONSTANT_0]] : tensor<2x!tt.ptr<f32>> loc(#loc7)
// CHECK:           tt.return loc(#loc8)
// CHECK:         } loc(#loc9)
module {
  tt.func public @kernel(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/path/to/program.py":9:0), %arg1: i32 loc("/path/to/program.py":9:0)) attributes {noinline = false} {
    %cst = arith.constant dense<1.000000e+00> : tensor<2xf32> loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %0 = tt.get_program_id x : i32 loc(#loc2)
    %1 = arith.muli %0, %c2_i32 : i32 loc(#loc3)
    %2 = tt.make_range {end = 2 : i32, start = 0 : i32} : tensor<2xi32> loc(#loc4)
    %3 = tt.splat %1 : i32 -> tensor<2xi32> loc(#loc5)
    %4 = arith.addi %3, %2 : tensor<2xi32> loc(#loc5)
    %5 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<2x!tt.ptr<f32>> loc(#loc6)
    %6 = tt.addptr %5, %4 : tensor<2x!tt.ptr<f32>>, tensor<2xi32> loc(#loc6)
    tt.store %6, %cst : tensor<2x!tt.ptr<f32>> loc(#loc7)
    tt.return loc(#loc8)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/path/to/program.py":10:24)
#loc3 = loc("/path/to/program.py":12:24)
#loc4 = loc("/path/to/program.py":13:41)
#loc5 = loc("/path/to/program.py":13:28)
#loc6 = loc("/path/to/program.py":25:26)
#loc7 = loc("/path/to/program.py":25:35)
#loc8 = loc("/path/to/program.py":25:4)
