// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt --triton-to-structured  --canonicalize  %s | FileCheck %s

// CHECK-LABEL:   tt.func public @gather_kernel(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<i64> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<i64> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<i64> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 512 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : i32
// CHECK:           %[[GET_PROGRAM_ID_0:.*]] = tt.get_program_id x : i32
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 512 : i32, start = 0 : i32} : tensor<512xi32>
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[GET_PROGRAM_ID_0]], %[[ARG6]] : i32
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[MULI_0]] : i32 to index
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[MULI_0]] : i32 to index
// CHECK:           %[[MAKE_TPTR_0:.*]] = tts.make_tptr %[[ARG1]] to sizes: [512], strides: [1], offsets: {{\[}}%[[INDEX_CAST_1]]], shape: [0], order: [] : <i64> to tensor<512x!tt.ptr<i64>>
// CHECK:           %[[SPLAT_0:.*]] = tt.splat %[[ARG3]] : i32 -> tensor<512xi32>
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[MAKE_RANGE_0]], %[[SPLAT_0]] : tensor<512xi32>
// CHECK:           %[[INDEX_CAST_2:.*]] = arith.index_cast %[[ARG3]] : i32 to index
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[INDEX_CAST_2]], %[[CONSTANT_1]] : index
// CHECK:           %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[VAL_0:.*]] = "tts.load"(%[[MAKE_TPTR_0]], %[[MAXSI_0]]) <{operandSegmentSizes = array<i32: 1, 1, 0>, static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<512x!tt.ptr<i64>>, index) -> tensor<512xi64>
// CHECK:           %[[CMPI_1:.*]] = arith.cmpi eq, %[[ARG4]], %[[CONSTANT_2]] : i32
// CHECK:           %[[IF_0:.*]] = scf.if %[[CMPI_1]] -> (tensor<512x!tt.ptr<i64>>) {
// CHECK:             %[[INDEX_CAST_3:.*]] = arith.index_cast %[[ARG5]] : i32 to index
// CHECK:             %[[INDEX_CAST_4:.*]] = arith.index_cast %[[INDEX_CAST_3]] : index to i64
// CHECK:             %[[SPLAT_1:.*]] = tt.splat %[[INDEX_CAST_4]] : i64 -> tensor<512xi64>
// CHECK:             %[[MULI_1:.*]] = arith.muli %[[VAL_0]], %[[SPLAT_1]] : tensor<512xi64>
// CHECK:             %[[MAKE_GATHER_SCATTER_TPTR_0:.*]] = tts.make_gather_scatter_tptr %[[ARG0]] to sizes: [512] gather_scatter_dim: 0 gather_scatter_offset: %[[MULI_1]], strides: [1], offsets: [0] : tensor<512xi64>  <i64> to tensor<512x!tt.ptr<i64>>
// CHECK:             scf.yield %[[MAKE_GATHER_SCATTER_TPTR_0]] : tensor<512x!tt.ptr<i64>>
// CHECK:           } else {
// CHECK:             %[[MULI_2:.*]] = arith.muli %[[GET_PROGRAM_ID_0]], %[[ARG5]] : i32
// CHECK:             %[[INDEX_CAST_5:.*]] = arith.index_cast %[[MULI_2]] : i32 to index
// CHECK:             %[[INDEX_CAST_6:.*]] = arith.index_cast %[[INDEX_CAST_5]] : index to i64
// CHECK:             %[[SPLAT_2:.*]] = tt.splat %[[INDEX_CAST_6]] : i64 -> tensor<512xi64>
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[SPLAT_2]], %[[VAL_0]] : tensor<512xi64>
// CHECK:             %[[MAKE_GATHER_SCATTER_TPTR_1:.*]] = tts.make_gather_scatter_tptr %[[ARG0]] to sizes: [512] gather_scatter_dim: 0 gather_scatter_offset: %[[ADDI_0]], strides: [1], offsets: [0] : tensor<512xi64>  <i64> to tensor<512x!tt.ptr<i64>>
// CHECK:             scf.yield %[[MAKE_GATHER_SCATTER_TPTR_1]] : tensor<512x!tt.ptr<i64>>
// CHECK:           }
// CHECK:           %[[LOAD_0:.*]] = tt.load %[[IF_0]], %[[CMPI_0]] : tensor<512x!tt.ptr<i64>>
// CHECK:           %[[MAKE_TPTR_1:.*]] = tts.make_tptr %[[ARG2]] to sizes: [512], strides: [1], offsets: {{\[}}%[[INDEX_CAST_0]]], shape: [0], order: [] : <i64> to tensor<512x!tt.ptr<i64>>
// CHECK:           %[[INDEX_CAST_7:.*]] = arith.index_cast %[[ARG3]] : i32 to index
// CHECK:           %[[MINSI_1:.*]] = arith.minsi %[[INDEX_CAST_7]], %[[CONSTANT_1]] : index
// CHECK:           %[[MAXSI_1:.*]] = arith.maxsi %[[MINSI_1]], %[[CONSTANT_0]] : index
// CHECK:           "tts.store"(%[[MAKE_TPTR_1]], %[[LOAD_0]], %[[MAXSI_1]]) <{static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<512x!tt.ptr<i64>>, tensor<512xi64>, index) -> ()
// CHECK:           tt.return
// CHECK:         }
module attributes {} {
  tt.func public @gather_kernel(%arg0: !tt.ptr<i64> { tt.divisibility = 16 : i32}, %arg1: !tt.ptr<i64> { tt.divisibility = 16 : i32}, %arg2: !tt.ptr<i64> { tt.divisibility = 16 : i32}, %arg3: i32 {tt.divisibility = 16 : i32}, %arg4: i32 {tt.divisibility = 16 : i32}, %arg5: i32 {tt.divisibility = 16 : i32}, %arg6: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %c0_i32 = arith.constant 0 : i32
    %0 = tt.get_program_id x : i32
    %1 = tt.make_range {end = 512 : i32, start = 0 : i32} : tensor<512xi32>
    %2 = arith.muli %0, %arg6 : i32
    %3 = tt.addptr %arg1, %2 : !tt.ptr<i64>, i32
    %4 = tt.splat %3 : !tt.ptr<i64> -> tensor<512x!tt.ptr<i64>>
    %5 = tt.addptr %4, %1 : tensor<512x!tt.ptr<i64>>, tensor<512xi32>
    %6 = tt.splat %arg3 : i32 -> tensor<512xi32>
    %7 = arith.cmpi slt, %1, %6 : tensor<512xi32>
    %8 = tt.load %5, %7 : tensor<512x!tt.ptr<i64>>
    %9 = arith.cmpi eq, %arg4, %c0_i32 : i32
    %10 = scf.if %9 -> (tensor<512x!tt.ptr<i64>>) {
      %15 = arith.extsi %arg5 : i32 to i64
      %16 = tt.splat %15 : i64 -> tensor<512xi64>
      %17 = arith.muli %8, %16 : tensor<512xi64>
      %18 = tt.splat %arg0 : !tt.ptr<i64> -> tensor<512x!tt.ptr<i64>>
      %19 = tt.addptr %18, %17 : tensor<512x!tt.ptr<i64>>, tensor<512xi64>
      %20 = tt.addptr %19, %1 : tensor<512x!tt.ptr<i64>>, tensor<512xi32>
      scf.yield %20 : tensor<512x!tt.ptr<i64>>
    } else {
      %15 = arith.muli %0, %arg5 : i32
      %16 = tt.addptr %arg0, %15 : !tt.ptr<i64>, i32
      %17 = tt.splat %16 : !tt.ptr<i64> -> tensor<512x!tt.ptr<i64>>
      %18 = tt.addptr %17, %8 : tensor<512x!tt.ptr<i64>>, tensor<512xi64>
      scf.yield %18 : tensor<512x!tt.ptr<i64>>
    }
    %11 = tt.load %10, %7 : tensor<512x!tt.ptr<i64>>
    %12 = tt.addptr %arg2, %2 : !tt.ptr<i64>, i32
    %13 = tt.splat %12 : !tt.ptr<i64> -> tensor<512x!tt.ptr<i64>>
    %14 = tt.addptr %13, %1 : tensor<512x!tt.ptr<i64>>, tensor<512xi32>
    tt.store %14, %11, %7 : tensor<512x!tt.ptr<i64>>
    tt.return
  }
}
