// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --triton-to-structured --remove-dead-values --canonicalize --cse %s | FileCheck %s

// Make sure tts.make_gather_scatter_tptr is generated with for 1D tensor on addptr with if.


// CHECK-LABEL:   tt.func public @gather_row(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<8> : tensor<4xi32>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 8 : i32
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant dense<4> : tensor<4xi32>
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
// CHECK:           %[[DIVSI_0:.*]] = arith.divsi %[[MAKE_RANGE_0]], %[[CONSTANT_2]] : tensor<4xi32>
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[ARG2]], %[[CONSTANT_1]] : i32
// CHECK:           %[[IF_0:.*]] = scf.if %[[CMPI_0]] -> (tensor<4xi32>) {
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[DIVSI_0]], %[[CONSTANT_0]] : tensor<4xi32>
// CHECK:             scf.yield %[[ADDI_0]] : tensor<4xi32>
// CHECK:           } else {
// CHECK:             scf.yield %[[DIVSI_0]] : tensor<4xi32>
// CHECK:           }
// CHECK:           %[[MAKE_GATHER_SCATTER_TPTR_0:.*]] = tts.make_gather_scatter_tptr %[[ARG0]] to sizes: [4] gather_scatter_dim: 0 gather_scatter_offset: %[[IF_0]], strides: [1], offsets: [0] : tensor<4xi32>  <f32> to tensor<4x!tt.ptr<f32>>
// CHECK:           %[[MAKE_GATHER_SCATTER_TPTR_1:.*]] = tts.make_gather_scatter_tptr %[[ARG1]] to sizes: [4] gather_scatter_dim: 0 gather_scatter_offset: %[[IF_0]], strides: [1], offsets: [0] : tensor<4xi32>  <f32> to tensor<4x!tt.ptr<f32>>
// CHECK:           %[[VAL_0:.*]] = "tts.load"(%[[MAKE_GATHER_SCATTER_TPTR_0]]) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<4x!tt.ptr<f32>>) -> tensor<4xf32>
// CHECK:           "tts.store"(%[[MAKE_GATHER_SCATTER_TPTR_1]], %[[VAL_0]]) <{static_mask_dims = array<i64>}> : (tensor<4x!tt.ptr<f32>>, tensor<4xf32>) -> ()
// CHECK:           tt.return
// CHECK:         }
module {
  tt.func public @gather_row(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: i32, %arg3: i32) attributes {noinline = false} {
    %cst = arith.constant dense<8> : tensor<4xi32>
    %c8_i32 = arith.constant 8 : i32
    %cst_0 = arith.constant dense<4> : tensor<4xi32>
    %0 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %1 = arith.divsi %0, %cst_0 : tensor<4xi32>
    %2 = arith.cmpi slt, %arg2, %c8_i32 : i32
    %3 = scf.if %2 -> (tensor<4xi32>) {
      %9 = arith.addi %1, %cst : tensor<4xi32>
      scf.yield %9 : tensor<4xi32>
    } else {
      scf.yield %1 : tensor<4xi32>
    }
    %4 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<4x!tt.ptr<f32>>
    %5 = tt.addptr %4, %3 : tensor<4x!tt.ptr<f32>>, tensor<4xi32>
    %6 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<4x!tt.ptr<f32>>
    %7 = tt.addptr %6, %3 : tensor<4x!tt.ptr<f32>>, tensor<4xi32>
    %8 = tt.load %5 : tensor<4x!tt.ptr<f32>>
    tt.store %7, %8 : tensor<4x!tt.ptr<f32>>
    tt.return
  }
}
