// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --triton-to-structured --canonicalize --cse %s | FileCheck %s

// Make sure tts.make_gather_scatter_tptr is generated with correct gather_dim stride and offset.


// CHECK-LABEL:   tt.func public @row_gather(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 8 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant dense<3> : tensor<8xi32>
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant dense<5> : tensor<8xi32>
// CHECK:           %[[MAKE_TPTR_0:.*]] = tts.make_tptr %[[ARG1]] to sizes: [8], strides: [1], offsets: [0], shape: [0], order: [] : <i32> to tensor<8x!tt.ptr<i32>>
// CHECK:           %[[VAL_0:.*]] = "tts.load"(%[[MAKE_TPTR_0]]) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<8x!tt.ptr<i32>>) -> tensor<8xi32>
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[VAL_0]], %[[CONSTANT_1]] : tensor<8xi32>
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[MULI_0]], %[[CONSTANT_2]] : tensor<8xi32>
// CHECK:           %[[MAKE_GATHER_SCATTER_TPTR_0:.*]] = tts.make_gather_scatter_tptr %[[ARG0]] to sizes: [8, 8] gather_scatter_dim: 0 gather_scatter_offset: %[[REMSI_0]], strides: {{\[}}%[[CONSTANT_0]], 1], offsets: [0, 0] : tensor<8xi32>  <f32> to tensor<8x8x!tt.ptr<f32>>
// CHECK:           %[[VAL_1:.*]] = "tts.load"(%[[MAKE_GATHER_SCATTER_TPTR_0]]) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<8x8x!tt.ptr<f32>>) -> tensor<8x8xf32>
// CHECK:           %[[MAKE_TPTR_1:.*]] = tts.make_tptr %[[ARG2]] to sizes: [8, 8], strides: {{\[}}%[[CONSTANT_0]], 1], offsets: [0, 0], shape: [0, 0], order: [] : <f32> to tensor<8x8x!tt.ptr<f32>>
// CHECK:           "tts.store"(%[[MAKE_TPTR_1]], %[[VAL_1]]) <{static_mask_dims = array<i64>}> : (tensor<8x8x!tt.ptr<f32>>, tensor<8x8xf32>) -> ()
// CHECK:           tt.return
// CHECK:         }
module {
  tt.func public @row_gather(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<i32>, %arg2: !tt.ptr<f32>) attributes {noinline = false} {
    %cst = arith.constant dense<8> : tensor<8x1xi32>
    %cst_0 = arith.constant dense<8> : tensor<8xi32>
    %cst_1 = arith.constant dense<3> : tensor<8xi32>
    %cst_2 = arith.constant dense<5> : tensor<8xi32>
    %0 = tt.make_range {end = 8 : i32, start = 0 : i32} : tensor<8xi32>
    %1 = tt.splat %arg1 : !tt.ptr<i32> -> tensor<8x!tt.ptr<i32>>
    %2 = tt.addptr %1, %0 : tensor<8x!tt.ptr<i32>>, tensor<8xi32>
    %3 = tt.load %2 : tensor<8x!tt.ptr<i32>>
    %4 = arith.muli %3, %cst_1 : tensor<8xi32>
    %5 = arith.remsi %4, %cst_2 : tensor<8xi32>
    %6 = tt.expand_dims %5 {axis = 1 : i32} : tensor<8xi32> -> tensor<8x1xi32>
    %7 = arith.muli %6, %cst : tensor<8x1xi32>
    %8 = tt.expand_dims %0 {axis = 0 : i32} : tensor<8xi32> -> tensor<1x8xi32>
    %9 = tt.broadcast %7 : tensor<8x1xi32> -> tensor<8x8xi32>
    %10 = tt.broadcast %8 : tensor<1x8xi32> -> tensor<8x8xi32>
    %11 = arith.addi %9, %10 : tensor<8x8xi32>
    %12 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<8x8x!tt.ptr<f32>>
    %13 = tt.addptr %12, %11 : tensor<8x8x!tt.ptr<f32>>, tensor<8x8xi32>
    %14 = tt.load %13 : tensor<8x8x!tt.ptr<f32>>
    %15 = tt.expand_dims %0 {axis = 1 : i32} : tensor<8xi32> -> tensor<8x1xi32>
    %16 = arith.muli %15, %cst : tensor<8x1xi32>
    %17 = tt.broadcast %16 : tensor<8x1xi32> -> tensor<8x8xi32>
    %18 = arith.addi %17, %10 : tensor<8x8xi32>
    %19 = tt.splat %arg2 : !tt.ptr<f32> -> tensor<8x8x!tt.ptr<f32>>
    %20 = tt.addptr %19, %18 : tensor<8x8x!tt.ptr<f32>>, tensor<8x8xi32>
    tt.store %20, %14 : tensor<8x8x!tt.ptr<f32>>
    tt.return
  }
}
