// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt --triton-to-structured --remove-dead-values --cse --canonicalize %s | FileCheck %s

// RUN: triton-shared-opt --triton-to-structured="enable-make-gather-scatter=false" --remove-dead-values --canonicalize %s | FileCheck %s --check-prefix=NO_GATHER

// Make sure no tts.make_gather_scatter_tptr generated when enable-make-gather-scatter=false.
// NO_GATHER-LABEL:   tt.func public @row_gather2(
// NO_GATHER-NOT:     tts.make_gather_scatter_tptr

// Make sure tts.make_gather_scatter_tptr is generated with correct gather_dim stride and offset.


// CHECK-LABEL:   tt.func public @row_gather2(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG10:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG11:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG12:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 16 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant dense<8> : tensor<16x1xi32>
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 8 : i32
// CHECK:           %[[GET_PROGRAM_ID_0:.*]] = tt.get_program_id z : i32
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[ARG5]], %[[CONSTANT_3]] : i32
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
// CHECK:           %[[EXPAND_DIMS_0:.*]] = tt.expand_dims %[[MAKE_RANGE_0]] {axis = 1 : i32} : tensor<16xi32> -> tensor<16x1xi32>
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[EXPAND_DIMS_0]], %[[CONSTANT_2]] : tensor<16x1xi32>
// CHECK:           %[[MULI_1:.*]] = arith.muli %[[ARG3]], %[[CONSTANT_3]] : i32
// CHECK:           %[[DIVSI_0:.*]] = arith.divsi %[[EXPAND_DIMS_0]], %[[CONSTANT_2]] : tensor<16x1xi32>
// CHECK:           %[[EXTSI_0:.*]] = arith.extsi %[[ARG2]] : i32 to i64
// CHECK:           %[[MULI_2:.*]] = arith.muli %[[EXTSI_0]], %[[ARG7]] : i64
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[MULI_2]] : i64 to index
// CHECK:           %[[SPLAT_0:.*]] = tt.splat %[[ARG4]] : i32 -> tensor<16x1xi32>
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[DIVSI_0]], %[[SPLAT_0]] : tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG6]] : i64 to index
// CHECK:           %[[SPLAT_1:.*]] = tt.splat %[[MULI_1]] : i32 -> tensor<16x1xi32>
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[SPLAT_1]] : tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_2:.*]] = arith.index_cast %[[ARG8]] : i64 to index
// CHECK:           %[[INDEX_CAST_3:.*]] = arith.index_cast %[[INDEX_CAST_1]] : index to i32
// CHECK:           %[[SPLAT_2:.*]] = tt.splat %[[INDEX_CAST_3]] : i32 -> tensor<16x1xi32>
// CHECK:           %[[MULI_3:.*]] = arith.muli %[[ADDI_0]], %[[SPLAT_2]] : tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_4:.*]] = arith.index_cast %[[INDEX_CAST_2]] : index to i32
// CHECK:           %[[SPLAT_3:.*]] = tt.splat %[[INDEX_CAST_4]] : i32 -> tensor<16x1xi32>
// CHECK:           %[[MULI_4:.*]] = arith.muli %[[ADDI_1]], %[[SPLAT_3]] : tensor<16x1xi32>
// CHECK:           %[[ADDI_2:.*]] = arith.addi %[[MULI_3]], %[[MULI_4]] : tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_5:.*]] = arith.index_cast %[[INDEX_CAST_0]] : index to i32
// CHECK:           %[[SPLAT_4:.*]] = tt.splat %[[INDEX_CAST_5]] : i32 -> tensor<16x1xi32>
// CHECK:           %[[ADDI_3:.*]] = arith.addi %[[SPLAT_4]], %[[ADDI_2]] : tensor<16x1xi32>
// CHECK:           %[[COLLAPSE_SHAPE_0:.*]] = tensor.collapse_shape %[[ADDI_3]] {{\[\[}}0, 1]] : tensor<16x1xi32> into tensor<16xi32>
// CHECK:           %[[MAKE_GATHER_SCATTER_TPTR_0:.*]] = tts.make_gather_scatter_tptr %[[ARG0]] to sizes: [16, 16] gather_scatter_dim: 0 gather_scatter_offset: %[[COLLAPSE_SHAPE_0]], strides: [1, 1], offsets: [0, 0] : tensor<16xi32>  <f32> to tensor<16x16x!tt.ptr<f32>>
// CHECK:           %[[INDEX_CAST_6:.*]] = arith.index_cast %[[MULI_0]] : i32 to index
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[INDEX_CAST_6]], %[[CONSTANT_1]] : index
// CHECK:           %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[MINSI_1:.*]] = arith.minsi %[[MAXSI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[VAL_0:.*]] = "tts.load"(%[[MAKE_GATHER_SCATTER_TPTR_0]], %[[MINSI_1]]) <{operandSegmentSizes = array<i32: 1, 1, 0>, static_mask_dims = array<i64: -9223372036854775808, 8>}> : (tensor<16x16x!tt.ptr<f32>>, index) -> tensor<16x16xf32>
// CHECK:           %[[MULI_5:.*]] = arith.muli %[[EXTSI_0]], %[[ARG10]] : i64
// CHECK:           %[[EXTSI_1:.*]] = arith.extsi %[[GET_PROGRAM_ID_0]] : i32 to i64
// CHECK:           %[[MULI_6:.*]] = arith.muli %[[EXTSI_1]], %[[ARG12]] : i64
// CHECK:           %[[ADDI_4:.*]] = arith.addi %[[MULI_5]], %[[MULI_6]] : i64
// CHECK:           %[[INDEX_CAST_7:.*]] = arith.index_cast %[[ADDI_4]] : i64 to index
// CHECK:           %[[INDEX_CAST_8:.*]] = arith.index_cast %[[ARG9]] : i64 to index
// CHECK:           %[[INDEX_CAST_9:.*]] = arith.index_cast %[[ARG11]] : i64 to index
// CHECK:           %[[INDEX_CAST_10:.*]] = arith.index_cast %[[INDEX_CAST_8]] : index to i32
// CHECK:           %[[SPLAT_5:.*]] = tt.splat %[[INDEX_CAST_10]] : i32 -> tensor<16x1xi32>
// CHECK:           %[[MULI_7:.*]] = arith.muli %[[ADDI_0]], %[[SPLAT_5]] : tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_11:.*]] = arith.index_cast %[[INDEX_CAST_9]] : index to i32
// CHECK:           %[[SPLAT_6:.*]] = tt.splat %[[INDEX_CAST_11]] : i32 -> tensor<16x1xi32>
// CHECK:           %[[MULI_8:.*]] = arith.muli %[[ADDI_1]], %[[SPLAT_6]] : tensor<16x1xi32>
// CHECK:           %[[ADDI_5:.*]] = arith.addi %[[MULI_7]], %[[MULI_8]] : tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_12:.*]] = arith.index_cast %[[INDEX_CAST_7]] : index to i32
// CHECK:           %[[SPLAT_7:.*]] = tt.splat %[[INDEX_CAST_12]] : i32 -> tensor<16x1xi32>
// CHECK:           %[[ADDI_6:.*]] = arith.addi %[[SPLAT_7]], %[[ADDI_5]] : tensor<16x1xi32>
// CHECK:           %[[COLLAPSE_SHAPE_1:.*]] = tensor.collapse_shape %[[ADDI_6]] {{\[\[}}0, 1]] : tensor<16x1xi32> into tensor<16xi32>
// CHECK:           %[[MAKE_GATHER_SCATTER_TPTR_1:.*]] = tts.make_gather_scatter_tptr %[[ARG1]] to sizes: [16, 16] gather_scatter_dim: 0 gather_scatter_offset: %[[COLLAPSE_SHAPE_1]], strides: [1, 1], offsets: [0, 0] : tensor<16xi32>  <f32> to tensor<16x16x!tt.ptr<f32>>
// CHECK:           "tts.store"(%[[MAKE_GATHER_SCATTER_TPTR_1]], %[[VAL_0]], %[[MINSI_1]]) <{static_mask_dims = array<i64: -9223372036854775808, 8>}> : (tensor<16x16x!tt.ptr<f32>>, tensor<16x16xf32>, index) -> ()
// CHECK:           tt.return
// CHECK:         }
module {
  tt.func public @row_gather2(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: i32, %arg3: i32, %arg4: i32, %arg5: i32, %arg6: i64, %arg7: i64, %arg8: i64, %arg9: i64, %arg10: i64, %arg11: i64, %arg12: i64) attributes {noinline = false} {
    %cst = arith.constant dense<8> : tensor<1x16xi32>
    %cst_0 = arith.constant dense<8> : tensor<16x1xi32>
    %c8_i32 = arith.constant 8 : i32
    %0 = tt.get_program_id z : i32
    %1 = arith.muli %arg5, %c8_i32 : i32
    %2 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
    %3 = tt.expand_dims %2 {axis = 1 : i32} : tensor<16xi32> -> tensor<16x1xi32>
    %4 = arith.remsi %3, %cst_0 : tensor<16x1xi32>
    %5 = arith.muli %arg3, %c8_i32 : i32
    %6 = tt.splat %5 : i32 -> tensor<16x1xi32>
    %7 = arith.addi %4, %6 : tensor<16x1xi32>
    %8 = arith.divsi %3, %cst_0 : tensor<16x1xi32>
    %9 = tt.splat %arg4 : i32 -> tensor<16x1xi32>
    %10 = arith.addi %8, %9 : tensor<16x1xi32>
    %11 = arith.extsi %arg2 : i32 to i64
    %12 = arith.muli %11, %arg7 : i64
    %13 = tt.addptr %arg0, %12 : !tt.ptr<f32>, i64
    %14 = arith.extsi %10 : tensor<16x1xi32> to tensor<16x1xi64>
    %15 = tt.splat %arg6 : i64 -> tensor<16x1xi64>
    %16 = arith.muli %14, %15 : tensor<16x1xi64>
    %17 = tt.splat %13 : !tt.ptr<f32> -> tensor<16x1x!tt.ptr<f32>>
    %18 = arith.extsi %7 : tensor<16x1xi32> to tensor<16x1xi64>
    %19 = tt.splat %arg8 : i64 -> tensor<16x1xi64>
    %20 = arith.muli %18, %19 : tensor<16x1xi64>
    %21 = arith.addi %16, %20 : tensor<16x1xi64>
    %22 = tt.addptr %17, %21 : tensor<16x1x!tt.ptr<f32>>, tensor<16x1xi64>
    %23 = tt.expand_dims %2 {axis = 0 : i32} : tensor<16xi32> -> tensor<1x16xi32>
    %24 = tt.broadcast %22 : tensor<16x1x!tt.ptr<f32>> -> tensor<16x16x!tt.ptr<f32>>
    %25 = tt.broadcast %23 : tensor<1x16xi32> -> tensor<16x16xi32>
    %26 = tt.addptr %24, %25 : tensor<16x16x!tt.ptr<f32>>, tensor<16x16xi32>
    %27 = arith.cmpi slt, %23, %cst : tensor<1x16xi32>
    %28 = tt.splat %1 : i32 -> tensor<16x1xi32>
    %29 = arith.cmpi slt, %3, %28 : tensor<16x1xi32>
    %30 = tt.broadcast %27 : tensor<1x16xi1> -> tensor<16x16xi1>
    %31 = tt.broadcast %29 : tensor<16x1xi1> -> tensor<16x16xi1>
    %32 = arith.andi %30, %31 : tensor<16x16xi1>
    %33 = tt.load %26, %32 : tensor<16x16x!tt.ptr<f32>>
    %34 = arith.muli %11, %arg10 : i64
    %35 = arith.extsi %0 : i32 to i64
    %36 = arith.muli %35, %arg12 : i64
    %37 = arith.addi %34, %36 : i64
    %38 = tt.addptr %arg1, %37 : !tt.ptr<f32>, i64
    %39 = tt.splat %arg9 : i64 -> tensor<16x1xi64>
    %40 = arith.muli %14, %39 : tensor<16x1xi64>
    %41 = tt.splat %38 : !tt.ptr<f32> -> tensor<16x1x!tt.ptr<f32>>
    %42 = tt.splat %arg11 : i64 -> tensor<16x1xi64>
    %43 = arith.muli %18, %42 : tensor<16x1xi64>
    %44 = arith.addi %40, %43 : tensor<16x1xi64>
    %45 = tt.addptr %41, %44 : tensor<16x1x!tt.ptr<f32>>, tensor<16x1xi64>
    %46 = tt.broadcast %45 : tensor<16x1x!tt.ptr<f32>> -> tensor<16x16x!tt.ptr<f32>>
    %47 = tt.addptr %46, %25 : tensor<16x16x!tt.ptr<f32>>, tensor<16x16xi32>
    tt.store %47, %33, %32 : tensor<16x16x!tt.ptr<f32>>
    tt.return
  }
}
