// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --triton-to-structured --remove-dead-values --cse --canonicalize %s | FileCheck %s

// Make sure tts.make_gather_scatter_tptr was generated correctly.


// CHECK-LABEL:   tt.func public @index_select_row_with_double_mod_kernel2(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<i32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<1> : tensor<4x1xi32>
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
// CHECK:           %[[MAKE_TPTR_0:.*]] = tts.make_tptr %[[ARG2]] to sizes: [4], strides: [1], offsets: [0], shape: [0], order: [] : <i32> to tensor<4x!tt.ptr<i32>>
// CHECK:           %[[VAL_0:.*]] = "tts.load"(%[[MAKE_TPTR_0]]) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<4x!tt.ptr<i32>>) -> tensor<4xi32>
// CHECK:           %[[EXPAND_DIMS_0:.*]] = tt.expand_dims %[[MAKE_RANGE_0]] {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
// CHECK:           %[[SPLAT_0:.*]] = tt.splat %[[ARG5]] : i32 -> tensor<4x1xi32>
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[EXPAND_DIMS_0]], %[[SPLAT_0]] : tensor<4x1xi32>
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_0]] : tensor<4x1xi32>
// CHECK:           %[[RESHAPE_0:.*]] = tt.reshape %[[ADDI_0]] allow_reorder : tensor<4x1xi32> -> tensor<4xi32>
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[VAL_0]], %[[RESHAPE_0]] : tensor<4xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG3]] : i32 to index
// CHECK:           %[[MAKE_GATHER_SCATTER_TPTR_0:.*]] = tts.make_gather_scatter_tptr %[[ARG0]] to sizes: [4, 16] gather_scatter_dim: 0 gather_scatter_offset: %[[ADDI_1]], strides: {{\[}}%[[INDEX_CAST_0]], 1], offsets: [0, 0] : tensor<4xi32>  <f32> to tensor<4x16x!tt.ptr<f32>>
// CHECK:           %[[VAL_1:.*]] = "tts.load"(%[[MAKE_GATHER_SCATTER_TPTR_0]]) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<4x16x!tt.ptr<f32>>) -> tensor<4x16xf32>
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG4]] : i32 to index
// CHECK:           %[[MAKE_TPTR_1:.*]] = tts.make_tptr %[[ARG1]] to sizes: [4, 16], strides: {{\[}}%[[INDEX_CAST_1]], 1], offsets: [0, 0], shape: [0, 0], order: [] : <f32> to tensor<4x16x!tt.ptr<f32>>
// CHECK:           "tts.store"(%[[MAKE_TPTR_1]], %[[VAL_1]]) <{static_mask_dims = array<i64>}> : (tensor<4x16x!tt.ptr<f32>>, tensor<4x16xf32>) -> ()
// CHECK:           tt.return
// CHECK:         }
module {
  tt.func public @index_select_row_with_double_mod_kernel2(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg2: !tt.ptr<i32> {tt.divisibility = 16 : i32}, %arg3: i32 {tt.divisibility = 16 : i32}, %arg4: i32 {tt.divisibility = 16 : i32}, %arg5: i32) attributes {noinline = false} {
    %cst = arith.constant dense<1> : tensor<4x1xi32>
    %0 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %1 = tt.splat %arg2 : !tt.ptr<i32> -> tensor<4x!tt.ptr<i32>>
    %2 = tt.addptr %1, %0 : tensor<4x!tt.ptr<i32>>, tensor<4xi32>
    %3 = tt.load %2 : tensor<4x!tt.ptr<i32>>
    %4 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
    %5 = tt.expand_dims %3 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
    %6 = tt.expand_dims %0 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
    %7 = tt.splat %arg5 : i32 -> tensor<4x1xi32>
    %8 = arith.remsi %6, %7 : tensor<4x1xi32>
    %9 = arith.addi %8, %cst : tensor<4x1xi32>
    %10 = arith.addi %5, %9 : tensor<4x1xi32>
    %11 = tt.splat %arg3 : i32 -> tensor<4x1xi32>
    %12 = arith.muli %10, %11 : tensor<4x1xi32>
    %13 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<4x1x!tt.ptr<f32>>
    %14 = tt.addptr %13, %12 : tensor<4x1x!tt.ptr<f32>>, tensor<4x1xi32>
    %15 = tt.expand_dims %4 {axis = 0 : i32} : tensor<16xi32> -> tensor<1x16xi32>
    %16 = tt.broadcast %14 : tensor<4x1x!tt.ptr<f32>> -> tensor<4x16x!tt.ptr<f32>>
    %17 = tt.broadcast %15 : tensor<1x16xi32> -> tensor<4x16xi32>
    %18 = tt.addptr %16, %17 : tensor<4x16x!tt.ptr<f32>>, tensor<4x16xi32>
    %19 = tt.load %18 : tensor<4x16x!tt.ptr<f32>>
    %20 = tt.splat %arg4 : i32 -> tensor<4x1xi32>
    %21 = arith.muli %6, %20 : tensor<4x1xi32>
    %22 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<4x1x!tt.ptr<f32>>
    %23 = tt.addptr %22, %21 : tensor<4x1x!tt.ptr<f32>>, tensor<4x1xi32>
    %24 = tt.broadcast %23 : tensor<4x1x!tt.ptr<f32>> -> tensor<4x16x!tt.ptr<f32>>
    %25 = tt.addptr %24, %17 : tensor<4x16x!tt.ptr<f32>>, tensor<4x16xi32>
    tt.store %25, %19 : tensor<4x16x!tt.ptr<f32>>
    tt.return
  }
}
