// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt --triton-to-structured --canonicalize %s | FileCheck %s

module {
// CHECK-LABEL:   tt.func public @_layer_norm_fwd_fused_0123456789(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: f32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 256 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant dense<0.000000e+00> : tensor<256xf32>
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 256 : i32
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 1.000000e+00 : f32
// CHECK:           %[[GET_PROGRAM_ID_0:.*]] = tt.get_program_id x : i32
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[GET_PROGRAM_ID_0]], %[[ARG6]] : i32
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[MULI_0]] : i32 to index
// CHECK:           %[[FOR_0:.*]] = scf.for %[[VAL_0:.*]] = %[[CONSTANT_4]] to %[[ARG7]] step %[[CONSTANT_3]] iter_args(%[[VAL_1:.*]] = %[[CONSTANT_2]]) -> (tensor<256xf32>)  : i32 {
// CHECK:             %[[INDEX_CAST_1:.*]] = arith.index_cast %[[VAL_0]] : i32 to index
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[INDEX_CAST_1]] : index
// CHECK:             %[[MAKE_TPTR_0:.*]] = tts.make_tptr %[[ARG0]] to sizes: [256], strides: [1], offsets: {{\[}}%[[ADDI_0]]], shape: [0], order: [] : <f32> to tensor<256x!tt.ptr<f32>>
// CHECK:             %[[ADDI_1:.*]] = arith.addi %[[INDEX_CAST_1]], %[[CONSTANT_1]] : index
// CHECK:             %[[INDEX_CAST_2:.*]] = arith.index_cast %[[ARG7]] : i32 to index
// CHECK:             %[[MINSI_0:.*]] = arith.minsi %[[ADDI_1]], %[[INDEX_CAST_2]] : index
// CHECK:             %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_0]], %[[INDEX_CAST_1]] : index
// CHECK:             %[[SUBI_0:.*]] = arith.subi %[[MAXSI_0]], %[[INDEX_CAST_1]] : index
// CHECK:             %[[VAL_2:.*]] = "tts.load"(%[[MAKE_TPTR_0]], %[[SUBI_0]], %[[CONSTANT_0]]) <{operandSegmentSizes = array<i32: 1, 1, 1>, static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<256x!tt.ptr<f32>>, index, f32) -> tensor<256xf32>
// CHECK:             %[[ADDF_0:.*]] = arith.addf %[[VAL_1]], %[[VAL_2]] : tensor<256xf32>
// CHECK:             scf.yield %[[ADDF_0]] : tensor<256xf32>
// CHECK:           }
// CHECK:           %[[VAL_3:.*]] = "tt.reduce"(%[[FOR_0]]) <{axis = 0 : i32}> ({
// CHECK:           ^bb0(%[[VAL_4:.*]]: f32, %[[VAL_5:.*]]: f32):
// CHECK:             %[[ADDF_1:.*]] = arith.addf %[[VAL_4]], %[[VAL_5]] : f32
// CHECK:             tt.reduce.return %[[ADDF_1]] : f32
// CHECK:           }) : (tensor<256xf32>) -> f32
// CHECK:           %[[SITOFP_0:.*]] = arith.sitofp %[[ARG7]] : i32 to f32
// CHECK:           %[[DIVF_0:.*]] = arith.divf %[[VAL_3]], %[[SITOFP_0]] : f32
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 256 : i32, start = 0 : i32} : tensor<256xi32>
// CHECK:           %[[SPLAT_0:.*]] = tt.splat %[[ARG7]] : i32 -> tensor<256xi32>
// CHECK:           %[[SPLAT_1:.*]] = tt.splat %[[DIVF_0]] : f32 -> tensor<256xf32>
// CHECK:           %[[FOR_1:.*]] = scf.for %[[VAL_6:.*]] = %[[CONSTANT_4]] to %[[ARG7]] step %[[CONSTANT_3]] iter_args(%[[VAL_7:.*]] = %[[CONSTANT_2]]) -> (tensor<256xf32>)  : i32 {
// CHECK:             %[[SPLAT_2:.*]] = tt.splat %[[VAL_6]] : i32 -> tensor<256xi32>
// CHECK:             %[[ADDI_2:.*]] = arith.addi %[[SPLAT_2]], %[[MAKE_RANGE_0]] : tensor<256xi32>
// CHECK:             %[[CMPI_0:.*]] = arith.cmpi slt, %[[ADDI_2]], %[[SPLAT_0]] : tensor<256xi32>
// CHECK:             %[[INDEX_CAST_3:.*]] = arith.index_cast %[[VAL_6]] : i32 to index
// CHECK:             %[[ADDI_3:.*]] = arith.addi %[[INDEX_CAST_0]], %[[INDEX_CAST_3]] : index
// CHECK:             %[[MAKE_TPTR_1:.*]] = tts.make_tptr %[[ARG0]] to sizes: [256], strides: [1], offsets: {{\[}}%[[ADDI_3]]], shape: [0], order: [] : <f32> to tensor<256x!tt.ptr<f32>>
// CHECK:             %[[ADDI_4:.*]] = arith.addi %[[INDEX_CAST_3]], %[[CONSTANT_1]] : index
// CHECK:             %[[INDEX_CAST_4:.*]] = arith.index_cast %[[ARG7]] : i32 to index
// CHECK:             %[[MINSI_1:.*]] = arith.minsi %[[ADDI_4]], %[[INDEX_CAST_4]] : index
// CHECK:             %[[MAXSI_1:.*]] = arith.maxsi %[[MINSI_1]], %[[INDEX_CAST_3]] : index
// CHECK:             %[[SUBI_1:.*]] = arith.subi %[[MAXSI_1]], %[[INDEX_CAST_3]] : index
// CHECK:             %[[VAL_8:.*]] = "tts.load"(%[[MAKE_TPTR_1]], %[[SUBI_1]], %[[CONSTANT_0]]) <{operandSegmentSizes = array<i32: 1, 1, 1>, static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<256x!tt.ptr<f32>>, index, f32) -> tensor<256xf32>
// CHECK:             %[[SUBF_0:.*]] = arith.subf %[[VAL_8]], %[[SPLAT_1]] : tensor<256xf32>
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[SUBF_0]], %[[CONSTANT_2]] : tensor<256xi1>, tensor<256xf32>
// CHECK:             %[[MULF_0:.*]] = arith.mulf %[[SELECT_0]], %[[SELECT_0]] : tensor<256xf32>
// CHECK:             %[[ADDF_2:.*]] = arith.addf %[[VAL_7]], %[[MULF_0]] : tensor<256xf32>
// CHECK:             scf.yield %[[ADDF_2]] : tensor<256xf32>
// CHECK:           }
// CHECK:           %[[VAL_9:.*]] = "tt.reduce"(%[[FOR_1]]) <{axis = 0 : i32}> ({
// CHECK:           ^bb0(%[[VAL_10:.*]]: f32, %[[VAL_11:.*]]: f32):
// CHECK:             %[[ADDF_3:.*]] = arith.addf %[[VAL_10]], %[[VAL_11]] : f32
// CHECK:             tt.reduce.return %[[ADDF_3]] : f32
// CHECK:           }) : (tensor<256xf32>) -> f32
// CHECK:           %[[DIVF_1:.*]] = arith.divf %[[VAL_9]], %[[SITOFP_0]] : f32
// CHECK:           %[[ADDF_4:.*]] = arith.addf %[[DIVF_1]], %[[ARG8]] : f32
// CHECK:           %[[SQRT_0:.*]] = math.sqrt %[[ADDF_4]] : f32
// CHECK:           %[[DIVF_2:.*]] = arith.divf %[[CONSTANT_5]], %[[SQRT_0]] : f32
// CHECK:           %[[ADDPTR_0:.*]] = tt.addptr %[[ARG4]], %[[GET_PROGRAM_ID_0]] : !tt.ptr<f32>, i32
// CHECK:           tt.store %[[ADDPTR_0]], %[[DIVF_0]] : !tt.ptr<f32>
// CHECK:           %[[ADDPTR_1:.*]] = tt.addptr %[[ARG5]], %[[GET_PROGRAM_ID_0]] : !tt.ptr<f32>, i32
// CHECK:           tt.store %[[ADDPTR_1]], %[[DIVF_2]] : !tt.ptr<f32>
// CHECK:           %[[SPLAT_3:.*]] = tt.splat %[[DIVF_2]] : f32 -> tensor<256xf32>
// CHECK:           scf.for %[[VAL_12:.*]] = %[[CONSTANT_4]] to %[[ARG7]] step %[[CONSTANT_3]]  : i32 {
// CHECK:             %[[INDEX_CAST_5:.*]] = arith.index_cast %[[VAL_12]] : i32 to index
// CHECK:             %[[MAKE_TPTR_2:.*]] = tts.make_tptr %[[ARG2]] to sizes: [256], strides: [1], offsets: {{\[}}%[[INDEX_CAST_5]]], shape: [0], order: [] : <f32> to tensor<256x!tt.ptr<f32>>
// CHECK:             %[[ADDI_5:.*]] = arith.addi %[[INDEX_CAST_5]], %[[CONSTANT_1]] : index
// CHECK:             %[[INDEX_CAST_6:.*]] = arith.index_cast %[[ARG7]] : i32 to index
// CHECK:             %[[MINSI_2:.*]] = arith.minsi %[[ADDI_5]], %[[INDEX_CAST_6]] : index
// CHECK:             %[[MAXSI_2:.*]] = arith.maxsi %[[MINSI_2]], %[[INDEX_CAST_5]] : index
// CHECK:             %[[SUBI_2:.*]] = arith.subi %[[MAXSI_2]], %[[INDEX_CAST_5]] : index
// CHECK:             %[[VAL_13:.*]] = "tts.load"(%[[MAKE_TPTR_2]], %[[SUBI_2]]) <{operandSegmentSizes = array<i32: 1, 1, 0>, static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<256x!tt.ptr<f32>>, index) -> tensor<256xf32>
// CHECK:             %[[MAKE_TPTR_3:.*]] = tts.make_tptr %[[ARG3]] to sizes: [256], strides: [1], offsets: {{\[}}%[[INDEX_CAST_5]]], shape: [0], order: [] : <f32> to tensor<256x!tt.ptr<f32>>
// CHECK:             %[[VAL_14:.*]] = "tts.load"(%[[MAKE_TPTR_3]], %[[SUBI_2]]) <{operandSegmentSizes = array<i32: 1, 1, 0>, static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<256x!tt.ptr<f32>>, index) -> tensor<256xf32>
// CHECK:             %[[ADDI_6:.*]] = arith.addi %[[INDEX_CAST_0]], %[[INDEX_CAST_5]] : index
// CHECK:             %[[MAKE_TPTR_4:.*]] = tts.make_tptr %[[ARG0]] to sizes: [256], strides: [1], offsets: {{\[}}%[[ADDI_6]]], shape: [0], order: [] : <f32> to tensor<256x!tt.ptr<f32>>
// CHECK:             %[[VAL_15:.*]] = "tts.load"(%[[MAKE_TPTR_4]], %[[SUBI_2]], %[[CONSTANT_0]]) <{operandSegmentSizes = array<i32: 1, 1, 1>, static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<256x!tt.ptr<f32>>, index, f32) -> tensor<256xf32>
// CHECK:             %[[SUBF_1:.*]] = arith.subf %[[VAL_15]], %[[SPLAT_1]] : tensor<256xf32>
// CHECK:             %[[MULF_1:.*]] = arith.mulf %[[SUBF_1]], %[[SPLAT_3]] : tensor<256xf32>
// CHECK:             %[[MULF_2:.*]] = arith.mulf %[[MULF_1]], %[[VAL_13]] : tensor<256xf32>
// CHECK:             %[[ADDF_5:.*]] = arith.addf %[[MULF_2]], %[[VAL_14]] : tensor<256xf32>
// CHECK:             %[[MAKE_TPTR_5:.*]] = tts.make_tptr %[[ARG1]] to sizes: [256], strides: [1], offsets: {{\[}}%[[ADDI_6]]], shape: [0], order: [] : <f32> to tensor<256x!tt.ptr<f32>>
// CHECK:             "tts.store"(%[[MAKE_TPTR_5]], %[[ADDF_5]], %[[SUBI_2]]) <{static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<256x!tt.ptr<f32>>, tensor<256xf32>, index) -> ()
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func public @_layer_norm_fwd_fused_0123456789(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: !tt.ptr<f32>, %arg3: !tt.ptr<f32>, %arg4: !tt.ptr<f32>, %arg5: !tt.ptr<f32>, %arg6: i32, %arg7: i32, %arg8: f32) {
    %c256_i32 = arith.constant 256 : i32
    %c0_i32 = arith.constant 0 : i32
    %cst = arith.constant 1.000000e+00 : f32
    %cst_0 = arith.constant 0.000000e+00 : f32
    %0 = tt.get_program_id x : i32
    %1 = arith.muli %0, %arg6 : i32
    %2 = tt.addptr %arg1, %1 : !tt.ptr<f32>, i32
    %3 = tt.addptr %arg0, %1 : !tt.ptr<f32>, i32
    %4 = tt.splat %cst_0 : f32 -> tensor<256xf32>
    %5 = tt.make_range {end = 256 : i32, start = 0 : i32} : tensor<256xi32>
    %6 = tt.splat %arg7 : i32 -> tensor<256xi32>
    %7 = tt.splat %3 : !tt.ptr<f32> -> tensor<256x!tt.ptr<f32>>
    %8 = scf.for %arg9 = %c0_i32 to %arg7 step %c256_i32 iter_args(%arg10 = %4) -> (tensor<256xf32>)  : i32 {
      %32 = tt.splat %arg9 : i32 -> tensor<256xi32>
      %33 = arith.addi %32, %5 : tensor<256xi32>
      %34 = arith.cmpi slt, %33, %6 : tensor<256xi32>
      %35 = tt.addptr %7, %33 : tensor<256x!tt.ptr<f32>>, tensor<256xi32>
      %36 = tt.load %35, %34, %4 : tensor<256x!tt.ptr<f32>>
      %37 = arith.addf %arg10, %36 : tensor<256xf32>
      scf.yield %37 : tensor<256xf32>
    }
    %9 = "tt.reduce"(%8) ({
    ^bb0(%arg9: f32, %arg10: f32):
      %32 = arith.addf %arg9, %arg10 : f32
      tt.reduce.return %32 : f32
    }) {axis = 0 : i32} : (tensor<256xf32>) -> f32
    %10 = arith.sitofp %arg7 : i32 to f32
    %11 = arith.divf %9, %10 : f32
    %12 = tt.make_range {end = 256 : i32, start = 0 : i32} : tensor<256xi32>
    %13 = tt.splat %arg7 : i32 -> tensor<256xi32>
    %14 = tt.splat %3 : !tt.ptr<f32> -> tensor<256x!tt.ptr<f32>>
    %15 = tt.splat %11 : f32 -> tensor<256xf32>
    %16 = scf.for %arg9 = %c0_i32 to %arg7 step %c256_i32 iter_args(%arg10 = %4) -> (tensor<256xf32>)  : i32 {
      %32 = tt.splat %arg9 : i32 -> tensor<256xi32>
      %33 = arith.addi %32, %12 : tensor<256xi32>
      %34 = arith.cmpi slt, %33, %13 : tensor<256xi32>
      %35 = tt.addptr %14, %33 : tensor<256x!tt.ptr<f32>>, tensor<256xi32>
      %36 = tt.load %35, %34, %4 : tensor<256x!tt.ptr<f32>>
      %37 = arith.subf %36, %15 : tensor<256xf32>
      %38 = arith.select %34, %37, %4 : tensor<256xi1>, tensor<256xf32>
      %39 = arith.mulf %38, %38 : tensor<256xf32>
      %40 = arith.addf %arg10, %39 : tensor<256xf32>
      scf.yield %40 : tensor<256xf32>
    }
    %17 = "tt.reduce"(%16) ({
    ^bb0(%arg9: f32, %arg10: f32):
      %32 = arith.addf %arg9, %arg10 : f32
      tt.reduce.return %32 : f32
    }) {axis = 0 : i32} : (tensor<256xf32>) -> f32
    %18 = arith.divf %17, %10 : f32
    %19 = arith.addf %18, %arg8 : f32
    %20 = math.sqrt %19 : f32
    %21 = arith.divf %cst, %20 : f32
    %22 = tt.addptr %arg4, %0 : !tt.ptr<f32>, i32
    tt.store %22, %11 : !tt.ptr<f32>
    %23 = tt.addptr %arg5, %0 : !tt.ptr<f32>, i32
    tt.store %23, %21 : !tt.ptr<f32>
    %24 = tt.make_range {end = 256 : i32, start = 0 : i32} : tensor<256xi32>
    %25 = tt.splat %arg7 : i32 -> tensor<256xi32>
    %26 = tt.splat %arg2 : !tt.ptr<f32> -> tensor<256x!tt.ptr<f32>>
    %27 = tt.splat %arg3 : !tt.ptr<f32> -> tensor<256x!tt.ptr<f32>>
    %28 = tt.splat %3 : !tt.ptr<f32> -> tensor<256x!tt.ptr<f32>>
    %29 = tt.splat %11 : f32 -> tensor<256xf32>
    %30 = tt.splat %21 : f32 -> tensor<256xf32>
    %31 = tt.splat %2 : !tt.ptr<f32> -> tensor<256x!tt.ptr<f32>>
    scf.for %arg9 = %c0_i32 to %arg7 step %c256_i32  : i32 {
      %32 = tt.splat %arg9 : i32 -> tensor<256xi32>
      %33 = arith.addi %32, %24 : tensor<256xi32>
      %34 = arith.cmpi slt, %33, %25 : tensor<256xi32>
      %35 = tt.addptr %26, %33 : tensor<256x!tt.ptr<f32>>, tensor<256xi32>
      %36 = tt.load %35, %34 : tensor<256x!tt.ptr<f32>>
      %37 = tt.addptr %27, %33 : tensor<256x!tt.ptr<f32>>, tensor<256xi32>
      %38 = tt.load %37, %34 : tensor<256x!tt.ptr<f32>>
      %39 = tt.addptr %28, %33 : tensor<256x!tt.ptr<f32>>, tensor<256xi32>
      %40 = tt.load %39, %34, %4 : tensor<256x!tt.ptr<f32>>
      %41 = arith.subf %40, %29 : tensor<256xf32>
      %42 = arith.mulf %41, %30 : tensor<256xf32>
      %43 = arith.mulf %42, %36 : tensor<256xf32>
      %44 = arith.addf %43, %38 : tensor<256xf32>
      %45 = tt.addptr %31, %33 : tensor<256x!tt.ptr<f32>>, tensor<256xi32>
      tt.store %45, %44, %34 : tensor<256x!tt.ptr<f32>>
    }
    tt.return
  }
}
