// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt --triton-to-structured --canonicalize %s | FileCheck %s

module {
// CHECK-LABEL:   tt.func public @_layer_norm_bwd_dwdb_0123456(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 256 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant dense<0.000000e+00> : tensor<256x256xf32>
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 256 : i32
// CHECK:           %[[GET_PROGRAM_ID_0:.*]] = tt.get_program_id x : i32
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[GET_PROGRAM_ID_0]], %[[CONSTANT_4]] : i32
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[MULI_0]] : i32 to index
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_3]] to %[[ARG4]] step %[[CONSTANT_4]] iter_args(%[[VAL_1:.*]] = %[[CONSTANT_2]], %[[VAL_2:.*]] = %[[CONSTANT_2]]) -> (tensor<256x256xf32>, tensor<256x256xf32>)  : i32 {
// CHECK:             %[[INDEX_CAST_1:.*]] = arith.index_cast %[[VAL_0]] : i32 to index
// CHECK:             %[[INDEX_CAST_2:.*]] = arith.index_cast %[[ARG5]] : i32 to index
// CHECK:             %[[MULI_1:.*]] = arith.muli %[[INDEX_CAST_1]], %[[INDEX_CAST_2]] : index
// CHECK:             %[[MAKE_TPTR_0:.*]] = tts.make_tptr %[[ARG0]] to sizes: [256, 256], strides: {{\[}}%[[INDEX_CAST_2]], 1], offsets: {{\[}}%[[MULI_1]], %[[INDEX_CAST_0]]], shape: [0, 0], order: [] : <f32> to tensor<256x256x!tt.ptr<f32>>
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_1]], %[[CONSTANT_1]] : index
// CHECK:             %[[INDEX_CAST_3:.*]] = arith.index_cast %[[ARG4]] : i32 to index
// CHECK:             %[[MINSI_0:.*]] = arith.minsi %[[ADDI_0]], %[[INDEX_CAST_3]] : index
// CHECK:             %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_0]], %[[INDEX_CAST_1]] : index
// CHECK:             %[[SUBI_0:.*]] = arith.subi %[[MAXSI_0]], %[[INDEX_CAST_1]] : index
// CHECK:             %[[ADDI_1:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_1]] : index
// CHECK:             %[[MINSI_1:.*]] = arith.minsi %[[ADDI_1]], %[[INDEX_CAST_2]] : index
// CHECK:             %[[MAXSI_1:.*]] = arith.maxsi %[[MINSI_1]], %[[INDEX_CAST_0]] : index
// CHECK:             %[[SUBI_1:.*]] = arith.subi %[[MAXSI_1]], %[[INDEX_CAST_0]] : index
// CHECK:             %[[MINSI_2:.*]] = arith.minsi %[[SUBI_0]], %[[CONSTANT_1]] : index
// CHECK:             %[[MINSI_3:.*]] = arith.minsi %[[SUBI_1]], %[[CONSTANT_1]] : index
// CHECK:             %[[VAL_3:.*]] = "tts.load"(%[[MAKE_TPTR_0]], %[[MINSI_2]], %[[MINSI_3]], %[[CONSTANT_0]]) <{operandSegmentSizes = array<i32: 1, 2, 1>, static_mask_dims = array<i64: -9223372036854775808, -9223372036854775808>}> : (tensor<256x256x!tt.ptr<f32>>, index, index, f32) -> tensor<256x256xf32>
// CHECK:             %[[ADDF_0:.*]] = arith.addf %[[VAL_1]], %[[VAL_3]] : tensor<256x256xf32>
// CHECK:             %[[MAKE_TPTR_1:.*]] = tts.make_tptr %[[ARG1]] to sizes: [256, 256], strides: {{\[}}%[[INDEX_CAST_2]], 1], offsets: {{\[}}%[[MULI_1]], %[[INDEX_CAST_0]]], shape: [0, 0], order: [] : <f32> to tensor<256x256x!tt.ptr<f32>>
// CHECK:             %[[VAL_4:.*]] = "tts.load"(%[[MAKE_TPTR_1]], %[[MINSI_2]], %[[MINSI_3]], %[[CONSTANT_0]]) <{operandSegmentSizes = array<i32: 1, 2, 1>, static_mask_dims = array<i64: -9223372036854775808, -9223372036854775808>}> : (tensor<256x256x!tt.ptr<f32>>, index, index, f32) -> tensor<256x256xf32>
// CHECK:             %[[ADDF_1:.*]] = arith.addf %[[VAL_2]], %[[VAL_4]] : tensor<256x256xf32>
// CHECK:             scf.yield %[[ADDF_0]], %[[ADDF_1]] : tensor<256x256xf32>, tensor<256x256xf32>
// CHECK:           }
// CHECK:           %[[VAL_5:.*]] = "tt.reduce"(%[[VAL_6:.*]]#0) <{axis = 0 : i32}> ({
// CHECK:           ^bb0(%[[VAL_7:.*]]: f32, %[[VAL_8:.*]]: f32):
// CHECK:             %[[ADDF_2:.*]] = arith.addf %[[VAL_7]], %[[VAL_8]] : f32
// CHECK:             tt.reduce.return %[[ADDF_2]] : f32
// CHECK:           }) : (tensor<256x256xf32>) -> tensor<256xf32>
// CHECK:           %[[VAL_9:.*]] = "tt.reduce"(%[[VAL_10:.*]]#1) <{axis = 0 : i32}> ({
// CHECK:           ^bb0(%[[VAL_11:.*]]: f32, %[[VAL_12:.*]]: f32):
// CHECK:             %[[ADDF_3:.*]] = arith.addf %[[VAL_11]], %[[VAL_12]] : f32
// CHECK:             tt.reduce.return %[[ADDF_3]] : f32
// CHECK:           }) : (tensor<256x256xf32>) -> tensor<256xf32>
// CHECK:           %[[MAKE_TPTR_2:.*]] = tts.make_tptr %[[ARG2]] to sizes: [256], strides: [1], offsets: {{\[}}%[[INDEX_CAST_0]]], shape: [0], order: [] : <f32> to tensor<256x!tt.ptr<f32>>
// CHECK:           %[[ADDI_2:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[INDEX_CAST_4:.*]] = arith.index_cast %[[ARG5]] : i32 to index
// CHECK:           %[[MINSI_4:.*]] = arith.minsi %[[ADDI_2]], %[[INDEX_CAST_4]] : index
// CHECK:           %[[MAXSI_2:.*]] = arith.maxsi %[[MINSI_4]], %[[INDEX_CAST_0]] : index
// CHECK:           %[[SUBI_2:.*]] = arith.subi %[[MAXSI_2]], %[[INDEX_CAST_0]] : index
// CHECK:           "tts.store"(%[[MAKE_TPTR_2]], %[[VAL_5]], %[[SUBI_2]]) <{static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<256x!tt.ptr<f32>>, tensor<256xf32>, index) -> ()
// CHECK:           %[[MAKE_TPTR_3:.*]] = tts.make_tptr %[[ARG3]] to sizes: [256], strides: [1], offsets: {{\[}}%[[INDEX_CAST_0]]], shape: [0], order: [] : <f32> to tensor<256x!tt.ptr<f32>>
// CHECK:           "tts.store"(%[[MAKE_TPTR_3]], %[[VAL_9]], %[[SUBI_2]]) <{static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<256x!tt.ptr<f32>>, tensor<256xf32>, index) -> ()
// CHECK:           tt.return
// CHECK:         }
  tt.func public @_layer_norm_bwd_dwdb_0123456(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: !tt.ptr<f32>, %arg3: !tt.ptr<f32>, %arg4: i32, %arg5: i32) {
    %c0_i32 = arith.constant 0 : i32
    %c256_i32 = arith.constant 256 : i32
    %cst = arith.constant 0.000000e+00 : f32
    %0 = tt.get_program_id x : i32
    %1 = arith.muli %0, %c256_i32 : i32
    %2 = tt.make_range {end = 256 : i32, start = 0 : i32} : tensor<256xi32>
    %3 = tt.splat %1 : i32 -> tensor<256xi32>
    %4 = arith.addi %3, %2 : tensor<256xi32>
    %5 = tt.splat %cst : f32 -> tensor<256x256xf32>
    %6 = tt.splat %arg4 : i32 -> tensor<256x1xi32>
    %7 = tt.expand_dims %4 {axis = 0 : i32} : tensor<256xi32> -> tensor<1x256xi32>
    %8 = tt.splat %arg5 : i32 -> tensor<1x256xi32>
    %9 = arith.cmpi slt, %7, %8 : tensor<1x256xi32>
    %10 = tt.broadcast %9 : tensor<1x256xi1> -> tensor<256x256xi1>
    %11 = tt.splat %arg5 : i32 -> tensor<256x1xi32>
    %12 = tt.broadcast %7 : tensor<1x256xi32> -> tensor<256x256xi32>
    %13 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<256x256x!tt.ptr<f32>>
    %14 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<256x256x!tt.ptr<f32>>
    %15:2 = scf.for %arg6 = %c0_i32 to %arg4 step %c256_i32 iter_args(%arg7 = %5, %arg8 = %5) -> (tensor<256x256xf32>, tensor<256x256xf32>)  : i32 {
      %24 = tt.splat %arg6 : i32 -> tensor<256xi32>
      %25 = arith.addi %24, %2 : tensor<256xi32>
      %26 = tt.expand_dims %25 {axis = 1 : i32} : tensor<256xi32> -> tensor<256x1xi32>
      %27 = arith.cmpi slt, %26, %6 : tensor<256x1xi32>
      %28 = tt.broadcast %27 : tensor<256x1xi1> -> tensor<256x256xi1>
      %29 = arith.andi %28, %10 : tensor<256x256xi1>
      %30 = arith.muli %26, %11 : tensor<256x1xi32>
      %31 = tt.broadcast %30 : tensor<256x1xi32> -> tensor<256x256xi32>
      %32 = arith.addi %31, %12 : tensor<256x256xi32>
      %33 = tt.addptr %13, %32 : tensor<256x256x!tt.ptr<f32>>, tensor<256x256xi32>
      %34 = tt.load %33, %29, %5 : tensor<256x256x!tt.ptr<f32>>
      %35 = arith.addf %arg7, %34 : tensor<256x256xf32>
      %36 = tt.addptr %14, %32 : tensor<256x256x!tt.ptr<f32>>, tensor<256x256xi32>
      %37 = tt.load %36, %29, %5 : tensor<256x256x!tt.ptr<f32>>
      %38 = arith.addf %arg8, %37 : tensor<256x256xf32>
      scf.yield %35, %38 : tensor<256x256xf32>, tensor<256x256xf32>
    }
    %16 = "tt.reduce"(%15#0) ({
    ^bb0(%arg6: f32, %arg7: f32):
      %24 = arith.addf %arg6, %arg7 : f32
      tt.reduce.return %24 : f32
    }) {axis = 0 : i32} : (tensor<256x256xf32>) -> tensor<256xf32>
    %17 = "tt.reduce"(%15#1) ({
    ^bb0(%arg6: f32, %arg7: f32):
      %24 = arith.addf %arg6, %arg7 : f32
      tt.reduce.return %24 : f32
    }) {axis = 0 : i32} : (tensor<256x256xf32>) -> tensor<256xf32>
    %18 = tt.splat %arg5 : i32 -> tensor<256xi32>
    %19 = arith.cmpi slt, %4, %18 : tensor<256xi32>
    %20 = tt.splat %arg2 : !tt.ptr<f32> -> tensor<256x!tt.ptr<f32>>
    %21 = tt.addptr %20, %4 : tensor<256x!tt.ptr<f32>>, tensor<256xi32>
    tt.store %21, %16, %19 : tensor<256x!tt.ptr<f32>>
    %22 = tt.splat %arg3 : !tt.ptr<f32> -> tensor<256x!tt.ptr<f32>>
    %23 = tt.addptr %22, %4 : tensor<256x!tt.ptr<f32>>, tensor<256xi32>
    tt.store %23, %17, %19 : tensor<256x!tt.ptr<f32>>
    tt.return
  }
}
