// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --triton-to-structured --remove-dead-values --cse --canonicalize %s | FileCheck %s

// Make sure make_gather_scatter_tptr with generic mask generate correctly from row-structured ptr with unstructured mask.
// The load is unstructured ptr on dim 1 and unstructured mask on dim 1.



// CHECK-LABEL:   tt.func public @generic_mask_3d_non_continuous_load_kernel(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<i32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG10:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant -2.000000e+00 : f32
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 16 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 4 : index
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
// CHECK:           %[[SPLAT_0:.*]] = tt.splat %[[ARG3]] : i32 -> tensor<4xi32>
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[MAKE_RANGE_0]], %[[SPLAT_0]] : tensor<4xi32>
// CHECK:           %[[MAKE_TPTR_0:.*]] = tts.make_tptr %[[ARG2]] to sizes: [4], strides: [1], offsets: [0], shape: [0], order: [] : <i32> to tensor<4x!tt.ptr<i32>>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG3]] : i32 to index
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[INDEX_CAST_0]], %[[CONSTANT_4]] : index
// CHECK:           %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_0]], %[[CONSTANT_3]] : index
// CHECK:           %[[VAL_0:.*]] = "tts.load"(%[[MAKE_TPTR_0]], %[[MAXSI_0]], %[[CONSTANT_2]]) <{operandSegmentSizes = array<i32: 1, 1, 1>, static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<4x!tt.ptr<i32>>, index, i32) -> tensor<4xi32>
// CHECK:           %[[SPLAT_1:.*]] = tt.splat %[[ARG5]] : i32 -> tensor<4xi32>
// CHECK:           %[[CMPI_1:.*]] = arith.cmpi slt, %[[VAL_0]], %[[SPLAT_1]] : tensor<4xi32>
// CHECK:           %[[ANDI_0:.*]] = arith.andi %[[CMPI_1]], %[[CMPI_0]] : tensor<4xi1>
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG7]] : i32 to index
// CHECK:           %[[INDEX_CAST_2:.*]] = arith.index_cast %[[ARG8]] : i32 to index
// CHECK:           %[[INDEX_CAST_3:.*]] = arith.index_cast %[[ARG4]] : i32 to index
// CHECK:           %[[MINSI_1:.*]] = arith.minsi %[[INDEX_CAST_3]], %[[CONSTANT_4]] : index
// CHECK:           %[[MAXSI_1:.*]] = arith.maxsi %[[MINSI_1]], %[[CONSTANT_3]] : index
// CHECK:           %[[INDEX_CAST_4:.*]] = arith.index_cast %[[ARG6]] : i32 to index
// CHECK:           %[[MINSI_2:.*]] = arith.minsi %[[INDEX_CAST_4]], %[[CONSTANT_1]] : index
// CHECK:           %[[MAXSI_2:.*]] = arith.maxsi %[[MINSI_2]], %[[CONSTANT_3]] : index
// CHECK:           %[[MINSI_3:.*]] = arith.minsi %[[MAXSI_2]], %[[CONSTANT_1]] : index
// CHECK:           %[[MINSI_4:.*]] = arith.minsi %[[MAXSI_1]], %[[CONSTANT_4]] : index
// CHECK:           %[[MINSI_5:.*]] = arith.minsi %[[MINSI_3]], %[[CONSTANT_1]] : index
// CHECK:           %[[MAKE_GATHER_SCATTER_TPTR_0:.*]] = tts.make_gather_scatter_tptr %[[ARG0]] to sizes: [4, 4, 16] gather_scatter_dim: 1 gather_scatter_offset: %[[VAL_0]] gather_scatter_mask: %[[ANDI_0]], strides: {{\[}}%[[INDEX_CAST_1]], %[[INDEX_CAST_2]], 1], offsets: [0, 0, 0] : tensor<4xi32> tensor<4xi1> <f32> to tensor<4x4x16x!tt.ptr<f32>>
// CHECK:           %[[VAL_1:.*]] = "tts.load"(%[[MAKE_GATHER_SCATTER_TPTR_0]], %[[MINSI_4]], %[[MINSI_5]], %[[CONSTANT_0]]) <{operandSegmentSizes = array<i32: 1, 2, 1>, static_mask_dims = array<i64: -9223372036854775808, 0, -9223372036854775808>}> : (tensor<4x4x16x!tt.ptr<f32>>, index, index, f32) -> tensor<4x4x16xf32>
// CHECK:           %[[INDEX_CAST_5:.*]] = arith.index_cast %[[ARG9]] : i32 to index
// CHECK:           %[[INDEX_CAST_6:.*]] = arith.index_cast %[[ARG10]] : i32 to index
// CHECK:           %[[MAKE_TPTR_1:.*]] = tts.make_tptr %[[ARG1]] to sizes: [4, 4, 16], strides: {{\[}}%[[INDEX_CAST_5]], %[[INDEX_CAST_6]], 1], offsets: [0, 0, 0], shape: [0, 0, 0], order: [] : <f32> to tensor<4x4x16x!tt.ptr<f32>>
// CHECK:           %[[MINSI_6:.*]] = arith.minsi %[[MAXSI_0]], %[[CONSTANT_4]] : index
// CHECK:           %[[MINSI_7:.*]] = arith.minsi %[[MINSI_6]], %[[CONSTANT_4]] : index
// CHECK:           "tts.store"(%[[MAKE_TPTR_1]], %[[VAL_1]], %[[MINSI_4]], %[[MINSI_7]], %[[MINSI_5]]) <{static_mask_dims = array<i64: -9223372036854775808, -9223372036854775808, -9223372036854775808>}> : (tensor<4x4x16x!tt.ptr<f32>>, tensor<4x4x16xf32>, index, index, index) -> ()
// CHECK:           tt.return
// CHECK:         }
module {
  tt.func public @generic_mask_3d_non_continuous_load_kernel(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg2: !tt.ptr<i32> {tt.divisibility = 16 : i32}, %arg3: i32, %arg4: i32, %arg5: i32, %arg6: i32 {tt.divisibility = 16 : i32}, %arg7: i32 {tt.divisibility = 16 : i32}, %arg8: i32 {tt.divisibility = 16 : i32}, %arg9: i32 {tt.divisibility = 16 : i32}, %arg10: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %cst = arith.constant dense<-2.000000e+00> : tensor<4x4x16xf32>
    %cst_0 = arith.constant dense<0> : tensor<4xi32>
    %0 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %1 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
    %2 = tt.splat %arg3 : i32 -> tensor<4xi32>
    %3 = arith.cmpi slt, %0, %2 : tensor<4xi32>
    %4 = tt.splat %arg2 : !tt.ptr<i32> -> tensor<4x!tt.ptr<i32>>
    %5 = tt.addptr %4, %0 : tensor<4x!tt.ptr<i32>>, tensor<4xi32>
    %6 = tt.load %5, %3, %cst_0 : tensor<4x!tt.ptr<i32>>
    %7 = tt.splat %arg5 : i32 -> tensor<4xi32>
    %8 = arith.cmpi slt, %6, %7 : tensor<4xi32>
    %9 = arith.andi %8, %3 : tensor<4xi1>
    %10 = tt.expand_dims %0 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
    %11 = tt.expand_dims %10 {axis = 2 : i32} : tensor<4x1xi32> -> tensor<4x1x1xi32>
    %12 = tt.splat %arg7 : i32 -> tensor<4x1x1xi32>
    %13 = arith.muli %11, %12 : tensor<4x1x1xi32>
    %14 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<4x1x1x!tt.ptr<f32>>
    %15 = tt.addptr %14, %13 : tensor<4x1x1x!tt.ptr<f32>>, tensor<4x1x1xi32>
    %16 = tt.expand_dims %6 {axis = 0 : i32} : tensor<4xi32> -> tensor<1x4xi32>
    %17 = tt.expand_dims %16 {axis = 2 : i32} : tensor<1x4xi32> -> tensor<1x4x1xi32>
    %18 = tt.splat %arg8 : i32 -> tensor<1x4x1xi32>
    %19 = arith.muli %17, %18 : tensor<1x4x1xi32>
    %20 = tt.broadcast %15 : tensor<4x1x1x!tt.ptr<f32>> -> tensor<4x4x1x!tt.ptr<f32>>
    %21 = tt.broadcast %19 : tensor<1x4x1xi32> -> tensor<4x4x1xi32>
    %22 = tt.addptr %20, %21 : tensor<4x4x1x!tt.ptr<f32>>, tensor<4x4x1xi32>
    %23 = tt.expand_dims %1 {axis = 0 : i32} : tensor<16xi32> -> tensor<1x16xi32>
    %24 = tt.expand_dims %23 {axis = 1 : i32} : tensor<1x16xi32> -> tensor<1x1x16xi32>
    %25 = tt.broadcast %22 : tensor<4x4x1x!tt.ptr<f32>> -> tensor<4x4x16x!tt.ptr<f32>>
    %26 = tt.broadcast %24 : tensor<1x1x16xi32> -> tensor<4x4x16xi32>
    %27 = tt.addptr %25, %26 : tensor<4x4x16x!tt.ptr<f32>>, tensor<4x4x16xi32>
    %28 = tt.splat %arg4 : i32 -> tensor<4x1x1xi32>
    %29 = arith.cmpi slt, %11, %28 : tensor<4x1x1xi32>
    %30 = tt.expand_dims %9 {axis = 0 : i32} : tensor<4xi1> -> tensor<1x4xi1>
    %31 = tt.expand_dims %30 {axis = 2 : i32} : tensor<1x4xi1> -> tensor<1x4x1xi1>
    %32 = tt.splat %arg6 : i32 -> tensor<1x1x16xi32>
    %33 = arith.cmpi slt, %24, %32 : tensor<1x1x16xi32>
    %34 = tt.broadcast %31 : tensor<1x4x1xi1> -> tensor<1x4x16xi1>
    %35 = tt.broadcast %33 : tensor<1x1x16xi1> -> tensor<1x4x16xi1>
    %36 = arith.andi %34, %35 : tensor<1x4x16xi1>
    %37 = tt.broadcast %29 : tensor<4x1x1xi1> -> tensor<4x4x16xi1>
    %38 = tt.broadcast %36 : tensor<1x4x16xi1> -> tensor<4x4x16xi1>
    %39 = arith.andi %37, %38 : tensor<4x4x16xi1>
    %40 = tt.load %27, %39, %cst : tensor<4x4x16x!tt.ptr<f32>>
    %41 = tt.splat %arg9 : i32 -> tensor<4x1x1xi32>
    %42 = arith.muli %11, %41 : tensor<4x1x1xi32>
    %43 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<4x1x1x!tt.ptr<f32>>
    %44 = tt.addptr %43, %42 : tensor<4x1x1x!tt.ptr<f32>>, tensor<4x1x1xi32>
    %45 = tt.expand_dims %0 {axis = 0 : i32} : tensor<4xi32> -> tensor<1x4xi32>
    %46 = tt.expand_dims %45 {axis = 2 : i32} : tensor<1x4xi32> -> tensor<1x4x1xi32>
    %47 = tt.splat %arg10 : i32 -> tensor<1x4x1xi32>
    %48 = arith.muli %46, %47 : tensor<1x4x1xi32>
    %49 = tt.broadcast %44 : tensor<4x1x1x!tt.ptr<f32>> -> tensor<4x4x1x!tt.ptr<f32>>
    %50 = tt.broadcast %48 : tensor<1x4x1xi32> -> tensor<4x4x1xi32>
    %51 = tt.addptr %49, %50 : tensor<4x4x1x!tt.ptr<f32>>, tensor<4x4x1xi32>
    %52 = tt.broadcast %51 : tensor<4x4x1x!tt.ptr<f32>> -> tensor<4x4x16x!tt.ptr<f32>>
    %53 = tt.addptr %52, %26 : tensor<4x4x16x!tt.ptr<f32>>, tensor<4x4x16xi32>
    %54 = tt.splat %arg3 : i32 -> tensor<1x4x1xi32>
    %55 = arith.cmpi slt, %46, %54 : tensor<1x4x1xi32>
    %56 = tt.broadcast %55 : tensor<1x4x1xi1> -> tensor<1x4x16xi1>
    %57 = arith.andi %56, %35 : tensor<1x4x16xi1>
    %58 = tt.broadcast %57 : tensor<1x4x16xi1> -> tensor<4x4x16xi1>
    %59 = arith.andi %37, %58 : tensor<4x4x16xi1>
    tt.store %53, %40, %59 : tensor<4x4x16x!tt.ptr<f32>>
    tt.return
  }
}
