// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --triton-to-structured --remove-dead-values --cse --canonicalize %s | FileCheck %s

// Make sure make_gather_scatter_tptr with generic mask generate correctly from column-structured ptr with unstructured mask.
// The store is unstructured ptr on dim 2 and unstructured mask on dim 2.



// CHECK-LABEL:   tt.func public @generic_mask_3d_non_continuous_store_kernel(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<i32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant -2.000000e+00 : f32
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 8 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 16 : index
// CHECK:           %[[MAKE_RANGE_0:.*]] = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
// CHECK:           %[[SPLAT_0:.*]] = tt.splat %[[ARG6]] : i32 -> tensor<16xi32>
// CHECK:           %[[MAKE_TPTR_0:.*]] = tts.make_tptr %[[ARG2]] to sizes: [16], strides: [1], offsets: [0], shape: [0], order: [] : <i32> to tensor<16x!tt.ptr<i32>>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG6]] : i32 to index
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[INDEX_CAST_0]], %[[CONSTANT_5]] : index
// CHECK:           %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_0]], %[[CONSTANT_4]] : index
// CHECK:           %[[VAL_0:.*]] = "tts.load"(%[[MAKE_TPTR_0]], %[[MAXSI_0]], %[[CONSTANT_3]]) <{operandSegmentSizes = array<i32: 1, 1, 1>, static_mask_dims = array<i64: -9223372036854775808>}> : (tensor<16x!tt.ptr<i32>>, index, i32) -> tensor<16xi32>
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[VAL_0]], %[[SPLAT_0]] : tensor<16xi32>
// CHECK:           %[[SPLAT_1:.*]] = tt.splat %[[ARG3]] : i32 -> tensor<16xi32>
// CHECK:           %[[CMPI_1:.*]] = arith.cmpi slt, %[[MAKE_RANGE_0]], %[[SPLAT_1]] : tensor<16xi32>
// CHECK:           %[[ANDI_0:.*]] = arith.andi %[[CMPI_0]], %[[CMPI_1]] : tensor<16xi1>
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG7]] : i32 to index
// CHECK:           %[[INDEX_CAST_2:.*]] = arith.index_cast %[[ARG8]] : i32 to index
// CHECK:           %[[MAKE_TPTR_1:.*]] = tts.make_tptr %[[ARG0]] to sizes: [4, 8, 16], strides: {{\[}}%[[INDEX_CAST_1]], %[[INDEX_CAST_2]], 1], offsets: [0, 0, 0], shape: [0, 0, 0], order: [] : <f32> to tensor<4x8x16x!tt.ptr<f32>>
// CHECK:           %[[INDEX_CAST_3:.*]] = arith.index_cast %[[ARG4]] : i32 to index
// CHECK:           %[[MINSI_1:.*]] = arith.minsi %[[INDEX_CAST_3]], %[[CONSTANT_2]] : index
// CHECK:           %[[MAXSI_1:.*]] = arith.maxsi %[[MINSI_1]], %[[CONSTANT_4]] : index
// CHECK:           %[[INDEX_CAST_4:.*]] = arith.index_cast %[[ARG5]] : i32 to index
// CHECK:           %[[MINSI_2:.*]] = arith.minsi %[[INDEX_CAST_4]], %[[CONSTANT_1]] : index
// CHECK:           %[[MAXSI_2:.*]] = arith.maxsi %[[MINSI_2]], %[[CONSTANT_4]] : index
// CHECK:           %[[INDEX_CAST_5:.*]] = arith.index_cast %[[ARG3]] : i32 to index
// CHECK:           %[[MINSI_3:.*]] = arith.minsi %[[INDEX_CAST_5]], %[[CONSTANT_5]] : index
// CHECK:           %[[MAXSI_3:.*]] = arith.maxsi %[[MINSI_3]], %[[CONSTANT_4]] : index
// CHECK:           %[[MINSI_4:.*]] = arith.minsi %[[MAXSI_2]], %[[CONSTANT_1]] : index
// CHECK:           %[[MINSI_5:.*]] = arith.minsi %[[MAXSI_3]], %[[CONSTANT_5]] : index
// CHECK:           %[[MINSI_6:.*]] = arith.minsi %[[MAXSI_1]], %[[CONSTANT_2]] : index
// CHECK:           %[[MINSI_7:.*]] = arith.minsi %[[MINSI_4]], %[[CONSTANT_1]] : index
// CHECK:           %[[MINSI_8:.*]] = arith.minsi %[[MINSI_5]], %[[CONSTANT_5]] : index
// CHECK:           %[[VAL_1:.*]] = "tts.load"(%[[MAKE_TPTR_1]], %[[MINSI_6]], %[[MINSI_7]], %[[MINSI_8]], %[[CONSTANT_0]]) <{operandSegmentSizes = array<i32: 1, 3, 1>, static_mask_dims = array<i64: -9223372036854775808, -9223372036854775808, -9223372036854775808>}> : (tensor<4x8x16x!tt.ptr<f32>>, index, index, index, f32) -> tensor<4x8x16xf32>
// CHECK:           %[[MAKE_GATHER_SCATTER_TPTR_0:.*]] = tts.make_gather_scatter_tptr %[[ARG1]] to sizes: [4, 8, 16] gather_scatter_dim: 2 gather_scatter_offset: %[[VAL_0]] gather_scatter_mask: %[[ANDI_0]], strides: {{\[}}%[[INDEX_CAST_1]], %[[INDEX_CAST_2]], 1], offsets: [0, 0, 0] : tensor<16xi32> tensor<16xi1> <f32> to tensor<4x8x16x!tt.ptr<f32>>
// CHECK:           "tts.store"(%[[MAKE_GATHER_SCATTER_TPTR_0]], %[[VAL_1]], %[[MINSI_6]], %[[MINSI_7]]) <{static_mask_dims = array<i64: -9223372036854775808, -9223372036854775808, 0>}> : (tensor<4x8x16x!tt.ptr<f32>>, tensor<4x8x16xf32>, index, index) -> ()
// CHECK:           tt.return
// CHECK:         }
module {
  tt.func public @generic_mask_3d_non_continuous_store_kernel(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg2: !tt.ptr<i32> {tt.divisibility = 16 : i32}, %arg3: i32, %arg4: i32, %arg5: i32, %arg6: i32 {tt.divisibility = 16 : i32}, %arg7: i32 {tt.divisibility = 16 : i32}, %arg8: i32 {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %cst = arith.constant dense<-2.000000e+00> : tensor<4x8x16xf32>
    %cst_0 = arith.constant dense<0> : tensor<16xi32>
    %0 = tt.make_range {end = 8 : i32, start = 0 : i32} : tensor<8xi32>
    %1 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
    %2 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %3 = tt.splat %arg6 : i32 -> tensor<16xi32>
    %4 = arith.cmpi slt, %1, %3 : tensor<16xi32>
    %5 = tt.splat %arg2 : !tt.ptr<i32> -> tensor<16x!tt.ptr<i32>>
    %6 = tt.addptr %5, %1 : tensor<16x!tt.ptr<i32>>, tensor<16xi32>
    %7 = tt.load %6, %4, %cst_0 : tensor<16x!tt.ptr<i32>>
    %8 = arith.cmpi slt, %7, %3 : tensor<16xi32>
    %9 = tt.splat %arg3 : i32 -> tensor<16xi32>
    %10 = arith.cmpi slt, %1, %9 : tensor<16xi32>
    %11 = arith.andi %8, %10 : tensor<16xi1>
    %12 = tt.expand_dims %2 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
    %13 = tt.expand_dims %12 {axis = 2 : i32} : tensor<4x1xi32> -> tensor<4x1x1xi32>
    %14 = tt.splat %arg7 : i32 -> tensor<4x1x1xi32>
    %15 = arith.muli %13, %14 : tensor<4x1x1xi32>
    %16 = tt.splat %arg0 : !tt.ptr<f32> -> tensor<4x1x1x!tt.ptr<f32>>
    %17 = tt.addptr %16, %15 : tensor<4x1x1x!tt.ptr<f32>>, tensor<4x1x1xi32>
    %18 = tt.expand_dims %0 {axis = 0 : i32} : tensor<8xi32> -> tensor<1x8xi32>
    %19 = tt.expand_dims %18 {axis = 2 : i32} : tensor<1x8xi32> -> tensor<1x8x1xi32>
    %20 = tt.splat %arg8 : i32 -> tensor<1x8x1xi32>
    %21 = arith.muli %19, %20 : tensor<1x8x1xi32>
    %22 = tt.broadcast %17 : tensor<4x1x1x!tt.ptr<f32>> -> tensor<4x8x1x!tt.ptr<f32>>
    %23 = tt.broadcast %21 : tensor<1x8x1xi32> -> tensor<4x8x1xi32>
    %24 = tt.addptr %22, %23 : tensor<4x8x1x!tt.ptr<f32>>, tensor<4x8x1xi32>
    %25 = tt.expand_dims %1 {axis = 0 : i32} : tensor<16xi32> -> tensor<1x16xi32>
    %26 = tt.expand_dims %25 {axis = 1 : i32} : tensor<1x16xi32> -> tensor<1x1x16xi32>
    %27 = tt.broadcast %24 : tensor<4x8x1x!tt.ptr<f32>> -> tensor<4x8x16x!tt.ptr<f32>>
    %28 = tt.broadcast %26 : tensor<1x1x16xi32> -> tensor<4x8x16xi32>
    %29 = tt.addptr %27, %28 : tensor<4x8x16x!tt.ptr<f32>>, tensor<4x8x16xi32>
    %30 = tt.splat %arg4 : i32 -> tensor<4x1x1xi32>
    %31 = arith.cmpi slt, %13, %30 : tensor<4x1x1xi32>
    %32 = tt.splat %arg5 : i32 -> tensor<1x8x1xi32>
    %33 = arith.cmpi slt, %19, %32 : tensor<1x8x1xi32>
    %34 = tt.splat %arg3 : i32 -> tensor<1x1x16xi32>
    %35 = arith.cmpi slt, %26, %34 : tensor<1x1x16xi32>
    %36 = tt.broadcast %33 : tensor<1x8x1xi1> -> tensor<1x8x16xi1>
    %37 = tt.broadcast %35 : tensor<1x1x16xi1> -> tensor<1x8x16xi1>
    %38 = arith.andi %36, %37 : tensor<1x8x16xi1>
    %39 = tt.broadcast %31 : tensor<4x1x1xi1> -> tensor<4x8x16xi1>
    %40 = tt.broadcast %38 : tensor<1x8x16xi1> -> tensor<4x8x16xi1>
    %41 = arith.andi %39, %40 : tensor<4x8x16xi1>
    %42 = tt.load %29, %41, %cst : tensor<4x8x16x!tt.ptr<f32>>
    %43 = tt.splat %arg1 : !tt.ptr<f32> -> tensor<4x1x1x!tt.ptr<f32>>
    %44 = tt.addptr %43, %15 : tensor<4x1x1x!tt.ptr<f32>>, tensor<4x1x1xi32>
    %45 = tt.broadcast %44 : tensor<4x1x1x!tt.ptr<f32>> -> tensor<4x8x1x!tt.ptr<f32>>
    %46 = tt.addptr %45, %23 : tensor<4x8x1x!tt.ptr<f32>>, tensor<4x8x1xi32>
    %47 = tt.expand_dims %7 {axis = 0 : i32} : tensor<16xi32> -> tensor<1x16xi32>
    %48 = tt.expand_dims %47 {axis = 1 : i32} : tensor<1x16xi32> -> tensor<1x1x16xi32>
    %49 = tt.broadcast %46 : tensor<4x8x1x!tt.ptr<f32>> -> tensor<4x8x16x!tt.ptr<f32>>
    %50 = tt.broadcast %48 : tensor<1x1x16xi32> -> tensor<4x8x16xi32>
    %51 = tt.addptr %49, %50 : tensor<4x8x16x!tt.ptr<f32>>, tensor<4x8x16xi32>
    %52 = tt.expand_dims %11 {axis = 0 : i32} : tensor<16xi1> -> tensor<1x16xi1>
    %53 = tt.expand_dims %52 {axis = 1 : i32} : tensor<1x16xi1> -> tensor<1x1x16xi1>
    %54 = tt.broadcast %53 : tensor<1x1x16xi1> -> tensor<1x8x16xi1>
    %55 = arith.andi %36, %54 : tensor<1x8x16xi1>
    %56 = tt.broadcast %55 : tensor<1x8x16xi1> -> tensor<4x8x16xi1>
    %57 = arith.andi %39, %56 : tensor<4x8x16xi1>
    tt.store %51, %42, %57 : tensor<4x8x16x!tt.ptr<f32>>
    tt.return
  }
}
