// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt --split-input-file --triton-to-linalg-experimental %s | FileCheck %s
module {
// CHECK-LABEL:   func.func @kernel(
// CHECK-SAME:                      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: f32,
// CHECK-SAME:                      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: bf16,
// CHECK-SAME:                      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xbf16>,
// CHECK-SAME:                      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 256 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 128 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 1024 : index
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[ARG2]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:             memref.store %[[ARG0]], %[[CAST_0]]{{\[}}%[[CONSTANT_3]]] : memref<?xf32>
// CHECK:           }
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[ARG3]] : memref<*xbf16> to memref<?xbf16>
// CHECK:           scf.for %[[VAL_1:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_1]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_2:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_0]] step %[[CONSTANT_2]] {
// CHECK:               memref.store %[[ARG1]], %[[CAST_1]]{{\[}}%[[CONSTANT_3]]] : memref<?xbf16>
// CHECK:             }
// CHECK:           }
// CHECK:           return
// CHECK:         }
    tt.func @kernel(%fin : f32,
                    %bin : bf16,
                    %save_ptr0 : !tt.ptr<f32>,
                    %save_ptr1 : !tt.ptr<bf16>) -> () {
        %0 = tt.splat %fin : f32 -> tensor<1024xf32>
        %1 = tt.splat %bin : bf16 -> tensor<128x256xbf16>
        // save pointers, intentionally splat the base pointer for brevity
        %save0 = tt.splat %save_ptr0 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
        %save1 = tt.splat %save_ptr1 : !tt.ptr<bf16> -> tensor<128x256x!tt.ptr<bf16>>
        tt.store %save0, %0 : tensor<1024x!tt.ptr<f32>>
        tt.store %save1, %1 : tensor<128x256x!tt.ptr<bf16>>
        tt.return
    }
}
