// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --triton-to-linalg-experimental %s | FileCheck %s
// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>
// CHECK-LABEL:   func.func @kernel(
// CHECK-SAME:                      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xi32>,
// CHECK-SAME:                      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf16>,
// CHECK-SAME:                      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xbf16>,
// CHECK-SAME:                      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:                      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG10:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG11:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG12:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG13:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[EMPTY_0:.*]] = tensor.empty() : tensor<1024xi32>
// CHECK:           %[[FILL_0:.*]] = linalg.fill ins(%[[CONSTANT_0]] : i32) outs(%[[EMPTY_0]] : tensor<1024xi32>) -> tensor<1024xi32>
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[ARG0]] to offset: [0], sizes: [1024], strides: [1] : memref<*xf32> to memref<1024xf32, strided<[1]>>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<1024xf32>
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<1024xf32, strided<[1]>> to memref<1024xf32>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<1024xf32> to tensor<1024xf32>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: [0], sizes: [1024], strides: [1] : memref<*xi32> to memref<1024xi32, strided<[1]>>
// CHECK:           %[[ALLOC_1:.*]] = memref.alloc() : memref<1024xi32>
// CHECK:           memref.copy %[[REINTERPRET_CAST_1]], %[[ALLOC_1]] : memref<1024xi32, strided<[1]>> to memref<1024xi32>
// CHECK:           %[[TO_TENSOR_1:.*]] = bufferization.to_tensor %[[ALLOC_1]] restrict writable : memref<1024xi32> to tensor<1024xi32>
// CHECK:           %[[REINTERPRET_CAST_2:.*]] = memref.reinterpret_cast %[[ARG2]] to offset: [0], sizes: [1024], strides: [1] : memref<*xf16> to memref<1024xf16, strided<[1]>>
// CHECK:           %[[ALLOC_2:.*]] = memref.alloc() : memref<1024xf16>
// CHECK:           memref.copy %[[REINTERPRET_CAST_2]], %[[ALLOC_2]] : memref<1024xf16, strided<[1]>> to memref<1024xf16>
// CHECK:           %[[TO_TENSOR_2:.*]] = bufferization.to_tensor %[[ALLOC_2]] restrict writable : memref<1024xf16> to tensor<1024xf16>
// CHECK:           %[[EMPTY_1:.*]] = tensor.empty() : tensor<1024xbf16>
// CHECK:           %[[GENERIC_0:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[TO_TENSOR_0]] : tensor<1024xf32>) outs(%[[EMPTY_1]] : tensor<1024xbf16>) {
// CHECK:           ^bb0(%[[VAL_0:.*]]: f32, %[[VAL_1:.*]]: bf16):
// CHECK:             %[[TRUNCF_0:.*]] = arith.truncf %[[VAL_0]] : f32 to bf16
// CHECK:             linalg.yield %[[TRUNCF_0]] : bf16
// CHECK:           } -> tensor<1024xbf16>
// CHECK:           %[[GENERIC_1:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[TO_TENSOR_0]] : tensor<1024xf32>) outs(%[[TO_TENSOR_0]] : tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_2:.*]]: f32, %[[VAL_3:.*]]: f32):
// CHECK:             %[[EXP_0:.*]] = math.exp %[[VAL_2]] : f32
// CHECK:             linalg.yield %[[EXP_0]] : f32
// CHECK:           } -> tensor<1024xf32>
// CHECK:           %[[EMPTY_2:.*]] = tensor.empty() : tensor<1024xf32>
// CHECK:           %[[GENERIC_2:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[TO_TENSOR_1]] : tensor<1024xi32>) outs(%[[EMPTY_2]] : tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: f32):
// CHECK:             %[[SITOFP_0:.*]] = arith.sitofp %[[VAL_4]] : i32 to f32
// CHECK:             linalg.yield %[[SITOFP_0]] : f32
// CHECK:           } -> tensor<1024xf32>
// CHECK:           %[[GENERIC_3:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[TO_TENSOR_2]] : tensor<1024xf16>) outs(%[[EMPTY_2]] : tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_6:.*]]: f16, %[[VAL_7:.*]]: f32):
// CHECK:             %[[EXTF_0:.*]] = arith.extf %[[VAL_6]] : f16 to f32
// CHECK:             linalg.yield %[[EXTF_0]] : f32
// CHECK:           } -> tensor<1024xf32>
// CHECK:           %[[GENERIC_4:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[TO_TENSOR_0]] : tensor<1024xf32>) outs(%[[TO_TENSOR_0]] : tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_8:.*]]: f32, %[[VAL_9:.*]]: f32):
// CHECK:             %[[SQRT_0:.*]] = math.sqrt %[[VAL_8]] : f32
// CHECK:             linalg.yield %[[SQRT_0]] : f32
// CHECK:           } -> tensor<1024xf32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[ARG3]] : memref<*xbf16> to memref<?xbf16>
// CHECK:           linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[FILL_0]], %[[GENERIC_0]] : tensor<1024xi32>, tensor<1024xbf16>) {
// CHECK:           ^bb0(%[[VAL_10:.*]]: i32, %[[VAL_11:.*]]: bf16):
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_10]] : i32 to index
// CHECK:             memref.store %[[VAL_11]], %[[CAST_0]]{{\[}}%[[INDEX_CAST_0]]] : memref<?xbf16>
// CHECK:             linalg.yield
// CHECK:           }
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[ARG4]] : memref<*xf32> to memref<?xf32>
// CHECK:           linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[FILL_0]], %[[GENERIC_1]] : tensor<1024xi32>, tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_12:.*]]: i32, %[[VAL_13:.*]]: f32):
// CHECK:             %[[INDEX_CAST_1:.*]] = arith.index_cast %[[VAL_12]] : i32 to index
// CHECK:             memref.store %[[VAL_13]], %[[CAST_1]]{{\[}}%[[INDEX_CAST_1]]] : memref<?xf32>
// CHECK:             linalg.yield
// CHECK:           }
// CHECK:           %[[CAST_2:.*]] = memref.cast %[[ARG5]] : memref<*xf32> to memref<?xf32>
// CHECK:           linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[FILL_0]], %[[GENERIC_2]] : tensor<1024xi32>, tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_14:.*]]: i32, %[[VAL_15:.*]]: f32):
// CHECK:             %[[INDEX_CAST_2:.*]] = arith.index_cast %[[VAL_14]] : i32 to index
// CHECK:             memref.store %[[VAL_15]], %[[CAST_2]]{{\[}}%[[INDEX_CAST_2]]] : memref<?xf32>
// CHECK:             linalg.yield
// CHECK:           }
// CHECK:           %[[CAST_3:.*]] = memref.cast %[[ARG6]] : memref<*xf32> to memref<?xf32>
// CHECK:           linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[FILL_0]], %[[GENERIC_3]] : tensor<1024xi32>, tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_16:.*]]: i32, %[[VAL_17:.*]]: f32):
// CHECK:             %[[INDEX_CAST_3:.*]] = arith.index_cast %[[VAL_16]] : i32 to index
// CHECK:             memref.store %[[VAL_17]], %[[CAST_3]]{{\[}}%[[INDEX_CAST_3]]] : memref<?xf32>
// CHECK:             linalg.yield
// CHECK:           }
// CHECK:           %[[CAST_4:.*]] = memref.cast %[[ARG7]] : memref<*xf32> to memref<?xf32>
// CHECK:           linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[FILL_0]], %[[GENERIC_4]] : tensor<1024xi32>, tensor<1024xf32>) {
// CHECK:           ^bb0(%[[VAL_18:.*]]: i32, %[[VAL_19:.*]]: f32):
// CHECK:             %[[INDEX_CAST_4:.*]] = arith.index_cast %[[VAL_18]] : i32 to index
// CHECK:             memref.store %[[VAL_19]], %[[CAST_4]]{{\[}}%[[INDEX_CAST_4]]] : memref<?xf32>
// CHECK:             linalg.yield
// CHECK:           }
// CHECK:           return
// CHECK:         }
module {
  tt.func @kernel(
    %f32ptr : !tt.ptr<f32>,
    %intptr : !tt.ptr<i32>,
    %f16ptr : !tt.ptr<f16>,
    %save_ptr0 : !tt.ptr<bf16>,
    %save_ptr1 : !tt.ptr<f32>,
    %save_ptr2 : !tt.ptr<f32>,
    %save_ptr3 : !tt.ptr<f32>,
    %save_ptr4 : !tt.ptr<f32>
  ) -> () {
    // offset calculations
    %0 = tt.make_range {end = 1024 : i32, start = 0 : i32} : tensor<1024xi32>
    // f32ptr pointer
    %8 = tt.splat %f32ptr : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %9 = tt.addptr %8, %0 : tensor<1024x!tt.ptr<f32>>, tensor<1024xi32>
    // intptr pointer
    %18 = tt.splat %intptr : !tt.ptr<i32> -> tensor<1024x!tt.ptr<i32>>
    %19 = tt.addptr %18, %0 : tensor<1024x!tt.ptr<i32>>, tensor<1024xi32>
    // f32ptr pointer
    %28 = tt.splat %f16ptr : !tt.ptr<f16> -> tensor<1024x!tt.ptr<f16>>
    %29 = tt.addptr %28, %0 : tensor<1024x!tt.ptr<f16>>, tensor<1024xi32>
    %afm = tt.load %9 : tensor<1024x!tt.ptr<f32>>
    %aim = tt.load %19 : tensor<1024x!tt.ptr<i32>>
    %bfm = tt.load %29 : tensor<1024x!tt.ptr<f16>>
    %5 = arith.truncf %afm : tensor<1024xf32> to tensor<1024xbf16>
    %6 = math.exp %afm : tensor<1024xf32>
    %7 = arith.sitofp %aim : tensor<1024xi32> to tensor<1024xf32>
    %10 = arith.extf %bfm : tensor<1024xf16> to tensor<1024xf32>
    %11 = math.sqrt %afm : tensor<1024xf32>
    // save pointers, intentionally splat the base pointer for brevity
    %save0 = tt.splat %save_ptr0 : !tt.ptr<bf16> -> tensor<1024x!tt.ptr<bf16>>
    %save1 = tt.splat %save_ptr1 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %save2 = tt.splat %save_ptr2 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %save3 = tt.splat %save_ptr3 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    %save4 = tt.splat %save_ptr4 : !tt.ptr<f32> -> tensor<1024x!tt.ptr<f32>>
    tt.store %save0, %5 : tensor<1024x!tt.ptr<bf16>>
    tt.store %save1, %6 : tensor<1024x!tt.ptr<f32>>
    tt.store %save2, %7 : tensor<1024x!tt.ptr<f32>>
    tt.store %save3, %10 : tensor<1024x!tt.ptr<f32>>
    tt.store %save4, %11 : tensor<1024x!tt.ptr<f32>>
    tt.return
  }
}
