// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt --triton-to-linalg-experimental --cse %s | FileCheck %s

// RUN: triton-shared-opt --triton-to-linalg-experimental="enable-make-gather-scatter=false" %s | FileCheck %s --check-prefix=NO_GATHER

// Make sure no extract_slice when enable-make-gather-scatter=false..
// NO_GATHER-LABEL: func.func @row_gather2(
// NO_GATHER-NOT: extract_slice
// NO_GATHER: return


// Make sure extract_slice is generated correctly.



module {
// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>
// CHECK: #[[$ATTR_1:.+]] = affine_map<(d0, d1) -> (d0, d1)>
// CHECK-LABEL:   func.func @row_gather2(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG10:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG11:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG12:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i64,
// CHECK-SAME:      %[[ARG13:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG14:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG15:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG16:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG17:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG18:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 16 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 8 : i32
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 1 : index
// CHECK:           %[[EMPTY_0:.*]] = tensor.empty() : tensor<16x1xi32>
// CHECK:           %[[FILL_0:.*]] = linalg.fill ins(%[[CONSTANT_2]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[ARG5]], %[[CONSTANT_2]] : i32
// CHECK:           %[[EMPTY_1:.*]] = tensor.empty() : tensor<16xi32>
// CHECK:           %[[GENERIC_0:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[EMPTY_1]] : tensor<16xi32>) {
// CHECK:           ^bb0(%[[VAL_0:.*]]: i32):
// CHECK:             %[[INDEX_0:.*]] = linalg.index 0 : index
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[INDEX_0]] : index to i32
// CHECK:             linalg.yield %[[INDEX_CAST_0]] : i32
// CHECK:           } -> tensor<16xi32>
// CHECK:           %[[EXPAND_SHAPE_0:.*]] = tensor.expand_shape %[[GENERIC_0]] {{\[\[}}0, 1]] output_shape [16, 1] : tensor<16xi32> into tensor<16x1xi32>
// CHECK:           %[[GENERIC_1:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[EXPAND_SHAPE_0]], %[[FILL_0]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[EXPAND_SHAPE_0]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32):
// CHECK:             %[[REMSI_0:.*]] = arith.remsi %[[VAL_1]], %[[VAL_2]] : i32
// CHECK:             linalg.yield %[[REMSI_0]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[MULI_1:.*]] = arith.muli %[[ARG3]], %[[CONSTANT_2]] : i32
// CHECK:           %[[GENERIC_2:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[EXPAND_SHAPE_0]], %[[FILL_0]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[EXPAND_SHAPE_0]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32):
// CHECK:             %[[DIVSI_0:.*]] = arith.divsi %[[VAL_4]], %[[VAL_5]] : i32
// CHECK:             linalg.yield %[[DIVSI_0]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[EXTSI_0:.*]] = arith.extsi %[[ARG2]] : i32 to i64
// CHECK:           %[[MULI_2:.*]] = arith.muli %[[EXTSI_0]], %[[ARG7]] : i64
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[MULI_2]] : i64 to index
// CHECK:           %[[FILL_1:.*]] = linalg.fill ins(%[[ARG4]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_3:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_2]], %[[FILL_1]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[GENERIC_2]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32, %[[VAL_9:.*]]: i32):
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[VAL_7]], %[[VAL_8]] : i32
// CHECK:             linalg.yield %[[ADDI_0]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_2:.*]] = arith.index_cast %[[ARG6]] : i64 to index
// CHECK:           %[[FILL_2:.*]] = linalg.fill ins(%[[MULI_1]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_4:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_1]], %[[FILL_2]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[GENERIC_1]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_10:.*]]: i32, %[[VAL_11:.*]]: i32, %[[VAL_12:.*]]: i32):
// CHECK:             %[[ADDI_1:.*]] = arith.addi %[[VAL_10]], %[[VAL_11]] : i32
// CHECK:             linalg.yield %[[ADDI_1]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_3:.*]] = arith.index_cast %[[ARG8]] : i64 to index
// CHECK:           %[[INDEX_CAST_4:.*]] = arith.index_cast %[[INDEX_CAST_2]] : index to i32
// CHECK:           %[[FILL_3:.*]] = linalg.fill ins(%[[INDEX_CAST_4]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_5:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_3]], %[[FILL_3]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[GENERIC_3]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_13:.*]]: i32, %[[VAL_14:.*]]: i32, %[[VAL_15:.*]]: i32):
// CHECK:             %[[MULI_3:.*]] = arith.muli %[[VAL_13]], %[[VAL_14]] : i32
// CHECK:             linalg.yield %[[MULI_3]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_5:.*]] = arith.index_cast %[[INDEX_CAST_3]] : index to i32
// CHECK:           %[[FILL_4:.*]] = linalg.fill ins(%[[INDEX_CAST_5]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_6:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_4]], %[[FILL_4]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[GENERIC_4]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_16:.*]]: i32, %[[VAL_17:.*]]: i32, %[[VAL_18:.*]]: i32):
// CHECK:             %[[MULI_4:.*]] = arith.muli %[[VAL_16]], %[[VAL_17]] : i32
// CHECK:             linalg.yield %[[MULI_4]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_7:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_5]], %[[GENERIC_6]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[GENERIC_5]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_19:.*]]: i32, %[[VAL_20:.*]]: i32, %[[VAL_21:.*]]: i32):
// CHECK:             %[[ADDI_2:.*]] = arith.addi %[[VAL_19]], %[[VAL_20]] : i32
// CHECK:             linalg.yield %[[ADDI_2]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_6:.*]] = arith.index_cast %[[INDEX_CAST_1]] : index to i32
// CHECK:           %[[FILL_5:.*]] = linalg.fill ins(%[[INDEX_CAST_6]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_8:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[FILL_5]], %[[GENERIC_7]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[FILL_5]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_22:.*]]: i32, %[[VAL_23:.*]]: i32, %[[VAL_24:.*]]: i32):
// CHECK:             %[[ADDI_3:.*]] = arith.addi %[[VAL_22]], %[[VAL_23]] : i32
// CHECK:             linalg.yield %[[ADDI_3]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[COLLAPSE_SHAPE_0:.*]] = tensor.collapse_shape %[[GENERIC_8]] {{\[\[}}0, 1]] : tensor<16x1xi32> into tensor<16xi32>
// CHECK:           %[[INDEX_CAST_7:.*]] = arith.index_cast %[[MULI_0]] : i32 to index
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[INDEX_CAST_7]], %[[CONSTANT_1]] : index
// CHECK:           %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[MINSI_1:.*]] = arith.minsi %[[MAXSI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<16x16xf32>
// CHECK:           %[[MINSI_2:.*]] = arith.minsi %[[MINSI_1]], %[[CONSTANT_1]] : index
// CHECK:           scf.for %[[VAL_25:.*]] = %[[CONSTANT_0]] to %[[MINSI_2]] step %[[CONSTANT_3]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[COLLAPSE_SHAPE_0]]{{\[}}%[[VAL_25]]] : tensor<16xi32>
// CHECK:             %[[INDEX_CAST_8:.*]] = arith.index_cast %[[EXTRACT_0]] : i32 to index
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[ARG0]] to offset: {{\[}}%[[INDEX_CAST_8]]], sizes: [1, 16], strides: [1, 1] : memref<*xf32> to memref<1x16xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[SUBVIEW_0:.*]] = memref.subview %[[REINTERPRET_CAST_0]][0, 0] [1, 8] [1, 1] : memref<1x16xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[SUBVIEW_1:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_25]], 0] [1, 8] [1, 1] : memref<16x16xf32> to memref<1x8xf32, strided<[16, 1], offset: ?>>
// CHECK:             memref.copy %[[SUBVIEW_0]], %[[SUBVIEW_1]] : memref<1x8xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[16, 1], offset: ?>>
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<16x16xf32> to tensor<16x16xf32>
// CHECK:           %[[MULI_5:.*]] = arith.muli %[[EXTSI_0]], %[[ARG10]] : i64
// CHECK:           %[[EXTSI_1:.*]] = arith.extsi %[[ARG18]] : i32 to i64
// CHECK:           %[[MULI_6:.*]] = arith.muli %[[EXTSI_1]], %[[ARG12]] : i64
// CHECK:           %[[ADDI_4:.*]] = arith.addi %[[MULI_5]], %[[MULI_6]] : i64
// CHECK:           %[[INDEX_CAST_9:.*]] = arith.index_cast %[[ADDI_4]] : i64 to index
// CHECK:           %[[INDEX_CAST_10:.*]] = arith.index_cast %[[ARG9]] : i64 to index
// CHECK:           %[[INDEX_CAST_11:.*]] = arith.index_cast %[[ARG11]] : i64 to index
// CHECK:           %[[INDEX_CAST_12:.*]] = arith.index_cast %[[INDEX_CAST_10]] : index to i32
// CHECK:           %[[FILL_6:.*]] = linalg.fill ins(%[[INDEX_CAST_12]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_9:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_3]], %[[FILL_6]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[GENERIC_3]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_26:.*]]: i32, %[[VAL_27:.*]]: i32, %[[VAL_28:.*]]: i32):
// CHECK:             %[[MULI_7:.*]] = arith.muli %[[VAL_26]], %[[VAL_27]] : i32
// CHECK:             linalg.yield %[[MULI_7]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_13:.*]] = arith.index_cast %[[INDEX_CAST_11]] : index to i32
// CHECK:           %[[FILL_7:.*]] = linalg.fill ins(%[[INDEX_CAST_13]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_10:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_4]], %[[FILL_7]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[GENERIC_4]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_29:.*]]: i32, %[[VAL_30:.*]]: i32, %[[VAL_31:.*]]: i32):
// CHECK:             %[[MULI_8:.*]] = arith.muli %[[VAL_29]], %[[VAL_30]] : i32
// CHECK:             linalg.yield %[[MULI_8]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_11:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[GENERIC_9]], %[[GENERIC_10]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[GENERIC_9]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_32:.*]]: i32, %[[VAL_33:.*]]: i32, %[[VAL_34:.*]]: i32):
// CHECK:             %[[ADDI_5:.*]] = arith.addi %[[VAL_32]], %[[VAL_33]] : i32
// CHECK:             linalg.yield %[[ADDI_5]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[INDEX_CAST_14:.*]] = arith.index_cast %[[INDEX_CAST_9]] : index to i32
// CHECK:           %[[FILL_8:.*]] = linalg.fill ins(%[[INDEX_CAST_14]] : i32) outs(%[[EMPTY_0]] : tensor<16x1xi32>) -> tensor<16x1xi32>
// CHECK:           %[[GENERIC_12:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_1]], #[[$ATTR_1]]], iterator_types = ["parallel", "parallel"]} ins(%[[FILL_8]], %[[GENERIC_11]] : tensor<16x1xi32>, tensor<16x1xi32>) outs(%[[FILL_8]] : tensor<16x1xi32>) {
// CHECK:           ^bb0(%[[VAL_35:.*]]: i32, %[[VAL_36:.*]]: i32, %[[VAL_37:.*]]: i32):
// CHECK:             %[[ADDI_6:.*]] = arith.addi %[[VAL_35]], %[[VAL_36]] : i32
// CHECK:             linalg.yield %[[ADDI_6]] : i32
// CHECK:           } -> tensor<16x1xi32>
// CHECK:           %[[COLLAPSE_SHAPE_1:.*]] = tensor.collapse_shape %[[GENERIC_12]] {{\[\[}}0, 1]] : tensor<16x1xi32> into tensor<16xi32>
// CHECK:           scf.for %[[VAL_38:.*]] = %[[CONSTANT_0]] to %[[MINSI_2]] step %[[CONSTANT_3]] {
// CHECK:             %[[EXTRACT_1:.*]] = tensor.extract %[[COLLAPSE_SHAPE_1]]{{\[}}%[[VAL_38]]] : tensor<16xi32>
// CHECK:             %[[INDEX_CAST_15:.*]] = arith.index_cast %[[EXTRACT_1]] : i32 to index
// CHECK:             %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]]{{\[}}%[[VAL_38]], 0] [1, 8] [1, 1] : tensor<16x16xf32> to tensor<1x8xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: {{\[}}%[[INDEX_CAST_15]]], sizes: [1, 16], strides: [1, 1] : memref<*xf32> to memref<1x16xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[SUBVIEW_2:.*]] = memref.subview %[[REINTERPRET_CAST_1]][0, 0] [1, 8] [1, 1] : memref<1x16xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[CAST_0:.*]] = memref.cast %[[SUBVIEW_2]] : memref<1x8xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[?, ?], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[CAST_0]] : (tensor<1x8xf32>, memref<1x8xf32, strided<[?, ?], offset: ?>>) -> ()
// CHECK:           }
// CHECK:           return
// CHECK:         }
  tt.func public @row_gather2(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<f32>, %arg2: i32, %arg3: i32, %arg4: i32, %arg5: i32, %arg6: i64, %arg7: i64, %arg8: i64, %arg9: i64, %arg10: i64, %arg11: i64, %arg12: i64) attributes {noinline = false} {
    %cst = arith.constant dense<8> : tensor<1x16xi32>
    %cst_0 = arith.constant dense<8> : tensor<16x1xi32>
    %c8_i32 = arith.constant 8 : i32
    %0 = tt.get_program_id z : i32
    %1 = arith.muli %arg5, %c8_i32 : i32
    %2 = tt.make_range {end = 16 : i32, start = 0 : i32} : tensor<16xi32>
    %3 = tt.expand_dims %2 {axis = 1 : i32} : tensor<16xi32> -> tensor<16x1xi32>
    %4 = arith.remsi %3, %cst_0 : tensor<16x1xi32>
    %5 = arith.muli %arg3, %c8_i32 : i32
    %6 = tt.splat %5 : i32 -> tensor<16x1xi32>
    %7 = arith.addi %4, %6 : tensor<16x1xi32>
    %8 = arith.divsi %3, %cst_0 : tensor<16x1xi32>
    %9 = tt.splat %arg4 : i32 -> tensor<16x1xi32>
    %10 = arith.addi %8, %9 : tensor<16x1xi32>
    %11 = arith.extsi %arg2 : i32 to i64
    %12 = arith.muli %11, %arg7 : i64
    %13 = tt.addptr %arg0, %12 : !tt.ptr<f32>, i64
    %14 = arith.extsi %10 : tensor<16x1xi32> to tensor<16x1xi64>
    %15 = tt.splat %arg6 : i64 -> tensor<16x1xi64>
    %16 = arith.muli %14, %15 : tensor<16x1xi64>
    %17 = tt.splat %13 : !tt.ptr<f32> -> tensor<16x1x!tt.ptr<f32>>
    %18 = arith.extsi %7 : tensor<16x1xi32> to tensor<16x1xi64>
    %19 = tt.splat %arg8 : i64 -> tensor<16x1xi64>
    %20 = arith.muli %18, %19 : tensor<16x1xi64>
    %21 = arith.addi %16, %20 : tensor<16x1xi64>
    %22 = tt.addptr %17, %21 : tensor<16x1x!tt.ptr<f32>>, tensor<16x1xi64>
    %23 = tt.expand_dims %2 {axis = 0 : i32} : tensor<16xi32> -> tensor<1x16xi32>
    %24 = tt.broadcast %22 : tensor<16x1x!tt.ptr<f32>> -> tensor<16x16x!tt.ptr<f32>>
    %25 = tt.broadcast %23 : tensor<1x16xi32> -> tensor<16x16xi32>
    %26 = tt.addptr %24, %25 : tensor<16x16x!tt.ptr<f32>>, tensor<16x16xi32>
    %27 = arith.cmpi slt, %23, %cst : tensor<1x16xi32>
    %28 = tt.splat %1 : i32 -> tensor<16x1xi32>
    %29 = arith.cmpi slt, %3, %28 : tensor<16x1xi32>
    %30 = tt.broadcast %27 : tensor<1x16xi1> -> tensor<16x16xi1>
    %31 = tt.broadcast %29 : tensor<16x1xi1> -> tensor<16x16xi1>
    %32 = arith.andi %30, %31 : tensor<16x16xi1>
    %33 = tt.load %26, %32 : tensor<16x16x!tt.ptr<f32>>
    %34 = arith.muli %11, %arg10 : i64
    %35 = arith.extsi %0 : i32 to i64
    %36 = arith.muli %35, %arg12 : i64
    %37 = arith.addi %34, %36 : i64
    %38 = tt.addptr %arg1, %37 : !tt.ptr<f32>, i64
    %39 = tt.splat %arg9 : i64 -> tensor<16x1xi64>
    %40 = arith.muli %14, %39 : tensor<16x1xi64>
    %41 = tt.splat %38 : !tt.ptr<f32> -> tensor<16x1x!tt.ptr<f32>>
    %42 = tt.splat %arg11 : i64 -> tensor<16x1xi64>
    %43 = arith.muli %18, %42 : tensor<16x1xi64>
    %44 = arith.addi %40, %43 : tensor<16x1xi64>
    %45 = tt.addptr %41, %44 : tensor<16x1x!tt.ptr<f32>>, tensor<16x1xi64>
    %46 = tt.broadcast %45 : tensor<16x1x!tt.ptr<f32>> -> tensor<16x16x!tt.ptr<f32>>
    %47 = tt.addptr %46, %25 : tensor<16x16x!tt.ptr<f32>>, tensor<16x16xi32>
    tt.store %47, %33, %32 : tensor<16x16x!tt.ptr<f32>>
    tt.return
  }
}
