// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt  --structured-to-memref --canonicalize --cse %s | FileCheck %s



// CHECK-LABEL:   tt.func public @row_gather(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant dense<5> : tensor<8xi32>
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant dense<3> : tensor<8xi32>
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 8 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant dense<8> : tensor<8xi32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: [0], sizes: [8], strides: [1] : memref<*xi32> to memref<8xi32, strided<[1]>>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<8xi32>
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<8xi32, strided<[1]>> to memref<8xi32>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<8xi32> to tensor<8xi32>
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[TO_TENSOR_0]], %[[CONSTANT_3]] : tensor<8xi32>
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[MULI_0]], %[[CONSTANT_2]] : tensor<8xi32>
// CHECK:           %[[MULI_1:.*]] = arith.muli %[[REMSI_0]], %[[CONSTANT_5]] : tensor<8xi32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_1:.*]] = memref.alloc() : memref<8x8xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_1]] to %[[CONSTANT_4]] step %[[CONSTANT_0]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[MULI_1]]{{\[}}%[[VAL_0]]] : tensor<8xi32>
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[EXTRACT_0]] : i32 to index
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [1, 8], strides: [1, 1] : memref<*xf32> to memref<1x8xf32, strided<[1, 1], offset: ?>>
// CHECK:             %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_1]]{{\[}}%[[VAL_0]], 0] [1, 8] [1, 1] : memref<8x8xf32> to memref<1x8xf32, strided<[8, 1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_1]], %[[SUBVIEW_0]] : memref<1x8xf32, strided<[1, 1], offset: ?>> to memref<1x8xf32, strided<[8, 1], offset: ?>>
// CHECK:           }
// CHECK:           %[[TO_TENSOR_1:.*]] = bufferization.to_tensor %[[ALLOC_1]] restrict writable : memref<8x8xf32> to tensor<8x8xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_2:.*]] = builtin.unrealized_conversion_cast %[[ARG2]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[REINTERPRET_CAST_2:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_2]] to offset: [0], sizes: [8, 8], strides: [8, 1] : memref<*xf32> to memref<8x8xf32, strided<[8, 1]>>
// CHECK:           bufferization.materialize_in_destination %[[TO_TENSOR_1]] in writable %[[REINTERPRET_CAST_2]] : (tensor<8x8xf32>, memref<8x8xf32, strided<[8, 1]>>) -> ()
// CHECK:           tt.return
// CHECK:         }
module {
  tt.func public @row_gather(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<i32>, %arg2: !tt.ptr<f32>) attributes {noinline = false} {
    %cst = arith.constant dense<8> : tensor<8xi32>
    %c8 = arith.constant 8 : index
    %cst_0 = arith.constant dense<3> : tensor<8xi32>
    %cst_1 = arith.constant dense<5> : tensor<8xi32>
    %0 = tts.make_tptr %arg1 to sizes: [8], strides: [1], offsets: [0], shape: [0], order: [] : <i32> to tensor<8x!tt.ptr<i32>>
    %1 = "tts.load"(%0) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<8x!tt.ptr<i32>>) -> tensor<8xi32>
    %2 = arith.muli %1, %cst_0 : tensor<8xi32>
    %3 = arith.remsi %2, %cst_1 : tensor<8xi32>
    %4 = arith.muli %3, %cst : tensor<8xi32>
    %5 = tts.make_gather_scatter_tptr %arg0 to sizes: [8, 8] gather_scatter_dim: 0 gather_scatter_offset: %4, strides: [1, 1], offsets: [0, 0] : tensor<8xi32> <f32> to tensor<8x8x!tt.ptr<f32>>
    %6 = "tts.load"(%5) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<8x8x!tt.ptr<f32>>) -> tensor<8x8xf32>
    %7 = tts.make_tptr %arg2 to sizes: [8, 8], strides: [%c8, 1], offsets: [0, 0], shape: [0, 0], order: [] : <f32> to tensor<8x8x!tt.ptr<f32>>
    "tts.store"(%7, %6) <{static_mask_dims = array<i64>}> : (tensor<8x8x!tt.ptr<f32>>, tensor<8x8xf32>) -> ()
    tt.return
  }
}
