// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/

// RUN: triton-shared-opt --triton-to-linalg-experimental %s | FileCheck %s

// Make sure extract_slice is generated correctly.



module {
// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>
// CHECK-LABEL:   func.func @row_gather3(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xi32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG10:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG11:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 32 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 1 : index
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: [0], sizes: [32], strides: [1] : memref<*xi32> to memref<32xi32, strided<[1]>>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<32xi32>
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<32xi32, strided<[1]>> to memref<32xi32>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<32xi32> to tensor<32xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG3]] : i32 to index
// CHECK:           %[[EMPTY_0:.*]] = tensor.empty() : tensor<32xi32>
// CHECK:           %[[FILL_0:.*]] = linalg.fill ins(%[[ARG4]] : i32) outs(%[[EMPTY_0]] : tensor<32xi32>) -> tensor<32xi32>
// CHECK:           %[[GENERIC_0:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[TO_TENSOR_0]], %[[FILL_0]] : tensor<32xi32>, tensor<32xi32>) outs(%[[TO_TENSOR_0]] : tensor<32xi32>) {
// CHECK:           ^bb0(%[[VAL_0:.*]]: i32, %[[VAL_1:.*]]: i32, %[[VAL_2:.*]]: i32):
// CHECK:             %[[MULI_0:.*]] = arith.muli %[[VAL_0]], %[[VAL_1]] : i32
// CHECK:             linalg.yield %[[MULI_0]] : i32
// CHECK:           } -> tensor<32xi32>
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG5]] : i32 to index
// CHECK:           %[[ALLOC_1:.*]] = memref.alloc() : memref<32x32x32xf32>
// CHECK:           scf.for %[[VAL_3:.*]] = %[[CONSTANT_0]] to %[[CONSTANT_1]] step %[[CONSTANT_2]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[GENERIC_0]]{{\[}}%[[VAL_3]]] : tensor<32xi32>
// CHECK:             %[[INDEX_CAST_2:.*]] = arith.index_cast %[[EXTRACT_0]] : i32 to index
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[ARG0]] to offset: {{\[}}%[[INDEX_CAST_2]]], sizes: [32, 1, 32], strides: {{\[}}%[[INDEX_CAST_0]], 1, %[[INDEX_CAST_1]]] : memref<*xf32> to memref<32x1x32xf32, strided<[?, 1, ?], offset: ?>>
// CHECK:             %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_1]][0, %[[VAL_3]], 0] [32, 1, 32] [1, 1, 1] : memref<32x32x32xf32> to memref<32x1x32xf32, strided<[1024, 32, 1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_1]], %[[SUBVIEW_0]] : memref<32x1x32xf32, strided<[?, 1, ?], offset: ?>> to memref<32x1x32xf32, strided<[1024, 32, 1], offset: ?>>
// CHECK:           }
// CHECK:           %[[TO_TENSOR_1:.*]] = bufferization.to_tensor %[[ALLOC_1]] restrict writable : memref<32x32x32xf32> to tensor<32x32x32xf32>
// CHECK:           scf.for %[[VAL_4:.*]] = %[[CONSTANT_0]] to %[[CONSTANT_1]] step %[[CONSTANT_2]] {
// CHECK:             %[[EXTRACT_1:.*]] = tensor.extract %[[GENERIC_0]]{{\[}}%[[VAL_4]]] : tensor<32xi32>
// CHECK:             %[[INDEX_CAST_3:.*]] = arith.index_cast %[[EXTRACT_1]] : i32 to index
// CHECK:             %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_1]][0, %[[VAL_4]], 0] [32, 1, 32] [1, 1, 1] : tensor<32x32x32xf32> to tensor<32x1x32xf32>
// CHECK:             %[[REINTERPRET_CAST_2:.*]] = memref.reinterpret_cast %[[ARG2]] to offset: {{\[}}%[[INDEX_CAST_3]]], sizes: [32, 1, 32], strides: {{\[}}%[[INDEX_CAST_0]], 1, %[[INDEX_CAST_1]]] : memref<*xf32> to memref<32x1x32xf32, strided<[?, 1, ?], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_2]] : (tensor<32x1x32xf32>, memref<32x1x32xf32, strided<[?, 1, ?], offset: ?>>) -> ()
// CHECK:           }
// CHECK:           return
// CHECK:         }
  tt.func public @row_gather3(%arg0: !tt.ptr<f32>, %arg1: !tt.ptr<i32>, %arg2: !tt.ptr<f32>, %arg3: i32, %arg4: i32, %arg5: i32) attributes {noinline = false} {
    %0 = tts.make_tptr %arg1 to sizes: [32], strides: [1], offsets: [0], shape: [0], order: [] : <i32> to tensor<32x!tt.ptr<i32>>
    %1 = "tts.load"(%0) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<32x!tt.ptr<i32>>) -> tensor<32xi32>
    %2 = arith.index_cast %arg3 : i32 to index
    %3 = tt.splat %arg4 : i32 -> tensor<32xi32>
    %4 = arith.muli %1, %3 : tensor<32xi32>
    %5 = arith.index_cast %arg5 : i32 to index
    %6 = tts.make_gather_scatter_tptr %arg0 to sizes: [32, 32, 32] gather_scatter_dim: 1 gather_scatter_offset: %4, strides: [%2, 1, %5], offsets: [0, 0, 0] : tensor<32xi32> <f32> to tensor<32x32x32x!tt.ptr<f32>>
    %7 = "tts.load"(%6) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<32x32x32x!tt.ptr<f32>>) -> tensor<32x32x32xf32>
    %8 = arith.index_cast %arg3 : i32 to index
    %9 = tt.splat %arg4 : i32 -> tensor<32xi32>
    %10 = arith.muli %1, %9 : tensor<32xi32>
    %11 = arith.index_cast %arg5 : i32 to index
    %12 = tts.make_gather_scatter_tptr %arg2 to sizes: [32, 32, 32] gather_scatter_dim: 1 gather_scatter_offset: %10, strides: [%8, 1, %11], offsets: [0, 0, 0] : tensor<32xi32> <f32> to tensor<32x32x32x!tt.ptr<f32>>
    "tts.store"(%12, %7) <{static_mask_dims = array<i64>}> : (tensor<32x32x32x!tt.ptr<f32>>, tensor<32x32x32xf32>) -> ()
    tt.return
  }
}
