// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --split-input-file --triton-to-linalg-experimental="structured-ldst-mode=tensor-first-vector-cpu" %s | FileCheck %s

module {
// CHECK-LABEL:   func.func @masked_sum_rank1(
// CHECK-SAME:  %[[VAL_0:.*]]: memref<*xf32>, %[[VAL_1:.*]]: memref<*xf32>, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32) {
// CHECK:           %[[VAL_9:.*]] = arith.constant 128 : index
// CHECK:           %[[VAL_10:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_11:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[VAL_12:.*]] = arith.constant 1 : index
// CHECK:           %[[VAL_13:.*]] = arith.constant 16 : index
// CHECK:           %[[VAL_14:.*]] = arith.index_cast %[[VAL_2]] : i32 to index
// CHECK:           %[[VAL_15:.*]] = arith.minsi %[[VAL_14]], %[[VAL_9]] : index
// CHECK:           %[[VAL_16:.*]] = arith.maxsi %[[VAL_15]], %[[VAL_10]] : index
// CHECK:           %[[VAL_17:.*]] = bufferization.alloc_tensor() : tensor<f32>
// CHECK:           %[[VAL_18:.*]] = memref.reinterpret_cast %[[VAL_0]] to offset: [0], sizes: [128], strides: [1] : memref<*xf32> to memref<128xf32, strided<[1]>>
// CHECK:           %[[VAL_19:.*]] = arith.divui %[[VAL_16]], %[[VAL_13]] : index
// CHECK:           %[[VAL_20:.*]] = arith.muli %[[VAL_19]], %[[VAL_13]] : index
// CHECK:           %[[VAL_21:.*]] = scf.for %[[VAL_22:.*]] = %[[VAL_10]] to %[[VAL_20]] step %[[VAL_13]] iter_args(%[[VAL_23:.*]] = %[[VAL_11]]) -> (f32) {
// CHECK:             %[[VAL_24:.*]] = vector.load %[[VAL_18]]{{\[}}%[[VAL_22]]] : memref<128xf32, strided<[1]>>, vector<16xf32>
// CHECK:             %[[VAL_25:.*]] = vector.reduction <add>, %[[VAL_24]], %[[VAL_23]] : vector<16xf32> into f32
// CHECK:             scf.yield %[[VAL_25]] : f32
// CHECK:           }
// CHECK:           %[[VAL_26:.*]] = scf.for %[[VAL_27:.*]] = %[[VAL_20]] to %[[VAL_16]] step %[[VAL_12]] iter_args(%[[VAL_28:.*]] = %[[VAL_21]]) -> (f32) {
// CHECK:             %[[VAL_29:.*]] = memref.load %[[VAL_18]]{{\[}}%[[VAL_27]]] : memref<128xf32, strided<[1]>>
// CHECK:             %[[VAL_30:.*]] = arith.addf %[[VAL_29]], %[[VAL_28]] : f32
// CHECK:             scf.yield %[[VAL_30]] : f32
// CHECK:           }
// CHECK:           %[[VAL_31:.*]] = scf.for %[[VAL_32:.*]] = %[[VAL_16]] to %[[VAL_9]] step %[[VAL_12]] iter_args(%[[VAL_33:.*]] = %[[VAL_26]]) -> (f32) {
// CHECK:             %[[VAL_34:.*]] = arith.addf %[[VAL_33]], %[[VAL_11]] : f32
// CHECK:             scf.yield %[[VAL_34]] : f32
// CHECK:           }
// CHECK:           %[[VAL_35:.*]] = memref.reinterpret_cast %[[VAL_1]] to offset: [0], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1]>>
// CHECK:           affine.store %[[VAL_31]], %[[VAL_35]][0] : memref<1xf32, strided<[1]>>
// CHECK:           return
// CHECK:         }
  tt.func @masked_sum_rank1(%in : !tt.ptr<f32>, %out : !tt.ptr<f32>, %n : i32) {
    %cst = arith.constant 0.000000e+00 : f32
    %0 = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32>
    %1 = tt.splat %in : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>>
    %2 = tt.addptr %1, %0 : tensor<128x!tt.ptr<f32>>, tensor<128xi32>
    %3 = tt.splat %n : i32 -> tensor<128xi32>
    %4 = arith.cmpi slt, %0, %3 : tensor<128xi32>
    %5 = tt.splat %cst : f32 -> tensor<128xf32>
    %6 = tt.load %2, %4, %5 : tensor<128x!tt.ptr<f32>>
    %7 = "tt.reduce"(%6) ({
    ^bb0(%arg0: f32, %arg1: f32):
      %8 = arith.addf %arg0, %arg1 : f32
      tt.reduce.return %8 : f32
    }) {axis = 0 : i32} : (tensor<128xf32>) -> f32
    tt.store %out, %7 : !tt.ptr<f32>
    tt.return
  }
}


// -----

module {
// CHECK-LABEL:   func.func @masked_max_rank1(
// CHECK-SAME:  %[[VAL_0:.*]]: memref<*xf32>, %[[VAL_1:.*]]: memref<*xf32>, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32) {
// CHECK:           %[[VAL_9:.*]] = arith.constant 128 : index
// CHECK:           %[[VAL_10:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_11:.*]] = arith.constant 0xFF800000 : f32
// CHECK:           %[[VAL_12:.*]] = arith.constant 1 : index
// CHECK:           %[[VAL_13:.*]] = arith.constant 16 : index
// CHECK:           %[[VAL_14:.*]] = arith.index_cast %[[VAL_2]] : i32 to index
// CHECK:           %[[VAL_15:.*]] = arith.minsi %[[VAL_14]], %[[VAL_9]] : index
// CHECK:           %[[VAL_16:.*]] = arith.maxsi %[[VAL_15]], %[[VAL_10]] : index
// CHECK:           %[[VAL_17:.*]] = bufferization.alloc_tensor() : tensor<f32>
// CHECK:           %[[VAL_18:.*]] = memref.reinterpret_cast %[[VAL_0]] to offset: [0], sizes: [128], strides: [1] : memref<*xf32> to memref<128xf32, strided<[1]>>
// CHECK:           %[[VAL_19:.*]] = arith.divui %[[VAL_16]], %[[VAL_13]] : index
// CHECK:           %[[VAL_20:.*]] = arith.muli %[[VAL_19]], %[[VAL_13]] : index
// CHECK:           %[[VAL_21:.*]] = scf.for %[[VAL_22:.*]] = %[[VAL_10]] to %[[VAL_20]] step %[[VAL_13]] iter_args(%[[VAL_23:.*]] = %[[VAL_11]]) -> (f32) {
// CHECK:             %[[VAL_24:.*]] = vector.load %[[VAL_18]]{{\[}}%[[VAL_22]]] : memref<128xf32, strided<[1]>>, vector<16xf32>
// CHECK:             %[[VAL_25:.*]] = vector.reduction <maxnumf>, %[[VAL_24]], %[[VAL_23]] : vector<16xf32> into f32
// CHECK:             scf.yield %[[VAL_25]] : f32
// CHECK:           }
// CHECK:           %[[VAL_26:.*]] = scf.for %[[VAL_27:.*]] = %[[VAL_20]] to %[[VAL_16]] step %[[VAL_12]] iter_args(%[[VAL_28:.*]] = %[[VAL_21]]) -> (f32) {
// CHECK:             %[[VAL_29:.*]] = memref.load %[[VAL_18]]{{\[}}%[[VAL_27]]] : memref<128xf32, strided<[1]>>
// CHECK:             %[[VAL_30:.*]] = arith.maxnumf %[[VAL_29]], %[[VAL_28]] : f32
// CHECK:             scf.yield %[[VAL_30]] : f32
// CHECK:           }
// CHECK:           %[[VAL_31:.*]] = scf.for %[[VAL_32:.*]] = %[[VAL_16]] to %[[VAL_9]] step %[[VAL_12]] iter_args(%[[VAL_33:.*]] = %[[VAL_26]]) -> (f32) {
// CHECK:             %[[VAL_34:.*]] = arith.maxnumf %[[VAL_33]], %[[VAL_11]] : f32
// CHECK:             scf.yield %[[VAL_34]] : f32
// CHECK:           }
// CHECK:           %[[VAL_35:.*]] = memref.reinterpret_cast %[[VAL_1]] to offset: [0], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1]>>
// CHECK:           affine.store %[[VAL_31]], %[[VAL_35]][0] : memref<1xf32, strided<[1]>>
// CHECK:           return
// CHECK:         }
  tt.func @masked_max_rank1(%in : !tt.ptr<f32>, %out : !tt.ptr<f32>, %n : i32) {
    %cst = arith.constant 0xFF800000 : f32
    %0 = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32>
    %1 = tt.splat %in : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>>
    %2 = tt.addptr %1, %0 : tensor<128x!tt.ptr<f32>>, tensor<128xi32>
    %3 = tt.splat %n : i32 -> tensor<128xi32>
    %4 = arith.cmpi slt, %0, %3 : tensor<128xi32>
    %5 = tt.splat %cst : f32 -> tensor<128xf32>
    %6 = tt.load %2, %4, %5 : tensor<128x!tt.ptr<f32>>
    %7 = "tt.reduce"(%6) ({
    ^bb0(%arg0: f32, %arg1: f32):
      %8 = arith.maxnumf %arg0, %arg1 : f32
      tt.reduce.return %8 : f32
    }) {axis = 0 : i32} : (tensor<128xf32>) -> f32
    tt.store %out, %7 : !tt.ptr<f32>
    tt.return
  }
}


// -----

module {
// CHECK-LABEL:   func.func @masked_mul_rank1_fallback(
// CHECK-SAME:  %[[VAL_0:.*]]: memref<*xf32>, %[[VAL_1:.*]]: memref<*xf32>, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32) {
// CHECK:           %[[VAL_9:.*]] = arith.constant 16 : index
// CHECK:           %[[VAL_10:.*]] = arith.constant 1 : index
// CHECK:           %[[VAL_11:.*]] = arith.constant 128 : index
// CHECK:           %[[VAL_12:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_13:.*]] = arith.constant 1.000000e+00 : f32
// CHECK:           %[[VAL_14:.*]] = arith.index_cast %[[VAL_2]] : i32 to index
// CHECK:           %[[VAL_15:.*]] = arith.minsi %[[VAL_14]], %[[VAL_11]] : index
// CHECK:           %[[VAL_16:.*]] = arith.maxsi %[[VAL_15]], %[[VAL_12]] : index
// CHECK:           %[[VAL_17:.*]] = memref.reinterpret_cast %[[VAL_0]] to offset: [0], sizes: [128], strides: [1] : memref<*xf32> to memref<128xf32, strided<[1]>>
// CHECK:           %[[VAL_18:.*]] = memref.alloc() : memref<128xf32>
// CHECK:           %[[VAL_19:.*]] = arith.cmpi slt, %[[VAL_16]], %[[VAL_11]] : index
// CHECK:           scf.if %[[VAL_19]] {
// CHECK:             linalg.fill ins(%[[VAL_13]] : f32) outs(%[[VAL_18]] : memref<128xf32>)
// CHECK:           }
// CHECK:           %[[VAL_20:.*]] = memref.subview %[[VAL_17]][0] {{\[}}%[[VAL_16]]] [1] : memref<128xf32, strided<[1]>> to memref<?xf32, strided<[1]>>
// CHECK:           %[[VAL_21:.*]] = memref.subview %[[VAL_18]][0] {{\[}}%[[VAL_16]]] [1] : memref<128xf32> to memref<?xf32, strided<[1]>>
// CHECK:           %[[VAL_22:.*]] = arith.divui %[[VAL_16]], %[[VAL_9]] : index
// CHECK:           %[[VAL_23:.*]] = arith.muli %[[VAL_22]], %[[VAL_9]] : index
// CHECK:           scf.for %[[VAL_24:.*]] = %[[VAL_12]] to %[[VAL_23]] step %[[VAL_9]] {
// CHECK:             %[[VAL_25:.*]] = vector.load %[[VAL_20]]{{\[}}%[[VAL_24]]] : memref<?xf32, strided<[1]>>, vector<16xf32>
// CHECK:             vector.store %[[VAL_25]], %[[VAL_21]]{{\[}}%[[VAL_24]]] : memref<?xf32, strided<[1]>>, vector<16xf32>
// CHECK:           }
// CHECK:           scf.for %[[VAL_26:.*]] = %[[VAL_23]] to %[[VAL_16]] step %[[VAL_10]] {
// CHECK:             %[[VAL_27:.*]] = memref.load %[[VAL_20]]{{\[}}%[[VAL_26]]] : memref<?xf32, strided<[1]>>
// CHECK:             memref.store %[[VAL_27]], %[[VAL_21]]{{\[}}%[[VAL_26]]] : memref<?xf32, strided<[1]>>
// CHECK:           }
// CHECK:           %[[VAL_28:.*]] = bufferization.to_tensor %[[VAL_18]] restrict writable : memref<128xf32> to tensor<128xf32>
// CHECK:           %[[VAL_29:.*]] = bufferization.alloc_tensor() : tensor<f32>
// CHECK:           %[[VAL_30:.*]] = tensor.insert %[[VAL_13]] into %[[VAL_29]][] : tensor<f32>
// CHECK:           %[[VAL_31:.*]] = linalg.reduce ins(%[[VAL_28]] : tensor<128xf32>) outs(%[[VAL_30]] : tensor<f32>) dimensions = [0]
// CHECK:             (%[[VAL_32:.*]]: f32, %[[VAL_33:.*]]: f32) {
// CHECK:               %[[VAL_34:.*]] = arith.mulf %[[VAL_32]], %[[VAL_33]] : f32
// CHECK:               linalg.yield %[[VAL_34]] : f32
// CHECK:             }
// CHECK:           %[[VAL_35:.*]] = tensor.extract %[[VAL_31]][] : tensor<f32>
// CHECK:           %[[VAL_36:.*]] = memref.reinterpret_cast %[[VAL_1]] to offset: [0], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1]>>
// CHECK:           affine.store %[[VAL_35]], %[[VAL_36]][0] : memref<1xf32, strided<[1]>>
// CHECK:           return
// CHECK:         }
// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0) -> (d0)>
// CHECK: #[[$ATTR_1:.+]] = affine_map<(d0, d1) -> (d0, 0)>
// CHECK: #[[$ATTR_2:.+]] = affine_map<(d0, d1) -> (d0, d1)>
// CHECK: #[[$ATTR_3:.+]] = affine_map<(d0, d1) -> (0, d1)>
  tt.func @masked_mul_rank1_fallback(%in : !tt.ptr<f32>, %out : !tt.ptr<f32>, %n : i32) {
    %cst = arith.constant 1.000000e+00 : f32
    %0 = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32>
    %1 = tt.splat %in : !tt.ptr<f32> -> tensor<128x!tt.ptr<f32>>
    %2 = tt.addptr %1, %0 : tensor<128x!tt.ptr<f32>>, tensor<128xi32>
    %3 = tt.splat %n : i32 -> tensor<128xi32>
    %4 = arith.cmpi slt, %0, %3 : tensor<128xi32>
    %5 = tt.splat %cst : f32 -> tensor<128xf32>
    %6 = tt.load %2, %4, %5 : tensor<128x!tt.ptr<f32>>
    %7 = "tt.reduce"(%6) ({
    ^bb0(%arg0: f32, %arg1: f32):
      %8 = arith.mulf %arg0, %arg1 : f32
      tt.reduce.return %8 : f32
    }) {axis = 0 : i32} : (tensor<128xf32>) -> f32
    tt.store %out, %7 : !tt.ptr<f32>
    tt.return
  }
}


// -----

module {
// CHECK-LABEL:   func.func @masked_sum_rank2_fallback(
// CHECK-SAME:  %[[VAL_0:.*]]: memref<*xf32>, %[[VAL_1:.*]]: memref<*xf32>, %[[VAL_2:.*]]: i32, %[[VAL_3:.*]]: i32, %[[VAL_4:.*]]: i32, %[[VAL_5:.*]]: i32, %[[VAL_6:.*]]: i32, %[[VAL_7:.*]]: i32, %[[VAL_8:.*]]: i32, %[[VAL_9:.*]]: i32) {
// CHECK:           %[[VAL_10:.*]] = arith.constant 1 : index
// CHECK:           %[[VAL_11:.*]] = arith.constant 0 : index
// CHECK:           %[[VAL_12:.*]] = arith.constant 8 : index
// CHECK:           %[[VAL_13:.*]] = arith.constant 4 : index
// CHECK:           %[[VAL_14:.*]] = arith.constant 0 : i32
// CHECK:           %[[VAL_15:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[VAL_16:.*]] = arith.constant 8 : i32
// CHECK:           %[[VAL_17:.*]] = tensor.empty() : tensor<4xi32>
// CHECK:           %[[VAL_18:.*]] = linalg.fill ins(%[[VAL_14]] : i32) outs(%[[VAL_17]] : tensor<4xi32>) -> tensor<4xi32>
// CHECK:           %[[VAL_19:.*]] = tensor.empty() : tensor<4x8xi32>
// CHECK:           %[[VAL_20:.*]] = linalg.fill ins(%[[VAL_16]] : i32) outs(%[[VAL_19]] : tensor<4x8xi32>) -> tensor<4x8xi32>
// CHECK:           %[[VAL_21:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[VAL_17]] : tensor<4xi32>) {
// CHECK:           ^bb0(%[[VAL_22:.*]]: i32):
// CHECK:             %[[VAL_23:.*]] = linalg.index 0 : index
// CHECK:             %[[VAL_24:.*]] = arith.index_cast %[[VAL_23]] : index to i32
// CHECK:             linalg.yield %[[VAL_24]] : i32
// CHECK:           } -> tensor<4xi32>
// CHECK:           %[[VAL_25:.*]] = tensor.expand_shape %[[VAL_21]] {{\[\[}}0, 1]] output_shape [4, 1] : tensor<4xi32> into tensor<4x1xi32>
// CHECK:           %[[VAL_26:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_1]], #[[$ATTR_2]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_25]] : tensor<4x1xi32>) outs(%[[VAL_19]] : tensor<4x8xi32>) attrs =  {broadcastDims = array<i64: 1>} {
// CHECK:           ^bb0(%[[VAL_27:.*]]: i32, %[[VAL_28:.*]]: i32):
// CHECK:             linalg.yield %[[VAL_27]] : i32
// CHECK:           } -> tensor<4x8xi32>
// CHECK:           %[[VAL_29:.*]] = tensor.empty() : tensor<8xi32>
// CHECK:           %[[VAL_30:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]]], iterator_types = ["parallel"]} outs(%[[VAL_29]] : tensor<8xi32>) {
// CHECK:           ^bb0(%[[VAL_31:.*]]: i32):
// CHECK:             %[[VAL_32:.*]] = linalg.index 0 : index
// CHECK:             %[[VAL_33:.*]] = arith.index_cast %[[VAL_32]] : index to i32
// CHECK:             linalg.yield %[[VAL_33]] : i32
// CHECK:           } -> tensor<8xi32>
// CHECK:           %[[VAL_34:.*]] = tensor.expand_shape %[[VAL_30]] {{\[\[}}0, 1]] output_shape [1, 8] : tensor<8xi32> into tensor<1x8xi32>
// CHECK:           %[[VAL_35:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_3]], #[[$ATTR_2]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_34]] : tensor<1x8xi32>) outs(%[[VAL_19]] : tensor<4x8xi32>) attrs =  {broadcastDims = array<i64: 0>} {
// CHECK:           ^bb0(%[[VAL_36:.*]]: i32, %[[VAL_37:.*]]: i32):
// CHECK:             linalg.yield %[[VAL_36]] : i32
// CHECK:           } -> tensor<4x8xi32>
// CHECK:           %[[VAL_38:.*]] = linalg.fill ins(%[[VAL_3]] : i32) outs(%[[VAL_19]] : tensor<4x8xi32>) -> tensor<4x8xi32>
// CHECK:           %[[VAL_39:.*]] = tensor.empty() : tensor<4x8xi1>
// CHECK:           %[[VAL_40:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_2]], #[[$ATTR_2]], #[[$ATTR_2]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_35]], %[[VAL_38]] : tensor<4x8xi32>, tensor<4x8xi32>) outs(%[[VAL_39]] : tensor<4x8xi1>) {
// CHECK:           ^bb0(%[[VAL_41:.*]]: i32, %[[VAL_42:.*]]: i32, %[[VAL_43:.*]]: i1):
// CHECK:             %[[VAL_44:.*]] = arith.cmpi slt, %[[VAL_41]], %[[VAL_42]] : i32
// CHECK:             linalg.yield %[[VAL_44]] : i1
// CHECK:           } -> tensor<4x8xi1>
// CHECK:           %[[VAL_45:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_2]], #[[$ATTR_2]], #[[$ATTR_2]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_26]], %[[VAL_20]] : tensor<4x8xi32>, tensor<4x8xi32>) outs(%[[VAL_26]] : tensor<4x8xi32>) {
// CHECK:           ^bb0(%[[VAL_46:.*]]: i32, %[[VAL_47:.*]]: i32, %[[VAL_48:.*]]: i32):
// CHECK:             %[[VAL_49:.*]] = arith.muli %[[VAL_46]], %[[VAL_47]] : i32
// CHECK:             linalg.yield %[[VAL_49]] : i32
// CHECK:           } -> tensor<4x8xi32>
// CHECK:           %[[VAL_50:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_2]], #[[$ATTR_2]], #[[$ATTR_2]]], iterator_types = ["parallel", "parallel"]} ins(%[[VAL_45]], %[[VAL_35]] : tensor<4x8xi32>, tensor<4x8xi32>) outs(%[[VAL_45]] : tensor<4x8xi32>) {
// CHECK:           ^bb0(%[[VAL_51:.*]]: i32, %[[VAL_52:.*]]: i32, %[[VAL_53:.*]]: i32):
// CHECK:             %[[VAL_54:.*]] = arith.addi %[[VAL_51]], %[[VAL_52]] : i32
// CHECK:             linalg.yield %[[VAL_54]] : i32
// CHECK:           } -> tensor<4x8xi32>
// CHECK:           %[[VAL_55:.*]] = memref.cast %[[VAL_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           %[[VAL_56:.*]] = tensor.empty() : tensor<4x8xf32>
// CHECK:           %[[VAL_57:.*]] = scf.for %[[VAL_58:.*]] = %[[VAL_11]] to %[[VAL_13]] step %[[VAL_10]] iter_args(%[[VAL_59:.*]] = %[[VAL_56]]) -> (tensor<4x8xf32>) {
// CHECK:             %[[VAL_60:.*]] = scf.for %[[VAL_61:.*]] = %[[VAL_11]] to %[[VAL_12]] step %[[VAL_10]] iter_args(%[[VAL_62:.*]] = %[[VAL_59]]) -> (tensor<4x8xf32>) {
// CHECK:               %[[VAL_63:.*]] = tensor.extract %[[VAL_50]]{{\[}}%[[VAL_58]], %[[VAL_61]]] : tensor<4x8xi32>
// CHECK:               %[[VAL_64:.*]] = arith.index_cast %[[VAL_63]] : i32 to index
// CHECK:               %[[VAL_65:.*]] = memref.load %[[VAL_55]]{{\[}}%[[VAL_64]]] : memref<?xf32>
// CHECK:               %[[VAL_66:.*]] = tensor.extract %[[VAL_40]]{{\[}}%[[VAL_58]], %[[VAL_61]]] : tensor<4x8xi1>
// CHECK:               %[[VAL_67:.*]] = arith.select %[[VAL_66]], %[[VAL_65]], %[[VAL_15]] : f32
// CHECK:               %[[VAL_68:.*]] = tensor.insert %[[VAL_67]] into %[[VAL_62]]{{\[}}%[[VAL_58]], %[[VAL_61]]] : tensor<4x8xf32>
// CHECK:               scf.yield %[[VAL_68]] : tensor<4x8xf32>
// CHECK:             }
// CHECK:             scf.yield %[[VAL_60]] : tensor<4x8xf32>
// CHECK:           }
// CHECK:           %[[VAL_69:.*]] = tensor.empty() : tensor<4xf32>
// CHECK:           %[[VAL_70:.*]] = linalg.fill ins(%[[VAL_15]] : f32) outs(%[[VAL_69]] : tensor<4xf32>) -> tensor<4xf32>
// CHECK:           %[[VAL_71:.*]] = linalg.reduce ins(%[[VAL_57]] : tensor<4x8xf32>) outs(%[[VAL_70]] : tensor<4xf32>) dimensions = [1]
// CHECK:             (%[[VAL_72:.*]]: f32, %[[VAL_73:.*]]: f32) {
// CHECK:               %[[VAL_74:.*]] = arith.addf %[[VAL_72]], %[[VAL_73]] : f32
// CHECK:               linalg.yield %[[VAL_74]] : f32
// CHECK:             }
// CHECK:           %[[VAL_75:.*]] = memref.cast %[[VAL_1]] : memref<*xf32> to memref<?xf32>
// CHECK:           linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel"]} ins(%[[VAL_18]], %[[VAL_71]] : tensor<4xi32>, tensor<4xf32>) {
// CHECK:           ^bb0(%[[VAL_76:.*]]: i32, %[[VAL_77:.*]]: f32):
// CHECK:             %[[VAL_78:.*]] = arith.index_cast %[[VAL_76]] : i32 to index
// CHECK:             memref.store %[[VAL_77]], %[[VAL_75]]{{\[}}%[[VAL_78]]] : memref<?xf32>
// CHECK:             linalg.yield
// CHECK:           }
// CHECK:           return
// CHECK:         }
  tt.func @masked_sum_rank2_fallback(%in : !tt.ptr<f32>, %out : !tt.ptr<f32>, %rows : i32, %cols : i32) {
    %cst = arith.constant 0.000000e+00 : f32
    %0 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %1 = tt.expand_dims %0 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
    %2 = tt.broadcast %1 : tensor<4x1xi32> -> tensor<4x8xi32>
    %3 = tt.make_range {end = 8 : i32, start = 0 : i32} : tensor<8xi32>
    %4 = tt.expand_dims %3 {axis = 0 : i32} : tensor<8xi32> -> tensor<1x8xi32>
    %5 = tt.broadcast %4 : tensor<1x8xi32> -> tensor<4x8xi32>
    %c8 = arith.constant 8 : i32
    %6 = tt.splat %cols : i32 -> tensor<4x8xi32>
    %7 = arith.cmpi slt, %5, %6 : tensor<4x8xi32>
    %8 = tt.splat %c8 : i32 -> tensor<4x8xi32>
    %9 = arith.muli %2, %8 : tensor<4x8xi32>
    %10 = arith.addi %9, %5 : tensor<4x8xi32>
    %11 = tt.splat %in : !tt.ptr<f32> -> tensor<4x8x!tt.ptr<f32>>
    %12 = tt.addptr %11, %10 : tensor<4x8x!tt.ptr<f32>>, tensor<4x8xi32>
    %13 = tt.splat %cst : f32 -> tensor<4x8xf32>
    %14 = tt.load %12, %7, %13 : tensor<4x8x!tt.ptr<f32>>
    %15 = "tt.reduce"(%14) ({
    ^bb0(%arg0: f32, %arg1: f32):
      %16 = arith.addf %arg0, %arg1 : f32
      tt.reduce.return %16 : f32
    }) {axis = 1 : i32} : (tensor<4x8xf32>) -> tensor<4xf32>
    %16 = tt.splat %out : !tt.ptr<f32> -> tensor<4x!tt.ptr<f32>>
    tt.store %16, %15 : tensor<4x!tt.ptr<f32>>
    tt.return
  }
}
