// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --triton-to-linalg-experimental="structured-ldst-mode=tensor-first-vector-cpu" %s | FileCheck %s

// CHECK-LABEL:   func.func @kernel(
// CHECK-SAME:                      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xbf16>,
// CHECK-SAME:                      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xbf16>,
// CHECK-SAME:                      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:                      %[[ARG9:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 130 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 259 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 3 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 128 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 256 : index
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG2]] : i32 to index
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[INDEX_CAST_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[SUBI_0:.*]] = arith.subi %[[MAXSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG3]] : i32 to index
// CHECK:           %[[MINSI_1:.*]] = arith.minsi %[[INDEX_CAST_1]], %[[CONSTANT_2]] : index
// CHECK:           %[[MAXSI_1:.*]] = arith.maxsi %[[MINSI_1]], %[[CONSTANT_3]] : index
// CHECK:           %[[SUBI_1:.*]] = arith.subi %[[MAXSI_1]], %[[CONSTANT_3]] : index
// CHECK:           %[[MINSI_2:.*]] = arith.minsi %[[SUBI_0]], %[[CONSTANT_4]] : index
// CHECK:           %[[MINSI_3:.*]] = arith.minsi %[[SUBI_1]], %[[CONSTANT_5]] : index
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[ARG0]] to offset: [3074], sizes: [128, 256], strides: [1, 1024] : memref<*xbf16> to memref<128x256xbf16, strided<[1, 1024], offset: 3074>>
// CHECK:           %[[SUBVIEW_0:.*]] = memref.subview %[[REINTERPRET_CAST_0]][0, 0] {{\[}}%[[MINSI_2]], %[[MINSI_3]]] [1, 1] : memref<128x256xbf16, strided<[1, 1024], offset: 3074>> to memref<?x?xbf16, strided<[1, 1024], offset: 3074>>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[SUBVIEW_0]] : memref<?x?xbf16, strided<[1, 1024], offset: 3074>> to memref<?x?xbf16, strided<[1, 1024], offset: ?>>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[CAST_0]] restrict : memref<?x?xbf16, strided<[1, 1024], offset: ?>> to tensor<?x?xbf16>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: [3074], sizes: [128, 256], strides: [1, 1024] : memref<*xbf16> to memref<128x256xbf16, strided<[1, 1024], offset: 3074>>
// CHECK:           %[[SUBVIEW_1:.*]] = memref.subview %[[REINTERPRET_CAST_1]][0, 0] {{\[}}%[[MINSI_2]], %[[MINSI_3]]] [1, 1] : memref<128x256xbf16, strided<[1, 1024], offset: 3074>> to memref<?x?xbf16, strided<[1, 1024], offset: 3074>>
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[SUBVIEW_1]] : memref<?x?xbf16, strided<[1, 1024], offset: 3074>> to memref<?x?xbf16, strided<[1, 1024], offset: ?>>
// CHECK:           bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[CAST_1]] : (tensor<?x?xbf16>, memref<?x?xbf16, strided<[1, 1024], offset: ?>>) -> ()
// CHECK:           return
// CHECK:         }
module {
  tt.func @kernel(%arg0: !tt.ptr<bf16>, %arg1: !tt.ptr<bf16>, %arg2: i32, %arg3: i32) {
    %in_ptrs = tt.splat %arg0 : !tt.ptr<bf16> -> tensor<128x256x!tt.ptr<bf16>>
    %out_ptrs = tt.splat %arg1 : !tt.ptr<bf16> -> tensor<128x256x!tt.ptr<bf16>>

    %x = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32>
    %c2 = arith.constant 2 : i32
    %c2s = tt.splat %c2 : i32 -> tensor<128xi32>
    %x2 = arith.addi %x, %c2s : tensor<128xi32>
    %x2e = tt.expand_dims %x2 {axis = 1 : i32} : tensor<128xi32> -> tensor<128x1xi32>
    %xb = tt.broadcast %x2e : tensor<128x1xi32> -> tensor<128x256xi32>

    %y = tt.make_range {end = 256 : i32, start = 0 : i32} : tensor<256xi32>
    %c3 = arith.constant 3 : i32
    %c3s = tt.splat %c3 : i32 -> tensor<256xi32>
    %y3 = arith.addi %y, %c3s : tensor<256xi32>
    %c1024 = arith.constant 1024 : i32
    %c1024s = tt.splat %c1024 : i32 -> tensor<256xi32>
    %y3s = arith.muli %y3, %c1024s : tensor<256xi32>
    %y3e = tt.expand_dims %y3s {axis = 0 : i32} : tensor<256xi32> -> tensor<1x256xi32>
    %yb = tt.broadcast %y3e : tensor<1x256xi32> -> tensor<128x256xi32>

    %idx = arith.addi %xb, %yb : tensor<128x256xi32>
    %ldptr = tt.addptr %in_ptrs, %idx : tensor<128x256x!tt.ptr<bf16>>, tensor<128x256xi32>
    %stptr = tt.addptr %out_ptrs, %idx : tensor<128x256x!tt.ptr<bf16>>, tensor<128x256xi32>

    %other_s = arith.constant 0xFF80 : bf16
    %other = tt.splat %other_s : bf16 -> tensor<128x256xbf16>
    %arg2s = tt.splat %arg2 : i32 -> tensor<128xi32>
    %mx = arith.cmpi slt, %x2, %arg2s : tensor<128xi32>
    %mxe = tt.expand_dims %mx {axis = 1 : i32} : tensor<128xi1> -> tensor<128x1xi1>
    %mxb = tt.broadcast %mxe : tensor<128x1xi1> -> tensor<128x256xi1>
    %arg3s = tt.splat %arg3 : i32 -> tensor<256xi32>
    %my = arith.cmpi slt, %y3, %arg3s : tensor<256xi32>
    %mye = tt.expand_dims %my {axis = 0 : i32} : tensor<256xi1> -> tensor<1x256xi1>
    %myb = tt.broadcast %mye : tensor<1x256xi1> -> tensor<128x256xi1>
    %mask = arith.andi %mxb, %myb : tensor<128x256xi1>

    %vals = tt.load %ldptr, %mask, %other : tensor<128x256x!tt.ptr<bf16>>
    tt.store %stptr, %vals, %mask : tensor<128x256x!tt.ptr<bf16>>
    tt.return
  }
}
