// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --triton-to-linalg-experimental="structured-ldst-mode=tensor-first-vector-cpu" %s | FileCheck %s

// CHECK: #[[$ATTR_0:.+]] = affine_map<(d0, d1) -> (d0, d1)>
// CHECK-LABEL:   func.func @tensor_add_2d_tensor_first(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: memref<*xf32>,
// CHECK-SAME:      %[[ARG3:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG4:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG5:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG6:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG7:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32,
// CHECK-SAME:      %[[ARG8:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: i32) {
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[ARG0]] to offset: [0], sizes: [4, 4], strides: [4, 1] : memref<*xf32> to memref<4x4xf32, strided<[4, 1]>>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[REINTERPRET_CAST_0]] restrict : memref<4x4xf32, strided<[4, 1]>> to tensor<4x4xf32>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[ARG1]] to offset: [0], sizes: [4, 4], strides: [4, 1] : memref<*xf32> to memref<4x4xf32, strided<[4, 1]>>
// CHECK:           %[[TO_TENSOR_1:.*]] = bufferization.to_tensor %[[REINTERPRET_CAST_1]] restrict : memref<4x4xf32, strided<[4, 1]>> to tensor<4x4xf32>
// CHECK:           %[[GENERIC_0:.*]] = linalg.generic {indexing_maps = [#[[$ATTR_0]], #[[$ATTR_0]], #[[$ATTR_0]]], iterator_types = ["parallel", "parallel"]} ins(%[[TO_TENSOR_0]], %[[TO_TENSOR_1]] : tensor<4x4xf32>, tensor<4x4xf32>) outs(%[[TO_TENSOR_0]] : tensor<4x4xf32>) {
// CHECK:           ^bb0(%[[VAL_0:.*]]: f32, %[[VAL_1:.*]]: f32, %[[VAL_2:.*]]: f32):
// CHECK:             %[[ADDF_0:.*]] = arith.addf %[[VAL_0]], %[[VAL_1]] : f32
// CHECK:             linalg.yield %[[ADDF_0]] : f32
// CHECK:           } -> tensor<4x4xf32>
// CHECK:           %[[REINTERPRET_CAST_2:.*]] = memref.reinterpret_cast %[[ARG2]] to offset: [0], sizes: [4, 4], strides: [4, 1] : memref<*xf32> to memref<4x4xf32, strided<[4, 1]>>
// CHECK:           bufferization.materialize_in_destination %[[GENERIC_0]] in writable %[[REINTERPRET_CAST_2]] : (tensor<4x4xf32>, memref<4x4xf32, strided<[4, 1]>>) -> ()
// CHECK:           return
// CHECK:         }
module {
  tt.func public @tensor_add_2d_tensor_first(%a: !tt.ptr<f32>, %b: !tt.ptr<f32>, %c: !tt.ptr<f32>) {
    %r0 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %r1 = tt.make_range {end = 4 : i32, start = 0 : i32} : tensor<4xi32>
    %a_s = tt.splat %a : !tt.ptr<f32> -> tensor<4x4x!tt.ptr<f32>>
    %b_s = tt.splat %b : !tt.ptr<f32> -> tensor<4x4x!tt.ptr<f32>>
    %c_s = tt.splat %c : !tt.ptr<f32> -> tensor<4x4x!tt.ptr<f32>>
    %r0e = tt.expand_dims %r0 {axis = 1 : i32} : tensor<4xi32> -> tensor<4x1xi32>
    %r1e = tt.expand_dims %r1 {axis = 0 : i32} : tensor<4xi32> -> tensor<1x4xi32>
    %r0b = tt.broadcast %r0e : tensor<4x1xi32> -> tensor<4x4xi32>
    %r1b = tt.broadcast %r1e : tensor<1x4xi32> -> tensor<4x4xi32>
    %c4 = arith.constant 4 : i32
    %c4s = tt.splat %c4 : i32 -> tensor<4x4xi32>
    %r0s = arith.muli %r0b, %c4s : tensor<4x4xi32>
    %idx = arith.addi %r0s, %r1b : tensor<4x4xi32>
    %pa = tt.addptr %a_s, %idx : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32>
    %pb = tt.addptr %b_s, %idx : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32>
    %pc = tt.addptr %c_s, %idx : tensor<4x4x!tt.ptr<f32>>, tensor<4x4xi32>
    %va = tt.load %pa : tensor<4x4x!tt.ptr<f32>>
    %vb = tt.load %pb : tensor<4x4x!tt.ptr<f32>>
    %sum = arith.addf %va, %vb : tensor<4x4xf32>
    tt.store %pc, %sum : tensor<4x4x!tt.ptr<f32>>
    tt.return
  }
}
