// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/



// RUN: triton-shared-opt --split-input-file --structured-to-memref %s | FileCheck %s

module {
// CHECK-LABEL:   tt.func public @wrap_stacked_load(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: index,
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: index) -> tensor<4x4xf32> {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[ARG1]], %[[ARG2]] : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[CONSTANT_2]], %[[ARG2]] : index
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[MULI_0]], %[[REMSI_0]] : index
// CHECK:           %[[DIVSI_0:.*]] = arith.divsi %[[ADDI_0]], %[[ARG2]] : index
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[DIVSI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[SUBI_0:.*]] = arith.subi %[[CONSTANT_1]], %[[MINSI_0]] : index
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[CONSTANT_2]]], sizes: {{\[}}%[[MINSI_0]], %[[CONSTANT_1]]], strides: {{\[}}%[[ARG2]], %[[CONSTANT_0]]] : memref<*xf32> to memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[REMSI_0]]], sizes: {{\[}}%[[SUBI_0]], %[[CONSTANT_1]]], strides: {{\[}}%[[ARG2]], %[[CONSTANT_0]]] : memref<*xf32> to memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4x4xf32>
// CHECK:           %[[DIM_0:.*]] = memref.dim %[[REINTERPRET_CAST_0]], %[[CONSTANT_2]] : memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[DIM_1:.*]] = memref.dim %[[REINTERPRET_CAST_0]], %[[CONSTANT_0]] : memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[DIM_2:.*]] = memref.dim %[[REINTERPRET_CAST_1]], %[[CONSTANT_2]] : memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[DIM_3:.*]] = memref.dim %[[REINTERPRET_CAST_1]], %[[CONSTANT_0]] : memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[CONSTANT_2]], %[[CONSTANT_2]]] {{\[}}%[[DIM_0]], %[[DIM_1]]] {{\[}}%[[CONSTANT_0]], %[[CONSTANT_0]]] : memref<4x4xf32> to memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[SUBVIEW_1:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[DIM_0]], %[[CONSTANT_2]]] {{\[}}%[[DIM_2]], %[[DIM_3]]] {{\[}}%[[CONSTANT_0]], %[[CONSTANT_0]]] : memref<4x4xf32> to memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<?x?xf32, strided<[?, ?], offset: ?>> to memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_1]], %[[SUBVIEW_1]] : memref<?x?xf32, strided<[?, ?], offset: ?>> to memref<?x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4x4xf32> to tensor<4x4xf32>
// CHECK:           tt.return %[[TO_TENSOR_0]] : tensor<4x4xf32>
// CHECK:         }
  tt.func public @wrap_stacked_load(%arg0: !tt.ptr<f32>, %M: index, %N: index) -> tensor<4x4xf32> {
    %0 = arith.muli %M, %N : index
    %1 = tts.make_tptr %arg0 to sizes: [4, 4], strides: [%N, 1], offsets: [0, 0], shape: [%0, 0], order: [] : <f32> to tensor<4x4x!tt.ptr<f32>>
    %2 = "tts.load"(%1) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (tensor<4x4x!tt.ptr<f32>>) -> tensor<4x4xf32>
    tt.return %2 : tensor<4x4xf32>
  }
}
