// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// This script is intended to make adding checks to a test case quick and easy.
// It is *not* authoritative about what constitutes a good test. After using the
// script, be sure to review and refine the generated checks. For example,
// CHECK lines should be minimized and named to reflect the test’s intent.
// For comprehensive guidelines, see:
//   * https://mlir.llvm.org/getting_started/TestingGuide/


// RUN: triton-shared-opt --structured-to-memref --canonicalize %s | FileCheck %s

// CHECK-LABEL:   tt.func public @triton_tem_fused_mm_0(
// CHECK-SAME:      %[[ARG0:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG1:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32},
// CHECK-SAME:      %[[ARG2:[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*]]: !tt.ptr<f32> {tt.divisibility = 16 : i32}) attributes {noinline = false} {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 8 : i32
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 128 : i32
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant dense<0.000000e+00> : tensor<128x128xf32>
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant 8 : index
// CHECK:           %[[CONSTANT_8:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[CONSTANT_9:.*]] = arith.constant 16 : index
// CHECK:           %[[CONSTANT_10:.*]] = arith.constant 128 : index
// CHECK:           %[[GET_PROGRAM_ID_0:.*]] = tt.get_program_id x : i32
// CHECK:           %[[DIVSI_0:.*]] = arith.divsi %[[GET_PROGRAM_ID_0]], %[[CONSTANT_2]] : i32
// CHECK:           %[[MULI_0:.*]] = arith.muli %[[DIVSI_0]], %[[CONSTANT_2]] : i32
// CHECK:           %[[SUBI_0:.*]] = arith.subi %[[CONSTANT_5]], %[[MULI_0]] : i32
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[SUBI_0]], %[[CONSTANT_2]] : i32
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[GET_PROGRAM_ID_0]], %[[MINSI_0]] : i32
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[MULI_0]], %[[REMSI_0]] : i32
// CHECK:           %[[REMSI_1:.*]] = arith.remsi %[[GET_PROGRAM_ID_0]], %[[CONSTANT_2]] : i32
// CHECK:           %[[DIVSI_1:.*]] = arith.divsi %[[REMSI_1]], %[[MINSI_0]] : i32
// CHECK:           %[[MULI_1:.*]] = arith.muli %[[ADDI_0]], %[[CONSTANT_3]] : i32
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[MULI_1]] : i32 to index
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[MULI_1]] : i32 to index
// CHECK:           %[[MULI_2:.*]] = arith.muli %[[DIVSI_1]], %[[CONSTANT_3]] : i32
// CHECK:           %[[INDEX_CAST_2:.*]] = arith.index_cast %[[MULI_2]] : i32 to index
// CHECK:           %[[INDEX_CAST_3:.*]] = arith.index_cast %[[MULI_2]] : i32 to index
// CHECK:           %[[MULI_3:.*]] = arith.muli %[[INDEX_CAST_1]], %[[CONSTANT_7]] : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[REMSI_2:.*]] = arith.remsi %[[MULI_3]], %[[CONSTANT_7]] : index
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[REMSI_2]], %[[CONSTANT_9]] : index
// CHECK:           %[[SUBI_1:.*]] = arith.subi %[[ADDI_1]], %[[MULI_3]] : index
// CHECK:           %[[DIVSI_2:.*]] = arith.divsi %[[SUBI_1]], %[[CONSTANT_7]] : index
// CHECK:           %[[MINSI_1:.*]] = arith.minsi %[[DIVSI_2]], %[[CONSTANT_10]] : index
// CHECK:           %[[SUBI_2:.*]] = arith.subi %[[CONSTANT_10]], %[[MINSI_1]] : index
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[MULI_3]]], sizes: {{\[}}%[[MINSI_1]], 32], strides: [8, 1] : memref<*xf32> to memref<?x32xf32, strided<[8, 1], offset: ?>>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[REMSI_2]]], sizes: {{\[}}%[[SUBI_2]], 32], strides: [8, 1] : memref<*xf32> to memref<?x32xf32, strided<[8, 1], offset: ?>>
// CHECK:           %[[EMPTY_0:.*]] = tensor.empty() : tensor<128x32xf32>
// CHECK:           %[[FILL_0:.*]] = linalg.fill ins(%[[CONSTANT_8]] : f32) outs(%[[EMPTY_0]] : tensor<128x32xf32>) -> tensor<128x32xf32>
// CHECK:           %[[DIM_0:.*]] = memref.dim %[[REINTERPRET_CAST_0]], %[[CONSTANT_0]] : memref<?x32xf32, strided<[8, 1], offset: ?>>
// CHECK:           %[[DIM_1:.*]] = memref.dim %[[REINTERPRET_CAST_1]], %[[CONSTANT_0]] : memref<?x32xf32, strided<[8, 1], offset: ?>>
// CHECK:           %[[SUBVIEW_0:.*]] = memref.subview %[[REINTERPRET_CAST_0]][0, 0] {{\[}}%[[DIM_0]], 8] [1, 1] : memref<?x32xf32, strided<[8, 1], offset: ?>> to memref<?x8xf32, strided<[8, 1], offset: ?>>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[SUBVIEW_0]] : memref<?x8xf32, strided<[8, 1], offset: ?>> to memref<?x8xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[SUBVIEW_1:.*]] = memref.subview %[[REINTERPRET_CAST_1]][0, 0] {{\[}}%[[DIM_1]], 8] [1, 1] : memref<?x32xf32, strided<[8, 1], offset: ?>> to memref<?x8xf32, strided<[8, 1], offset: ?>>
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[SUBVIEW_1]] : memref<?x8xf32, strided<[8, 1], offset: ?>> to memref<?x8xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[CAST_0]] restrict : memref<?x8xf32, strided<[?, ?], offset: ?>> to tensor<?x8xf32>
// CHECK:           %[[TO_TENSOR_1:.*]] = bufferization.to_tensor %[[CAST_1]] restrict : memref<?x8xf32, strided<[?, ?], offset: ?>> to tensor<?x8xf32>
// CHECK:           %[[INSERT_SLICE_0:.*]] = tensor.insert_slice %[[TO_TENSOR_0]] into %[[FILL_0]][0, 0] {{\[}}%[[DIM_0]], 8] [1, 1] : tensor<?x8xf32> into tensor<128x32xf32>
// CHECK:           %[[INSERT_SLICE_1:.*]] = tensor.insert_slice %[[TO_TENSOR_1]] into %[[INSERT_SLICE_0]]{{\[}}%[[DIM_0]], 0] {{\[}}%[[DIM_1]], 8] [1, 1] : tensor<?x8xf32> into tensor<128x32xf32>
// CHECK:           %[[MULI_4:.*]] = arith.muli %[[INDEX_CAST_3]], %[[CONSTANT_7]] : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[REMSI_3:.*]] = arith.remsi %[[MULI_4]], %[[CONSTANT_10]] : index
// CHECK:           %[[SUBI_3:.*]] = arith.subi %[[MULI_4]], %[[REMSI_3]] : index
// CHECK:           %[[ADDI_2:.*]] = arith.addi %[[REMSI_3]], %[[CONSTANT_10]] : index
// CHECK:           %[[MINSI_2:.*]] = arith.minsi %[[ADDI_2]], %[[CONSTANT_10]] : index
// CHECK:           %[[SUBI_4:.*]] = arith.subi %[[MINSI_2]], %[[REMSI_3]] : index
// CHECK:           %[[SUBI_5:.*]] = arith.subi %[[CONSTANT_10]], %[[SUBI_4]] : index
// CHECK:           %[[REINTERPRET_CAST_2:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[MULI_4]]], sizes: [32, %[[SUBI_4]]], strides: [1, 8] : memref<*xf32> to memref<32x?xf32, strided<[1, 8], offset: ?>>
// CHECK:           %[[REINTERPRET_CAST_3:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[SUBI_3]]], sizes: [32, %[[SUBI_5]]], strides: [1, 8] : memref<*xf32> to memref<32x?xf32, strided<[1, 8], offset: ?>>
// CHECK:           %[[EMPTY_1:.*]] = tensor.empty() : tensor<32x128xf32>
// CHECK:           %[[FILL_1:.*]] = linalg.fill ins(%[[CONSTANT_8]] : f32) outs(%[[EMPTY_1]] : tensor<32x128xf32>) -> tensor<32x128xf32>
// CHECK:           %[[DIM_2:.*]] = memref.dim %[[REINTERPRET_CAST_2]], %[[CONSTANT_1]] : memref<32x?xf32, strided<[1, 8], offset: ?>>
// CHECK:           %[[DIM_3:.*]] = memref.dim %[[REINTERPRET_CAST_3]], %[[CONSTANT_1]] : memref<32x?xf32, strided<[1, 8], offset: ?>>
// CHECK:           %[[SUBVIEW_2:.*]] = memref.subview %[[REINTERPRET_CAST_2]][0, 0] [8, %[[DIM_2]]] [1, 1] : memref<32x?xf32, strided<[1, 8], offset: ?>> to memref<8x?xf32, strided<[1, 8], offset: ?>>
// CHECK:           %[[CAST_2:.*]] = memref.cast %[[SUBVIEW_2]] : memref<8x?xf32, strided<[1, 8], offset: ?>> to memref<8x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[SUBVIEW_3:.*]] = memref.subview %[[REINTERPRET_CAST_3]][0, 0] [8, %[[DIM_3]]] [1, 1] : memref<32x?xf32, strided<[1, 8], offset: ?>> to memref<8x?xf32, strided<[1, 8], offset: ?>>
// CHECK:           %[[CAST_3:.*]] = memref.cast %[[SUBVIEW_3]] : memref<8x?xf32, strided<[1, 8], offset: ?>> to memref<8x?xf32, strided<[?, ?], offset: ?>>
// CHECK:           %[[TO_TENSOR_2:.*]] = bufferization.to_tensor %[[CAST_2]] restrict : memref<8x?xf32, strided<[?, ?], offset: ?>> to tensor<8x?xf32>
// CHECK:           %[[TO_TENSOR_3:.*]] = bufferization.to_tensor %[[CAST_3]] restrict : memref<8x?xf32, strided<[?, ?], offset: ?>> to tensor<8x?xf32>
// CHECK:           %[[INSERT_SLICE_2:.*]] = tensor.insert_slice %[[TO_TENSOR_2]] into %[[FILL_1]][0, 0] [8, %[[DIM_2]]] [1, 1] : tensor<8x?xf32> into tensor<32x128xf32>
// CHECK:           %[[INSERT_SLICE_3:.*]] = tensor.insert_slice %[[TO_TENSOR_3]] into %[[INSERT_SLICE_2]][0, %[[DIM_2]]] [8, %[[DIM_3]]] [1, 1] : tensor<8x?xf32> into tensor<32x128xf32>
// CHECK:           %[[DOT_0:.*]] = tt.dot %[[INSERT_SLICE_1]], %[[INSERT_SLICE_3]], %[[CONSTANT_4]] : tensor<128x32xf32> * tensor<32x128xf32> -> tensor<128x128xf32>
// CHECK:           %[[MULI_5:.*]] = arith.muli %[[INDEX_CAST_0]], %[[CONSTANT_9]] : index
// CHECK:           %[[INDEX_CAST_4:.*]] = arith.index_cast %[[MULI_1]] : i32 to index
// CHECK:           %[[ADDI_3:.*]] = arith.addi %[[INDEX_CAST_4]], %[[CONSTANT_10]] : index
// CHECK:           %[[MINSI_3:.*]] = arith.minsi %[[ADDI_3]], %[[CONSTANT_6]] : index
// CHECK:           %[[MAXSI_0:.*]] = arith.maxsi %[[MINSI_3]], %[[INDEX_CAST_4]] : index
// CHECK:           %[[SUBI_6:.*]] = arith.subi %[[MAXSI_0]], %[[INDEX_CAST_4]] : index
// CHECK:           %[[INDEX_CAST_5:.*]] = arith.index_cast %[[MULI_2]] : i32 to index
// CHECK:           %[[ADDI_4:.*]] = arith.addi %[[INDEX_CAST_5]], %[[CONSTANT_10]] : index
// CHECK:           %[[MINSI_4:.*]] = arith.minsi %[[ADDI_4]], %[[CONSTANT_9]] : index
// CHECK:           %[[MAXSI_1:.*]] = arith.maxsi %[[MINSI_4]], %[[INDEX_CAST_5]] : index
// CHECK:           %[[SUBI_7:.*]] = arith.subi %[[MAXSI_1]], %[[INDEX_CAST_5]] : index
// CHECK:           %[[MINSI_5:.*]] = arith.minsi %[[SUBI_6]], %[[CONSTANT_10]] : index
// CHECK:           %[[MINSI_6:.*]] = arith.minsi %[[SUBI_7]], %[[CONSTANT_10]] : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_2:.*]] = builtin.unrealized_conversion_cast %[[ARG2]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ADDI_5:.*]] = arith.addi %[[MULI_5]], %[[INDEX_CAST_2]] : index
// CHECK:           %[[REINTERPRET_CAST_4:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_2]] to offset: {{\[}}%[[ADDI_5]]], sizes: [128, 128], strides: [16, 1] : memref<*xf32> to memref<128x128xf32, strided<[16, 1], offset: ?>>
// CHECK:           %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[DOT_0]][0, 0] {{\[}}%[[MINSI_5]], %[[MINSI_6]]] [1, 1] : tensor<128x128xf32> to tensor<?x?xf32>
// CHECK:           %[[SUBVIEW_4:.*]] = memref.subview %[[REINTERPRET_CAST_4]][0, 0] {{\[}}%[[MINSI_5]], %[[MINSI_6]]] [1, 1] : memref<128x128xf32, strided<[16, 1], offset: ?>> to memref<?x?xf32, strided<[16, 1], offset: ?>>
// CHECK:           bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[SUBVIEW_4]] : (tensor<?x?xf32>, memref<?x?xf32, strided<[16, 1], offset: ?>>) -> ()
// CHECK:           tt.return
// CHECK:         }
module {
  tt.func public @triton_tem_fused_mm_0(%arg0: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg1: !tt.ptr<f32> {tt.divisibility = 16 : i32}, %arg2: !tt.ptr<f32> {tt.divisibility = 16 : i32}) attributes {noinline = false} {
    %c128 = arith.constant 128 : index
    %c16 = arith.constant 16 : index
    %cst = arith.constant 0.000000e+00 : f32
    %c8 = arith.constant 8 : index
    %c2 = arith.constant 2 : index
    %c1_i32 = arith.constant 1 : i32
    %cst_0 = arith.constant dense<0.000000e+00> : tensor<128x128xf32>
    %c128_i32 = arith.constant 128 : i32
    %c8_i32 = arith.constant 8 : i32
    %0 = tt.get_program_id x : i32
    %1 = arith.divsi %0, %c8_i32 : i32
    %2 = arith.muli %1, %c8_i32 : i32
    %3 = arith.subi %c1_i32, %2 : i32
    %4 = arith.minsi %3, %c8_i32 : i32
    %5 = arith.remsi %0, %4 : i32
    %6 = arith.addi %2, %5 : i32
    %7 = arith.remsi %0, %c8_i32 : i32
    %8 = arith.divsi %7, %4 : i32
    %9 = arith.muli %6, %c128_i32 : i32
    %10 = arith.index_cast %9 : i32 to index
    %11 = arith.index_cast %9 : i32 to index
    %12 = arith.muli %8, %c128_i32 : i32
    %13 = arith.index_cast %12 : i32 to index
    %14 = arith.index_cast %12 : i32 to index
    %15 = arith.muli %11, %c8 : index
    %16 = tts.make_tptr %arg0 to sizes: [128, 32], strides: [%c8, 1], offsets: [%15, 0], shape: [16, 0], order: [] : <f32> to tensor<128x32x!tt.ptr<f32>>
    %17 = "tts.load"(%16, %cst) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64: 128, 8>}> : (tensor<128x32x!tt.ptr<f32>>, f32) -> tensor<128x32xf32>
    %18 = arith.muli %14, %c8 : index
    %19 = tts.make_tptr %arg1 to sizes: [32, 128], strides: [1, %c8], offsets: [0, %18], shape: [0, 128], order: [] : <f32> to tensor<32x128x!tt.ptr<f32>>
    %20 = "tts.load"(%19, %cst) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64: 8, 128>}> : (tensor<32x128x!tt.ptr<f32>>, f32) -> tensor<32x128xf32>
    %21 = tt.dot %17, %20, %cst_0 : tensor<128x32xf32> * tensor<32x128xf32> -> tensor<128x128xf32>
    %22 = arith.muli %10, %c16 : index
    %23 = tts.make_tptr %arg2 to sizes: [128, 128], strides: [%c16, 1], offsets: [%22, %13], shape: [0, 0], order: [] : <f32> to tensor<128x128x!tt.ptr<f32>>
    %24 = arith.index_cast %9 : i32 to index
    %25 = arith.addi %24, %c128 : index
    %26 = arith.minsi %25, %c2 : index
    %27 = arith.maxsi %26, %24 : index
    %28 = arith.subi %27, %24 : index
    %29 = arith.index_cast %12 : i32 to index
    %30 = arith.addi %29, %c128 : index
    %31 = arith.minsi %30, %c16 : index
    %32 = arith.maxsi %31, %29 : index
    %33 = arith.subi %32, %29 : index
    %34 = arith.minsi %28, %c128 : index
    %35 = arith.minsi %33, %c128 : index
    "tts.store"(%23, %21, %34, %35) <{static_mask_dims = array<i64: -9223372036854775808, -9223372036854775808>}> : (tensor<128x128x!tt.ptr<f32>>, tensor<128x128xf32>, index, index) -> ()
    tt.return
  }
}
